docs/changelog.md, docs/type-support.md, sematic/types/BUILD, sematic/types/__init__.py, sematic/types/registry.py, sematic/types/types/BUILD, sematic/types/types/tests/BUILD, sematic/types/types/tests/test_tuple.py, sematic/types/types/tuple.py, sematic/ui/src/types/Types.tsx
Users should be able to use `Tuple` types in their Sematic functions:
```python
@sematic.func
def tuple_tuple(input: Tuple[float, str, bool]) -> Tuple[float, str, bool]:
return input
tuple_tuple((42, "abc", True)).resolve()
```
=> Tuple support, SDK + UI

docs/changelog.md, docs/execution-modes.md, docs/first-pipeline.md, docs/get-started.md, sematic/examples/add/__main__.py, sematic/types/BUILD, sematic/types/__init__.py, sematic/types/types/BUILD, sematic/types/types/dict.py, sematic/types/types/tests/BUILD, sematic/types/types/tests/test_dict.py, sematic/types/types/tuple.py, sematic/ui/src/types/Types.tsx
Users should be able to do
```python
@sematic.finc
def pipeline(input: Dict[str, float]) -> Dict[str, float]:
return input
pipeline(dict(a=123).resolve()
```
UI treatment:
=> Support for dictionaries: SDK + UI

docs/execution-modes.md
Fix the link to public roadmap on Trello
=> fix public roadmap link in docs

docs/changelog.md, docs/future-algebra.md, requirements/ci-requirements.txt, sematic/BUILD, sematic/__init__.py, sematic/future_operators/BUILD, sematic/future_operators/__init__.py, sematic/future_operators/getitem.py, sematic/future_operators/iter.py, sematic/future_operators/tests/BUILD, sematic/future_operators/tests/test_getitem.py, sematic/future_operators/tests/test_iter.py, sematic/tests/test_future.py
Now users can do
```python
@sematic.func
def foo() -> Tuple[int, str]:
return 42, "foo"
@sematic.func
def pipeline() -> str:
a = foo()[1]
return a
```
and
```python
@sematic.func
def foo() -> Tuple[int, str]:
return 42, "foo"
@sematic.func
def pipeline() -> str:
a, b = foo()
return b
```
=> Support for getitem and iter on futures

sematic/db/models/factories.py, sematic/types/types/pandas/dataframe.py, sematic/types/types/pandas/tests/BUILD, sematic/types/types/pandas/tests/test_dataframe.py
=> Fixes Timestamp JSON serialization by defaulting to `str`

docs/changelog.md, sematic/__init__.py
Addresses https://github.com/sematic-ai/sematic/issues/73
Users can currently receive a message like this if they try to use Sematic with invalid python versions:
```
from typing import (  # type: ignore
ImportError: cannot import name 'GenericAlias' from 'typing' (/usr/lib/python3.7/typing.py)
```
For folks installing with pip, this shouldn't be possible, but other mechanisms of depending on sematic might make it possible to try it with older interpreters. For such users, we should make the message more explicit.
This turns out to be surprisingly difficult to write an automated test for, since the mocking/patching libs apparently rely on importing the module first to apply the patch (makes sense, but it means that we can't mock the current/min versions before the checking code has …
=> Add friendly error message for bad python versions

docs/SUMMARY.md, docs/types.md, sematic/types/BUILD, sematic/types/__init__.py, sematic/types/types/BUILD, sematic/types/types/link.py, sematic/types/types/tests/BUILD, sematic/types/types/tests/test_link.py, sematic/ui/src/types/Types.tsx
This PR introduces a new `Link` type that enables users to display links in the UI.
```python
link = Link(label="Sematic documentation", url="https://docs.sematic.dev")
```
The type validates the passed `url` simply by checking that it has a `scheme` and `netloc`.
=> New `Link` type to display buttons in the UI

docs/changelog.md, sematic/BUILD, sematic/__init__.py, sematic/api/BUILD, sematic/api/endpoints/BUILD, sematic/api/endpoints/auth.py, sematic/api/endpoints/meta.py, sematic/api/endpoints/tests/BUILD, sematic/api/endpoints/tests/test_auth.py, sematic/api/endpoints/tests/test_meta.py, sematic/api/server.py, sematic/api/tests/fixtures.py, sematic/api_client.py, sematic/tests/BUILD, sematic/tests/test_api_client.py, sematic/types/types/pandas/dataframe.py, sematic/ui/src/index.tsx, sematic/utils/BUILD, sematic/utils/retry.py, sematic/versions.py
We may make some backwards incompatible changes to the server API, especially in these early days. To save users the trouble of hitting a weird compatibility issue with a cryptic error, let's generate an explicit message telling people when their client code won't work with the server.
Testing
-------
In addition to the unit tests, I ran the server locally and then ran an example pipeline to make sure it worked well. I also (inadvertently) ran the new client code against an old server and confirmed I got an appropriate error.
=> Version compatibility check

developer-docs/tips-for-bazel.md, docs/contributor-guide.md, requirements/requirements.in, requirements/requirements.txt, tools/pytest_runner.py, tools/sematic_rules.bzl
Because I'm tired of setting up VS code debugging hackily for specific tests when I need it, then undoing all the code changes when I'm done, I thought I'd add it as something automatically available when you execute tests, via only a change on the command line invocation.
=> Add debugpy as automatically available

sematic/ui/src/types/Types.tsx
We had a bug when the summary of a list view didn't contain any elements. We were running an array reduce on the summary, but array reductions are undefined for empty lists. This makes it so we handle "empty list" as a special case for display.
=> Improve empty list handling

docs/cli.md, sematic/config_dir.py, sematic/tests/BUILD, sematic/tests/fixtures.py, sematic/tests/test_config_dir.py
Sometimes people want to run Sematic in an environment where they don't have write permission for the home directory. Also, people may wish to maintain multiple sets of Sematic configs at once. We can enable this by allowing an env var to determine where the Sematic config dir should be.
In addition to unit tests, I also did `sematic settings show` with this code to ensure that my current settings still show. I also set `SEMATIC_CONFIG_DIR` to absolute and relative paths and ensured that Sematic created and used the specified dirs.
=> Add ability to change config dir with env var

docs/changelog.md, docs/execution-modes.md, sematic/config.py, sematic/examples/mnist/pytorch/pipeline.py, sematic/resolvers/cloud_resolver.py, sematic/resolvers/resource_requirements.py, sematic/tests/test_calculator.py
Currently you can specify what kind of node your job's pod runs on, but you can't specify how many resources on that node should be allocated to your individual pod. This PR makes it possible to specify resources required for the pod.
=> Add ability to specify required CPU/Mem

docs/execution-modes.md
Swap the descriptions for the `inline` parameter to match the values in the columns of the table (`True` is in the driver and `False` is in its own Kubernetes job and not vice versa)
=> Update execution-modes.md (swap inline True & False descriptions)

developer-docs/README.md, docs/changelog.md, sematic/api/server.py, sematic/config.py
When you are running a server in an environment like a container, it is standard for the logs to go to stdout/stderr. This PR makes it so that when running the server using the cloud mode, the logs go to stdout.
Testing
--------
Changed `server_log_to_stdout=True` briefly for the local config, and stopped/started the local server. Confirmed that the logs went to stdout. Then changed it back and stopped/started the local server. Confirmed that the logs didn't show up in stdout, but were still in the log files.
=> Have cloud server logs go to stdout

sematic/resolvers/cloud_resolver.py, sematic/resolvers/local_resolver.py
Kubernetes' autoscaler sometimes evicts pods because it wants to restructure how pods are packed in nodes. When this happens to our resolver job, we wind up creating a duplicate copy of the root run. This PR:
(a) changes the failure mode so we crash with an error message instead of duplicating things
(b) adds [an annotation](https://github.com/kubernetes/autoscaler/blob/c127763a4529d7d07961102856afe0ba8781f8ee/cluster-autoscaler/utils/drain/drain.go#L40) that k8s looks at when draining a node for purposed of autoscaling. The annotation will cause k8s to delay the scale-down while the pod is there.
Testing
-------
- Did a normal cloud execution: https://dev.sematic.cloud/pipelines/sematic.examples.bazel.pipeline.pipeline/91d8635765364ab79d1bc420197cf807
- Used `kubectl` to manually delete …
=> Improve eviction handling

sematic/db/migrations/20220830211101_persist_resource_reqs.sql, sematic/db/models/BUILD, sematic/db/models/factories.py, sematic/db/models/run.py, sematic/db/models/tests/test_factories.py, sematic/db/schema.sql.sqlite, sematic/examples/add/pipeline.py, sematic/types/types/dataclass.py, sematic/types/types/dict.py, sematic/types/types/tests/test_dict.py
Addresses #98
`ResourceRequirements` let users specify function-specific resource requirements. For example, a function can specify that it needs a particular type of Kubernetes node (e.g. GPU, high-mem).
At this time, these are used at runtime when launching K8s jobs, but they are not persisted in the DB. Persisting them is necessary to enable re-running pipelines from the UI and CLI, as well as to move kubernetes job launches behind the server.
Testing
-------
In addition to the unit tests, I ran the "add" pipeline with resource requirements set and confirmed they were in the DB.
=> Persist resource reqs in DB

sematic/api_client.py
When Sematic tries to verify that the server version is compatible, it's always the first API call that gets made. One failure mode is that the request receives a response, but that response is NOT a valid version metadata response from a Sematic server. This can have basically two causes:
(a) deployment is older than Sematic v0.9.0
(b) the URL points to *something* but it's not a valid Sematic deployment.
(a) shouldn't be worth worrying about at this point; people with cloud deployments seem to be updating regularly. (b) can happen under a variety of circumstances--people point to something random (ex: `http://example.com`) or their Sematic is behind a reverse proxy of some kind and the reverse proxy is broken. In this situation, people should figure out why that is.
The current error …
=> Improve bad URL error

docs/SUMMARY.md, docs/container-images.md, docs/deploy.md, docs/execution-modes.md
Currently it's not obvious to people that after they deploy Sematic, they need to use bazel to run cloud jobs. This change makes that explicit. Also ran `Prettier` on our md to make it more standard formatted
=> Add link between deploy docs and container docs

sematic/resolvers/tests/test_log_streamer.py
One of the log ingestion tests raises an error during ingestion and asserts that the error message made it into the first upload. It's actually possible (race condition) that an upload can happen before the error message is done being written to stdout. All we really care about is that the log message makes it by the final upload. This PR makes it so that's what we assert.
=> Reduce log ingestion test flake

sematic/ui/src/components/LogPanel.tsx
I thought I had pushed this with the main logs in the UI, but looks like I didn't. Instead of an unstyled div when the server can't serve logs, give an alert.
=> Use alert when log API errors

sematic/ui/src/components/ScrollingLogView.tsx
There is some code in the log view that says "on render, if I don't have any log lines for this run, load some." There's also some code that says "if a run is in a terminal state, don't bother asking for more logs once you've gotten the initial response." It seems I forgot to test the case where a run has no log lines, but is also not in a terminal state. Under these conditions, the existing code just repeatedly spams the server asking for logs. I have changed that by basing the "needs initial load" condition from being based on the number of lines to being based on the log source.
The fix: the code already detects when there is a mismatch between the active run and the source for the current logs. It triggers a load under this circumstance. I now set the initial render to say that the …
=> Fix log spam for runs without initial logs

bazel/worker.py, sematic/log_reader.py, sematic/resolvers/worker.py, sematic/wheel_version.bzl
When people use the `sematic_pipeline` bazel macro and don't use `dev=True`, it points them to the `worker.py` in `bazel/worker.py` rather than `sematic/resolvers/worker.py`. It imported the main from there, but it missed the code that wrapped main to set up logging properly. This PR makes it so both `worker.py` scripts use the same log wrapping for `main`.
Testing
-------
- launched a cloud [run](https://dev.sematic.cloud/pipelines/sematic.examples.bazel.pipeline.pipeline/79dd03cc82044e83a3de9a4ae0f90bc2) on the dev machine from within the Sematic repo, with `dev=True`
- launched a cloud [run](https://dev.sematic.cloud/pipelines/example_bazel.pipeline.pipeline/85c5b1e46fd24343a849d9b0c77115fa) on the dev machine from the `example_bazel` repo (pointing it at this branch), with `dev=False` …
=> Wrap worker.py main more consistently

docs/changelog.md, sematic/__init__.py, sematic/calculator.py, sematic/resolvers/resource_requirements.py, sematic/resolvers/tests/BUILD, sematic/resolvers/tests/test_resource_requirements.py, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_kubernetes.py, sematic/types/BUILD, sematic/types/__init__.py, sematic/types/casting.py, sematic/types/registry.py, sematic/types/serialization.py, sematic/types/tests/test_registry.py, sematic/types/types/BUILD, sematic/types/types/enum.py, sematic/types/types/tests/BUILD, sematic/types/types/tests/test_enum.py
People may want/need more control over which nodes their jobs run on. K8s tolerations is a mechanism many people use to achieve this. If we don't support them, people may not be able to run their Sematic funcs where they want them to go. This adds support for it.
It also adds support for enums, because the natural way to support tolerations includes some enum types that are currently serialized/deserialized with Sematic's type stuff. It fails without actual enum support. I've wanted enum support a few times anyway, so I took this opportunity to "bite the bullet."
Testing
-------
Submitted [a run](https://dev.sematic.cloud/pipelines/sematic.examples.bazel.pipeline.pipeline/44fce786dafe489c8055c1b85a64a70e) that had specified tolerations and looked at the produced pod to ensure it was …
=> Add support for specifying k8s tolerations

sematic/examples/mnist/pytorch/BUILD, sematic/examples/mnist/pytorch/mnist_learning_rates.py, sematic/examples/mnist/pytorch/mnist_train.py, sematic/examples/mnist/pytorch/pipeline.py
The existing MNIST pipelines were once runnable in the cloud and have support in the BUILD file for this. This PR fixes issues in the BUILD file and also adds a cloud-runnable version of the example pipeline, in addition to the existing learning rates pipelines.
=> Make the MNIST examples runnable in the cloud

sematic/db/models/BUILD, sematic/db/models/git_info.py, sematic/db/models/resolution.py, sematic/db/models/tests/test_resolution.py, sematic/db/tests/fixtures.py, sematic/scheduling/tests/test_job_scheduler.py, sematic/utils/BUILD, sematic/utils/git.py, sematic/utils/tests/BUILD, sematic/utils/tests/test_git.py
When the `git` executable is not installed, importing the third party `git-python` package fails. Docker images build without `git` will fail when scheduled in Kubernetes.
This PR removes the dependency of code that would run on the backend server on the `git-python` package, and introduces a local safeguard for users that might submit execution from a workspace that does not have `git` installed.
Re-validated basic functionality locally, and [validated it now works on Kubernetes](https://dev.sematic.cloud/pipelines/sematic.examples.mnist.pytorch.pipeline.pipeline/b20024e7779d454aa56f384a8073aaa6).
=> Fix GitInfo generation when git executable not installed

sematic/ui/src/components/GitInfo.tsx
Fixes an extra floating border in the UI.
Before:
After:
=> Fix GitInfo UI rendering when there is not git info

sematic/examples/bazel/pipeline.py, sematic/examples/mnist/pytorch/pipeline.py
This marks existing top-level pipeline functions as inlined, because we recommend only leaf functions to be non-inlined, and any non-expensive functions which only return other Futures to be inlined.
=> Inline existing pipeline functions

sematic/versions.py
The minimum client version hasn't been updated to reflect the Retry feature breaking changes. This PR does that.
=> Bump minimum client version to 0.17.0

sematic/utils/git.py
If there are custom changes to the Bazel workspace that make the git repository unreachable on the ancestor path of the executed pipeline file path, the git information will not be retrievable.
This PR adds an attempt to source the Bazel workspace from the `BUILD_WORKSPACE_DIRECTORY` env variable if this is the case.
Manually introduced a test exception:
```
[...]
DEBUG:sematic.utils.git:Could not find source file for object '<function pipeline at 0x106d06ca0>'
File "/private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1fc5e/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/examples/add/add.runfiles/sematic/sematic/utils/git.py", line 28, in get_git_info
raise Exception("test")
Exception: test
DEBUG:sematic.utils.git:Trying …
```
=> Fix GitInfo for custom Bazel workspaces

sematic/resolvers/cloud_resolver.py, sematic/resolvers/silent_resolver.py, sematic/resolvers/state_machine_resolver.py, sematic/resolvers/tests/test_cloud_resolver.py
Introduces a new parameter in the `CloudResolver` init function which controls how many runs can be scheduled in parallel at any given point.
This is a continuation of the work started in #184.
This is done by maintaining an active runs counter and incrementing and decrementing it whenever a run is scheduled or processed as complete when communicating with the backend server. This was chosen over doing these operations in `_future_*` callbacks in order to keep the server as the source of truth and to avoid any possible inconsistent states due to unexpected state transitions.
Scheduling a run is now done only if the active runs would not exceed the configured value.
I tried spying the value of the counter in unit tests, but this proved to be challenging due to:
- spying the counter …
=> Capability to limit the parallelism degree of CloudResolver

sematic/types/types/list.py, sematic/types/types/tests/test_list.py
Currently we don't guarantee that any list elements will be shown if the elements are "large," with "large" meaning a threshold less than 1kB. This guarantees that no matter how large the elements are, we display at least one (assuming there is at least one element in the first place). It also increases the threshold for max elements displayed to be based on returning roughly 128kB of data for the list.
In addition to unit tests, I also ran this with a list of lots of dataclasses (10k of them) and confirmed the result didn't look too overwhelming.
=> At least one list element

docs/changelog.md, sematic/db/BUILD, sematic/db/migrations/20220930014400_migrate_exception_data.py, sematic/db/migrations/20221019225916_migrate_container_image_uris.py
Python migrations are part of a sequence of migration. Each migration is written at a particular moment in time and should work with the state of the database at that time. Depending on SQLAlchemy models in those migrations makes them rely on the latest code changes (e.g. DB columns) that were not yet available at the time of writing of the migration.
To solve this, Python migrations should not depend on any of the SQLAlchemy models.
=> Fix migrations to not depend on SQLAlchemy models

sematic/resolvers/cloud_resolver.py, sematic/resolvers/tests/BUILD, sematic/resolvers/tests/test_cloud_resolver.py
When running remotely, the resolver was trying to get the image mapping from the environment, which failed. We had already stuffed the mapping into the resolution, so we can get it from there instead.
Also updated test_cloud_resolver so it emulates a slightly more realistic cloud execution, where not every run is inline
Testing
--------
- In addition to the unit test, also tested on this branch with a [detached resolution](https://dev.sematic.cloud/pipelines/sematic.examples.bazel.pipeline.pipeline/8936259decd1475f8799be601a36e01f) and a [non-detatched resolution](https://dev.sematic.cloud/pipelines/sematic.examples.bazel.pipeline.pipeline/7822f54f91ae4898a246b446d06dc8e2)
- in both cases, had decorated one function (`add3`) to use a custom base image (with tag "cuda")
- in both cases, …
=> fix base images for detached mode

docs/deploy.md
People may not upgrade their bazel lib when they upgrade their pip dep, which can run into trouble when we change things about how bazel and the python code interact (ex: custom base images)
=> Update deploy.md to mention upgrading bazel

sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_kubernetes.py
There was a check for reading k8s status conditions that should have been looking for >=1, but was only >1.
=> fix latest condition off-by-one error

sematic/api/endpoints/resolutions.py, sematic/api/endpoints/tests/test_resolutions.py, sematic/api_client.py, sematic/examples/bazel/BUILD, sematic/resolvers/cloud_resolver.py, sematic/resolvers/state_machine_resolver.py, sematic/resolvers/tests/test_cloud_resolver.py, sematic/resolvers/worker.py, sematic/scheduling/job_scheduler.py, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_job_scheduler.py
The `max_parallelism` configuration wasn't passed to the detached `CloudResolver`, meaning detached execution ignored it.
This PR passes it through the worker command line interface.
Discovered by @augray on [this branch](https://github.com/sematic-ai/sematic/tree/augray/parallel-reproduce).
Validated on top of it as well.
Resolution link: https://dev.sematic.cloud/pipelines/sematic.examples.bazel.pipeline.pipeline/2fae07faef3c4b758ebf36c01c697b93
Snapshot of the above resolution graph showing the parameter is not ignored:
Resolver logs (with extra debugging lines which weren't added to the PR) showing the parameter is passed and taken into account:
```
tudor@[the-box]:~/sematic$ kubectl exec -i sematic-driver-2fae07faef3c4b758ebf36c01c697b93-fd3e8f-ljwn7 -- cat …
```
=> Fix max_parallelism for deached mode

sematic/__init__.py
`sematic.SilentResolver` not created in `sematic` package, this allows for direct usage
=> Allow for using sematic.SilentResolver without going into deep imports

sematic/db/models/factories.py, sematic/db/models/tests/test_factories.py, sematic/ui/src/components/Notes.tsx, sematic/ui/src/components/PipelinePanels.tsx, sematic/ui/src/components/RunPanel.tsx, sematic/ui/src/components/RunTabs.tsx, sematic/ui/src/components/SnackBarProvider.tsx
- Server: input edge clones were not getting attached to the artifacts
- UI: whole graph edges were passed to the `RunActionMenu`
- Fixes #279 
- Fixes long unbreakable notes being off screen
- Fixes selectedRun refresh when navigating to new resolution
=> Fix five bugs

sematic/db/migrations/20221019225916_migrate_container_image_uris.py
The `20221019225916_migrate_container_image_uris.py` had an invalid SQL statement.
This was not detected in our dev deployments because at the time when we ran it there we were still using SQLAlchemy models instead of raw SQL statements. This change was made after the migrations was initially rolled out.
=> Fix Python migration UPDATE SQL statement

sematic/calculator.py
Fixes a broken link and the function name in the exception that is raised when a function is declared with a variadic parameter.
=> Fix vararg error message broken link

sematic/types/registry.py, sematic/types/tests/test_registry.py
Closes #92
Prior to this PR, you could not use an Abstract Base Class (ABC) as a type annotation in a Sematic func. This PR adds that capability.
=> Support abstract base classes in type annotations

docs/future-algebra.md, sematic/calculator.py, sematic/resolvers/worker.py, sematic/tests/test_calculator.py, sematic/types/registry.py
Closes #86, #217
We already support this for lists:
```
@sematic.func
def pipeline() -> typing.List[int]:
return [foo(), bar()]
```
where `foo` and `bar` are Sematic funcs (thus returning futures). This PR makes it so we also support this:
```
@sematic.func
def pipeline() -> typing.Tuple[int]:
return (foo(), bar())
```
Additionally, the code above would fail for a remote execution if the funcs were not inline (see #217). This PR also fixes that bug.
Testing
-------
In addition to unit tests, I also executed some remote runs:
- [returning a list of futures](https://dev.sematic.cloud/pipelines/sematic.examples.bazel.pipeline.pipeline/061fdf4f4b4a4ed6951495cc794c27d3)
- [returning a tuple of futures](https://dev.sematic.cloud/pipelines/sematic.examples.bazel.pipeline.pipeline/da76ced2672f4611 …
=> Support automatic conversion of tuple-of-futures to future-tuple

sematic/calculator.py, sematic/tests/test_calculator.py, sematic/types/registry.py, sematic/types/tests/test_registry.py
Closes #47, #133
Prior to now, if you used `Any` as a type annotation for a Sematic func, you got a general "not a supported type" message. We have a recommendation to use `object` instead. This makes it so the error message instructs users to use this alternative explicitly. It also makes it so that invalid type annotations are caught earlier--as soon as a function is decorated with `@func`. Additionally, there were several types of functions which would fail when decorated with `@func`, but which failed in unexpected ways. For example: methods, generators, and co-routines. This PR adds checks that detect these usages and raise a helpful error message.
=> More & earlier validation when using @func

sematic/api/wsgi.py, sematic/calculator.py, sematic/tests/BUILD, sematic/tests/test_calculator.py, sematic/tests/test_client.py
Mypy errors started happening on `main` (without reproducing locally), causing all new PRs' builds to fail. This fixes the issues to unblock new PRs, pending an investigation regarding the discrepancy between Circleci and local mypy linters.
=> Fix mypy issues on main

.circleci/config.yml, requirements/ci-requirements.txt, sematic/versions.py
If users have a sqlite3 version less than 3.35.0, they won't be able to use Sematic, but the failure mode is just that the automatic db migrations fail. This makes a more clear error message that will show up when the`versions` module is loaded. Since `versions` is imported in `sematic/__init__`, this should mean that the first time the interpreter imports `sematic`, the sqlite version check should be performed.
Testing
-------
`bazel run //sematic/cli:main -- --help`, then the same with `MIN_SQLITE_VERSION` changed to `(3, 35, 0)` to force it to fail. Failure message:
```python
File "/private/var/tmp/_bazel_josh/2e6587ba58699c2ae305f4c72e05bdb6/execroot/sematic/bazel-out/darwin_arm64-fastbuild/bin/sematic/cli/main.runfiles/sematic/sematic/cli/main.py", …
```
=> Add sqlite version check

helm/sematic/Chart.yaml, helm/sematic/templates/sematic-server-role.yaml
We have recently added an API call to list pods for a job. We need the server's K8s SA to have permissions to do that. This adds such permissions to our helm chart. [Here's](https://github.com/sematic-ai/sematic/blob/main/sematic/scheduling/kubernetes.py#L340) where we use the permissions
=> Add list pods permissions to server SA

.bazelrc, developer-docs/tips-for-bazel.md
Loosens Bazel sandboxing rules during build, such that the missing dirs are ignored.
Added a tip for clearing the Bazel cache.
=> Fix test errors when ~/.semantic/data is missing during build

sematic/examples/liver_cirrhosis/requirements.txt, sematic/examples/mnist/pytorch/requirements.txt
I have updated the references for sklearn to scikit-learn. The only place we reference sklearn is in the `requirements.txt` for the mnist and the liver cirrhosis examples. I have verified that we are not using this reference in the `requirements.in` used for the installation of sematic.
=> Update sklearn to scikit-learn in requirements.txt of examples

sematic/db/migrations/20221004183943_remove_exception_from_runs.sql, sematic/versions.py
This removes the drop column operations from the up direction DB migrations in order to unblock users who are impacted by this issue: #302.
The check that sqlite3 has a minimum version of 3.35.0 is also relaxed to just warn instead of fail the starting of the server.
The effect is that users will be able to migrate to newer versions of Sematic on both their local and cloud deployments even if their Python installation did not come with sqlite3 >= 3.35.0, without requiring them to install a newer version from sources.
This is a temporary measure until the issue is resolved in a more sustainable way. The column that was previously removed will be kept in the DB until we address the issue.
Tested by starting the server without a database file, and by migrating down a database that contained …
=> Temporarily remove drop column from up migrations

.bazelrc, developer-docs/tips-for-bazel.md
`bazel test //sematic/...` did not work anymore on Macs. This fixes it and adds some useful debugging tips
=> Fix `bazel test //sematic/...` on Macs. Add some troubleshooting tips

sematic/resolvers/cloud_resolver.py, sematic/resolvers/local_resolver.py, sematic/resolvers/state_machine_resolver.py, sematic/tests/test_graph.py
It turns out it is possible that certain input edges have neither an `artifact_id` set nor a `source_run_id` set.
This is the case when the edge points to a value passed from outside the parent future. For example:
```python
@sematic.func
def pipeline(a: int) -> int:
f = foo()
b = bar(f, a)
return b
```
In this case, the edge for the `a` input to `bar` will have neither `artifact_id` nor `source_run_id` set until `bar` is ready to be scheduled. This prevents the graph from being cloned in the case where an upstream run fails (e.g. `foo`).
This PR fixes this issue by creating artifacts as soon as there is a concrete value for it, it does not wait for `bar` to be ready to get scheduled.
=> Streamlining handling of artifacts in `LocalResolver` in order to fix a re-run bug

sematic/cli/run.py
Fixes #337.
The `cli` CLI command parser extracted its own options from `sys.args` and passed the remainder to executed scripts only when running non-example pipelines. When an example pipeline wanted to parse arguments, it would also get `cli`'s intended arguments, when executed by `cli`.
This fixes the issue by treating example pipelines as any other script launched by `cli`.
=> Fix cli command arg passing

sematic/db/models/run.py, sematic/db/models/tests/test_run.py
Fixes issue in #310 
Adopted one solution in https://github.com/remarkjs/react-markdown/issues/273#issuecomment-683754992
=> #310 Fixes the multi-line docstring rendering.

docker/Dockerfile.server
Closes #289 
Currently if the DB migration fails for any reason, the DB is left in an intermediate state with the last successful migration step applied, and the version of the Server which expected all the migration steps to have succeeded is started anyway, creating a discrepancy between the Server code and the DB version.
The Server should not start at all if the DB is not up-to-date.
This PR makes it so that when migration fails, the server does not start.
Testing
-------
I started the server on the webbox using this code, and confirmed the migration still worked and the server still started. Then, I made migration intentionally fail and confirmed that the server did not start.
=> Make server not start if migration fails

sematic/abstract_calculator.py
Removes usages if the deprecated `@abc.abstractproperty` decorator from the codebase:
```python
class abstractproperty(property):
"""A decorator indicating abstract properties.
Deprecated, use 'property' with 'abstractmethod' instead:
class C(ABC):
@property
@abstractmethod
def my_abstract_property(self):
...
"""
```
=> Remove deprecated abstractproperty

.gitignore, BUILD, helm/sematic-server/Chart.yaml, sematic/tests/BUILD, sematic/tests/test_versions.py
Helm chart versions were moved to use the published chart version by default, which broke the build.  This fixes the reference to the new `appVersion` location.
=> Fix build checks for Helm chart

sematic/types/registry.py
For instance pydantic uses a custom metaclass intead of `ABCMeta` (see https://github.com/pydantic/pydantic/blob/1ac1199f08c42803dc7c5e6fae754afd53e3f1b4/pydantic/main.py#LL118C7-L118C16). This will add support for these cases.
=> Add support to subclasses of `ABCMeta`

docs/changelog.md, sematic/types/types/tests/BUILD, sematic/types/types/tests/test_dict.py, sematic/types/types/tests/test_union.py, sematic/types/types/union.py
Prior to this PR, `Union` had logic for serializing to json, but not for deserializing from it. How could this have ever worked, you ask? Because the serialization logic for `Union` just forwarded straight to the serialization logic for the underlying type, and then on deserialization the fallback generally fell back to something that "just worked" (either pickle or assuming the object was already json encodable). However, in some cases, this would fail. So I now added an actual deserialize-from-json function for `Union`. It stores information about which of the Unioned types the deserialization should ultimately use. Note that this does NOT change the json summary logic, so the UI is not impacted by this change.
=> Fix Union serdes

sematic/ui/src/hooks/pipelineHooks.ts
There was an issue that occurred during some prior code review process:
`calculatorPath` was suggested to rename to `pipelinePath`. But the function body wasn't modified by the refactoring tool. 
Unfortunately, this wasn't caught by CI either.
=> Fixed a issue caused by variable renaming.

developer-docs/README.md, helm/sematic-server/values.yaml
Updates the Release Docs to cover the recent changes to the Helm Charts.
Also updates an older image tag references, and some various improvements to the Release Docs wordings.
=> Update Release Docs for new Helm Charts

developer-docs/README.md, docs/changelog.md, helm/sematic-server/Chart.yaml, helm/sematic-server/values.yaml, sematic/versions.py, sematic/wheel_version.bzl
Includes the bumped versions and changelog from [the special 0.20.1 release](https://github.com/sematic-ai/sematic/releases/tag/v0.20.1), and creates a Special Release Procedure to describe this very process.
=> Bump versions for 0.20.1 and introduce a Special Release Procedure

docs/changelog.md, helm/sematic-server/Chart.yaml, helm/sematic-server/templates/configmap.yaml, helm/sematic-server/templates/serviceaccount.yaml, helm/sematic-server/values.yaml, sematic/config/server_settings.py, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_kubernetes.py
Closes #372 
Currently the server launches all workloads to use the `default` service account. We should add a new server configuration that allows you to launch jobs with a different SA.
- [Server settings definition](https://github.com/sematic-ai/sematic/blob/main/sematic/config/server_settings.py)
- [job launch](https://github.com/sematic-ai/sematic/blob/main/sematic/scheduling/kubernetes.py#L587)
Made changes to the helm chart to make this configurable. Also made some changes to the helm chart so I could deploy this to dev1 and test it.
Testing
-------
- Deployed to dev1 using:
```
helm upgrade sematic ./ --namespace=dev1 -f values.yaml --set image.repository=$IMAGE --set image.tag=$TAG --set namespace=dev1 --set auth.google_oauth_client_id=$GOOGLE_OAUTH_CLIENT_ID --set …
```
=> Enable configurable worker sa

sematic/ui/src/Home.tsx, sematic/ui/src/components/PipelineBar.tsx, sematic/ui/src/components/RunList.tsx, sematic/ui/src/hooks/httpHooks.ts, sematic/ui/src/hooks/pipelineHooks.ts, sematic/ui/src/pipelines/PipelineIndex.tsx, sematic/ui/src/pipelines/PipelineView.tsx
Key points of this PR
- The scope of the refactor lies only at certain critical pipeline-related scenarios. It should be sufficient to demonstrate how hooks can be used to satisfy different use cases.
- Refactors the callback-style procedures (`fetch_json`) to async/await style.
- Delegate state management to hooks, instead of manually initiating state change in the business logic layer.
- Leverage [`useAsyncFn`](https://github.com/streamich/react-use/blob/master/docs/useAsyncFn.md) in [`react-use`](https://github.com/streamich/react-use)
- Introduces a httpClient middleware (`useHttpClient`), which could be further refactored to add caching mechanism or to hook up with a 3rd party library. For now, it is only an abstraction and needs to be extracted first.
- The ultimate goal is to get …
=> Refactor the hook usage on pipeline related scenarios

docs/changelog.md, sematic/api/endpoints/runs.py, sematic/api/endpoints/tests/test_runs.py
Every time the server saves a run, it needs to broadcast the fact that the graph was updated. These two were missing leading to the DAG not refreshing in the UI.
Ideally we would have a centralized way of doing this (so that any call to `save_run` automatically broadcasts the update), but I don't want to add a dependency to socketio in the `queries` module as it would mix concerns.
Maybe we need an additional intermediate layer that takes care of persisting objects (calling `queries` functions) and broadcasting to socketio too.
=> [bugfix] Missing broadcasts upon server-side run save

sematic/resolvers/cloud_resolver.py
With `CloudResolver`, the server is responsible for starting k8s jobs, and also updating the run status to `SCHEDULED`.
Inline runs are not scheduled by the server, therefore the usual logic needs to be applied.
This bug lead to inline runs remaining in the `CREATED` state until completion. This would have been caught by #107.
=> [bugfix] Inline future status were not being updated by `CloudResolver` prior to executing

docs/SUMMARY.md, docs/advanced-apis.md, sematic/BUILD, sematic/__init__.py, sematic/future_context.py, sematic/resolvers/BUILD, sematic/resolvers/silent_resolver.py, sematic/resolvers/state_machine_resolver.py, sematic/resolvers/tests/BUILD, sematic/resolvers/tests/test_silent_resolver.py, sematic/resolvers/tests/test_worker.py, sematic/resolvers/worker.py, sematic/types/types/dataclass.py, sematic/types/types/tests/test_dataclass.py
#138
Introduces a new context object that can be used to obtain the ids of the active run/root run as well as the Resolver class. Example:
```python
import sematic
@sematic.func
def my_func() -> None:
print("Root id is: {}".format(sematic.context().root_id))
return None
```
This PR serves 3 purposes. The first two are related to the start of Spark work, the last is general.
1. In order to have behavior that differs based on which resolver is being used (ex: allocate local or remote spark cluster), we will need a context object like this
2. In order to allow the resolver logic to have a "hook" into how references to external resources (ex: a spark cluster) are registered, we will need such a context. Silent resolver can store references to these resources in memory, while the others store …
=> Enable Sematic context

sematic/BUILD, sematic/calculator.py, sematic/future.py, sematic/resolvers/cloud_resolver.py, sematic/resolvers/local_resolver.py, sematic/tests/BUILD, sematic/tests/test_future.py
Updates docstrings and validation code in locations that will be touched by implementation of the Function Output Artifact Caching feature (#338).
Extracted out as a separate PR in order to reduce the overall size of the PRs that will implement that feature.
Also updated the unit tests and added new test cases to completely cover the future properties validation.
=> Update Future docstrings and properties validation

sematic/examples/mnist/pytorch/BUILD, sematic/examples/mnist/pytorch/pipeline.py
The mnist example with GPUs doesn't work "out of the box" on any of Sematic's infra. This PR makes it so that it at least works with some old infra.
Testing
-------
Using the old infra:
- `bazel run //sematic/examples/mnist/pytorch:mnist_train -- --cuda` [run](https://dev.sematic.cloud/pipelines/sematic.examples.mnist.pytorch.pipeline.pipeline/a9f3e45b6b3049c78c7fddcf956c5646)
- `bazel run //sematic/examples/mnist/pytorch:mnist_learning_rates -- --cuda` [run](https://dev.sematic.cloud/pipelines/sematic.examples.mnist.pytorch.pipeline.scan_learning_rate/642e9ebc79b04ee1ae32703c4cd36746)
=> Make mnist work

sematic/resolvers/state_machine_resolver.py, sematic/resolvers/tests/test_local_resolver.py
In order to cleanly and safely clean up external resources whenever a run reaches a terminal state, we need some logic that executes any time a resource reaches a terminal state. This adds an appropriate callback that should execute when a future enters any of the terminal states.
=> Add terminal state callback

sematic/ui/src/components/Notes.tsx, sematic/ui/src/components/NotesPanel.tsx, sematic/ui/src/components/PipelineBar.tsx, sematic/ui/src/components/PipelinePanels.tsx, sematic/ui/src/hooks/pipelineHooks.ts, sematic/ui/src/pipelines/PipelineRunView.tsx
Description:
There is no need to have `changeRootRunId` passed down from `<PipelineRunView />,` through  `<PipelineBar />,` then through `<NotesPanel />,` into `<NoteView />` (or similarly, from `<PipelineRunView />` into `<PipelineBar>`). If `<NoteView />` wants to change the root run, the best way is to make URL navigation and render a new page fresh. This doesn't have much performance drain because if a node is not changed on the virtual DOM tree, it will persist and potentially not be re-rendered. In the meantime, the code flow logic could be simplified. 
This idea also works well with the future's comprehensive deep-linking implementation.
=> Gets rid of passing down `changeRootRunId`

docs/changelog.md, sematic/log_reader.py, sematic/resolvers/tests/test_local_resolver.py, sematic/tests/test_log_reader.py
Fixes a bug where you could get the following behavior:
- run is in progress, you scroll to the end
- you request more logs
- you get back more logs from the beginning
The issue was this:
- the code for constructing the cursor to be returned uses the place where it stopped searching
- if you requested more lines and there were 0 more available, there was no information available about where the code had stopped searching
The fix was to have the code return the same cursor position as it was supposed to start from if it didn't find any log lines (but might still find more later because the run is still running).
Testing
--------
- Added a unit test to emulate this case. Confirmed the test fails with the old code, and passes with the new.
- Tested using `bazel run …
=> Fix log continuation bug

sematic/ui/src/components/LogPanel.tsx, sematic/ui/src/components/ScrollingLogView.tsx, sematic/ui/src/hooks/httpHooks.ts, sematic/ui/src/hooks/logHooks.ts, sematic/ui/src/utils.tsx
Simplify the logs processing logic
- Now, we don't pass the logs retrieving function from `<LogPanel>` to `<ScrollingLogView>.` The logs retrieving logics are encapsulated in `logHooks.ts.`
- Callback style procedures are converted to async/await style. Code flows more naturally.
- The logics in `logHooks.ts` are much shorter now!
This should fix #354
=> Simplify logs processing logic #354

.circleci/config.yml
I did a bunch of cleanup on our Circle CI configuration, but the main motivation was to:
- remove coverage from happening on every PR commit
- enable executing a full build with coverage every night
- add retry to the coverage upload, which is flaky
In addition to these, I also:
- moved a bunch of stuff from steps directly in the job to being commands (which are more re-usable, and makes the overall steps in the job more clear)
- removed some comments and code that look to have been left over from very early attempts at CI setup
Triggering on a schedule is configured only via UI, and not via config file. I already set up [a trigger](https://app.circleci.com/settings/project/github/sematic-ai/sematic/triggers?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fsematic-ai%2Fsemat …
=> make coverage conditional

sematic/ui/src/components/Notes.tsx, sematic/ui/src/hooks/pipelineHooks.ts
Currently, the links on the notes are not evident enough to be seen as a link. 
This change makes the links more evident.
From 
To:
It used to display as plain text instead of the link because we implemented it that way. Now when we use `<link>,` it will behave more naturally like an HTML native link. We gain the benefit of showing visited states of the link.
=> Makes RunID links more explicit visually

helm/sematic-server/templates/configmap.yaml, sematic/scheduling/BUILD, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_kubernetes.py
There was a feature that would allow you to configure the workers to use a different URL to talk to the server than the end-users did. This is useful if your networking setup is such that user machines will hit some sort of proxy that can't be used in-cluster.
The old setting was left in as a server setting, and the docs still reference it. It just wasn't hooked up to anything. So this PR just goes the last mile to hook it back up--this time functioning fully server-side rather than relying on the configuration to be set by the users. Luckily, in-cluster, you can just use the k8s built-in DNS to refer to the API via its k8s service name. This means that for helm deployments, we can set this config automatically.
Testing
-------
Deployed this code to dev1 using the helm chart. Then for my …
=> Add back worker url override

sematic/api/endpoints/auth.py, sematic/api/endpoints/tests/test_auth.py
Closes #114
This PR enables `SEMATIC_AUTHORIZED_EMAIL_DOMAIN` to accept multiple comma-separated email domains.
=> Allow multi-domain auth

sematic/abstract_future.py, sematic/caching/BUILD, sematic/caching/__init__.py, sematic/caching/caching.py, sematic/caching/git.py, sematic/caching/tests/BUILD, sematic/caching/tests/test_caching.py, sematic/calculator.py, sematic/db/models/BUILD, sematic/db/models/factories.py, sematic/graph.py, sematic/resolvers/tests/test_local_resolver.py, sematic/tests/test_graph.py, sematic/utils/BUILD, sematic/utils/git.py, sematic/utils/hashing.py, sematic/utils/json.py, sematic/utils/tests/BUILD, sematic/utils/tests/test_hashing.py
This is the second in a series of PRs that will implement #338. The previous one is #390.
Introduces a module that can be used to generate the final cache key based on a user-specified cache namespace and on a Future func.
Currently uses SHA1 for the actual hashing, at it is [fast](https://automationrhapsody.com/md5-sha-1-sha-256-sha-512-speed-performance) and easy to use (see code comments), until a more efficient system can be implemented (see #403).
Also introduces a utility function that generates the cache key based on the git commit SHA, as it was requested by users.
The module is currently unused. Subsequent PRs will use this code.
Unit tests were introduced for the base cache key generation:
```bash
$ bazel test //sematic/caching/tests:test_caching
```
For the git-based utility …
=> Future cache key module

sematic/ui/src/components/LogPanel.tsx, sematic/ui/src/components/ScrollingLogView.tsx, sematic/ui/src/hooks/httpHooks.ts, sematic/ui/src/hooks/scrollingHooks.ts, sematic/ui/src/hooks/setTimeoutHooks.ts
Implements a `usePulldownTrigger`, which monitors whether a scroller container has scrolled to the bottom. If there are consecutive scrolling down events occur after that, a callback function will be triggered. This callback function fetches the next page of logs.
Here is a screencast of the work of this PR:
This is what happens in case of an server-side error:
=> Implements the pull down to trigger logs fetch function

sematic/ui/src/components/LogPanel.tsx, sematic/ui/src/components/RunPanel.tsx, sematic/ui/src/components/RunTabs.tsx, sematic/ui/src/components/ScrollingLogView.tsx, sematic/ui/src/hooks/httpHooks.ts, sematic/ui/src/hooks/scrollingHooks.ts, sematic/ui/src/hooks/setTimeoutHooks.ts
Restrict the width and height of the logs' area. The area's height is confined to the remaining space of the RunPanel minus the height of the header area.
=> Restrict the size of logs area

sematic/config/settings.py, sematic/config/tests/test_settings.py
Fixes:
```
sematic/sematic/config/user_settings.py", line 56, in <dictcomp>
return {var.value: value for var, value in active_user_settings.items()}
AttributeError: 'str' object has no attribute 'value'
```
=> [bugfix] Remove version from settings

sematic/ui/src/components/MenuPanel.tsx, sematic/ui/src/components/NotesPanel.tsx, sematic/ui/src/components/PipelineBar.tsx, sematic/ui/src/components/PipelinePanels.tsx, sematic/ui/src/components/ReactFlowDag.tsx, sematic/ui/src/components/RunPanel.tsx, sematic/ui/src/components/RunTree.tsx, sematic/ui/src/components/utils/typings.ts, sematic/ui/src/hooks/pipelineHooks.ts, sematic/ui/src/index.tsx, sematic/ui/src/pipelines/PipelinePanelsContext.tsx, sematic/ui/src/pipelines/PipelineRunView.tsx, sematic/ui/src/pipelines/PipelineRunViewContext.tsx, sematic/ui/src/pipelines/PipelineView.tsx
Elevate `rootRun`, `resolution`, and `selectedPanelItem` into supervisor contexts
Maintain the selected nested run ( `selectedRuns`) in a supervisor context. This is to pave the way to implement deep linking more easily.
What's next:
Due to the size of this PR, a follow-up PR will divide RunPanels into GraphPanel and RunDetailsPanel sections. So we have a dedicated component to deal with Graph manipulations.
Graph data derivative runsById data will also stay in a context.
=> [1/2] Reactors the state management of Pipeline scenarios

sematic/examples/testing_pipeline/BUILD
Adds a missing requirement to the `sematic_example` target of the testing pipeline.
=> Fix missing requirement for example testing pipeline

sematic/db/models/artifact.py, sematic/db/queries.py, sematic/db/tests/fixtures.py, sematic/db/tests/test_queries.py
Artifacts are addressed by content, with the ID being generated from the type and value themselves. When a Resolution generates an Artifact which has been seen before and which is present in the DB, this DB entry is completely overwritten.
The consequence given the current array of Artifact fields is that the `created_at` field is always updated to the latest Resolution time of any pipeline that produces it, meaning it can't be actually trusted.
This PR changes the behavior to only update the `updated_at` field when an Artifact is recreated, and to provide instructions via code comments to future developers regarding how to update the Artifact model.
Added 2 unit tests:
- validate creating a new Artifact
- validate updating an existing Artifact does not overwrite the `created_at` column. …
=> Avoid Artifact overwrite

sematic/config/settings.py, sematic/config/tests/BUILD, sematic/config/tests/test_settings.py, sematic/db/migrations/20221214142609_plugin_settings_file.py
The current mechanism for overriding settings at runtime with environment variables only overrides settings that are already defined in the settings file.
This PR fixes this along with a number of small bugs in the migration file.
Tested on dev1: https://dev1.dev-usw2-sematic0.sematic.cloud/pipelines/sematic.examples.add.pipeline.pipeline/d0a340b14e04483bbab8ccfedec51ad8
=> Fix env var override for settings

docs/changelog.md, sematic/BUILD
The code in `sematic.testing` was not getting built into the wheel, because the wheel only depends on certain select top-level modules and their transitive dependencies. This PR adds `sematic.testing` to that list.
Testing
--------
```
$ make wheel
$ virtualenv --python=$(which python3.8) ~/venvs/checktesting
$ source ~/venvs/checktesting/bin/activate
$ pip install ~/code/sematic/bazel-bin/sematic/sematic-0.21.1-py3-none-any.whl
$ cd ~/
$ python3 -c "from sematic.testing import mock_sematic_funcs; print(mock_sematic_funcs)"
<function mock_sematic_funcs at 0x1174d28b0>
```
=> Add testing code to wheel

sematic/caching/caching.py, sematic/caching/tests/BUILD, sematic/caching/tests/test_caching.py
The function that computes the cache key incorrectly uses the Future's initial input arguments with which it was instantiated, instead of the definitely resolved input arguments. This means that Futures which take as input arguments other Futures (instead of constants), will have their cache key computed based on non-deterministic Futures as values, resulting in non-deterministic cache keys as well.
This PR updates the function to use the resolved arguments and adds validation to only accept Futures whose arguments have been resolved.
A new unit test is added to verify the validation, and existing unit tests are updated with correct Future fixtures that have resolved input arguments.
```bash
$ bazel test sematic/caching/tests:test_caching
```
=> Compute cache key only for resolved args

sematic/ui/package-lock.json, sematic/ui/package.json, sematic/ui/src/hooks/pipelineHooks.ts, sematic/ui/src/pipelines/NotesPanel.tsx, sematic/ui/src/pipelines/PipelinePanels.tsx, sematic/ui/src/pipelines/PipelinePanelsContext.tsx, sematic/ui/src/pipelines/RunDetailsPanel.tsx, sematic/ui/src/pipelines/RunTree.tsx, sematic/ui/src/pipelines/graph/ReactFlowDag.tsx
Implements deep link thanks to the help of [Jotai](https://jotai.org/) library.
Deep link has a pattern of 
```
http://localhost:3000/pipelines/sematic.examples.add.pipeline.pipeline/46b01356e2864c4f917d1d9125288ee7#selRun=%2224da63e8353d4cd3b49e0dbf96f881a4%22
```
Here is a demo:
Some other maintenance work:
* Changed the API for reporting selected runs to `setSelectedRunId`, so we avoid client reporting with inconsistent runs. The real run instance will be given by the `PipelinePanelsContext`, so this keeps the references to the run instances as consistent as possible.  
Planned job in the near future:
1. Support "host:/pipelines/[pipelineName]/[nest_run_id]" style URL
2. Support deep links to run tabs and the selected artifact.
=> Implement deep link for selected runs

sematic/ui/src/pipelines/Artifacts.tsx, sematic/ui/src/pipelines/PipelinePanels.tsx, sematic/ui/src/pipelines/PipelinePanelsContext.tsx, sematic/ui/src/pipelines/RunTabs.tsx, sematic/ui/src/pipelines/RunTree.tsx, sematic/ui/src/pipelines/graph/ReactFlowDag.tsx
This PR addresses issue #331. I have added the code linking artifact nodes in the DAG to the run panel. 
Further, for input artifacts with no source run, I have added the ability to scroll down to the relevant artifact automatically.  
Only part missing in the PR, is to make the artifact green when it is selected which I will address in the future.
=> Add functionality to click artifacts in the DAG view

sematic/ui/src/pipelines/MenuPanel.tsx, sematic/ui/src/pipelines/PipelinePanels.tsx
There was a UI defect from the previous refactoring --- we used to show the loading indicator synced to the state of `isLoading`. The main content component is not shown when the loading indicator is shown. Hence caused the unmount of the main content component and screen flashings. 
Also, it is helpful to explain the mechanism of `useAsync` (`useAsyncRetry` is the same) 
```typescript
const {value, loading, error, retry} = useAsyncRetry(async () => { ... })
```
When the `loading` state is switched from false to true, the `value` state will remain at its old value until the async loading completes (when the `loading` value switches back to `false`). This also means the `value` will not turn to `null` during the loading. This allows us to reuse the old value during the async loading, and …
=> Avoids unnecessary unmount that causes screen flashing

sematic/ui/src/pipelines/PipelineRunView.tsx
Now the following style link is supported, 
> http://localhost:3000/pipelines/sematic.examples.add.pipeline.pipeline/2255b50841b46843ee8bea2dc43f1a2105
Even if `2255b50841b46843ee8bea2dc43f1a2105` is a nested run id.
=> Support link for nested run

sematic/ui/src/pipelines/PipelineRunView.tsx
Fixes an issue that switching runs from the dropdown box does not switch the pages.
The reason why it didn't work is that the run data is not updated in time when we make a judgement whether the current run is a nested run in :
https://github.com/sematic-ai/sematic/blob/7c8af36651f6ea437ef402978d3a2cb9f1511ec6/sematic/ui/src/pipelines/PipelineRunView.tsx#L65-L73
In other words, this issue can also be fixed by [507b53](https://github.com/sematic-ai/sematic/commit/507b53e0490b49ef4e42bbe718c2fe40314d6900)
But I don't choose that way because there will be more complexities to consider in the future if we don't unmount the component and still attempt to fix things up based on the existing component state. IMHO, unmounting and remounting the component fresh is worry-free and more robust in the …
=> [Bug] Fixes an issue that not being able to unmount a component causes unnecessary complexity in the downstream processing.

sematic/graph.py
This PR fixes issue #393 . I chose to hardcode the props for name and tags because https://github.com/sematic-ai/sematic/blob/main/sematic/db/models/factories.py#L30 erases the name and tags from the existing future. It seems like for normal runs `.set` is called after this which sets the props but it doesn't seem to be the case for rerun resolutions.
At least from my understanding, this is why this issue happens.
=> Add props to cloned future to fix rerun name

sematic/graph.py
Fixes a lint error on main.
This originally did not fail the PR checks because the PR had been opened from a fork, and Github does not allow webhooks to send events from forks, so there were no PR checks at all until after the PR was merged.
=> Fix lint error

docker/Dockerfile.ci
So we can run `node` and `npm` commands.
=> Install node ecosystem to CI image

developer-docs/README.md
Updates the release docs to explicitly call out when the client needs to be upgraded in the release itself. Improvements around this were requested by a client.
=> Explicitly call out client upgrade in the release docs

sematic/resolvers/log_streamer.py, sematic/resolvers/tests/test_log_streamer.py
We currently upload log files from workers every 10 seconds. If logs are only created sparsely, this can mean uploading a lot of empty log files. That means it can take a long time to accumulate enough log lines to fill a single request for N log lines. This PR makes it so that we don't upload to s3 when there are no actual log lines.
Testing
-------
Ran a [run](https://dev1.dev-usw2-sematic0.sematic.cloud/pipelines/sematic.examples.testing_pipeline.pipeline.testing_pipeline/88fd25c4b282478fbe3ddcfa880afb62) that had a pause for 50 seconds. Checked [s3](https://s3.console.aws.amazon.com/s3/buckets/sematic-dev?region=us-west-2&prefix=logs/v2/run_id/c68b13c09743490a80581fe924c830bc/worker/&showversions=false) to ensure it only had log files that were non-empty, and had no files for the …
=> Don't upload empty log files

sematic/types/types/tests/test_tuple.py, sematic/types/types/tuple.py
`Tuple` was delegating to element types for serialization, but (having no deserializer at all) was not delegating to element types for deserialization. This PR fixes that.
=> Add proper deserialization for tuple

.circleci/config.yml, sematic/ui/package.json
1. Lint command is added as `npm run` script, it reuses `--config node_modules/eslint-config-react-app/index.js` config, which is precisely the same one used by `react-scripts start`. So we keep the development experience and CI experience the same.
2. Any warnings will trigger the exit code of `eslint` as 1 (Error), so it will fail the CI run in case of any warning. 
3. We install npm packages using Circle CI Orb: `node/install-packages`. It is said this Ord [Install your Node packages with automated caching and best practices](https://circleci.com/developer/orbs/orb/circleci/node#commands-install-packages).
4. The lint errors will be fixed in a separate PR. (This PR cannot be merged before the lint errors are fixed, since it is guarded by the ESlint step now)
Please see example Circle …
=> Setup Circle CI run for ESLINT

docs/execution-modes.md, sematic/examples/testing_pipeline/__main__.py, sematic/examples/testing_pipeline/pipeline.py, sematic/resolvers/resource_requirements.py, sematic/resolvers/tests/test_resource_requirements.py, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_kubernetes.py
Fixes #430.
By default Docker uses a 64MB `/dev/shm` partition. This limits the performance of software which uses that partition for data processing.
This PR adds a new flag to `KubernetesResourceRequirements` that enables the mounting of an expanded memory-backed `/dev/shm` tmpfs file, that expands to 50% of available memory on the pod.
Further configuration of the memory limit is not done because in order to configure this for memory-backed files, the `SizeMemoryBackedVolumes` feature gate must be activated by the cluster admin - please see [this resource](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/).
Existing unit tests are updated with assertions.
The testing pipeline is enhanced with a function that allows the configuration of resource …
=> Ability to expand the shared memory on worker pods

sematic/db/migrate.py
Some `migrate` CLI commands have incorrect options added to them.
=> Remove incorrect options from migrate CLI commands

sematic/config/BUILD, sematic/config/config.py, sematic/versions.py
Currently we warn if the Sqlite3 version is outdated even if PostgreSQL would be used instead, which confuses users.
This logs the warning only when the Sqlite database is used:
```bash
~/work/sematic$ bazel run //sematic/api:server
INFO: Analyzed target //sematic/api:server (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //sematic/api:server up-to-date:
bazel-bin/sematic/api/server
INFO: Elapsed time: 0.359s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
Sematic will soon require the sqlite3 version to be at least 3.35.0, but your Python is using 3.7.17. Please upgrade. You may find this useful: https://stackoverflow.com/a/55729735/2540669
[...]
```
=> Warn about Sqlite3 version only when used

sematic/db/migrate.py
When dumping the DB schema to a relative file path, the file is actually created inside the Bazel runtime dir:
```bash
~/work/sematic$ bazel run //sematic/db:migrate -- dump --schema-file my_schema.sql
INFO: Analyzed target //sematic/db:migrate (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //sematic/db:migrate up-to-date:
bazel-bin/sematic/db/migrate
INFO: Elapsed time: 0.320s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
~/work/sematic$
~/work/sematic$ git st
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
~/work/sematic$
~/work/sematic$ find /private/var/tmp/_bazel_tudorscurtu/a689328a338e85f1cbb50b96a7f1 …
```
=> Fix schema dump relative file path usage

sematic/db/migrate.py
This reverts commit c29510f70840b8af9eccedd63d42d9dc1d7d3e1b, as it broke the build.
=> Revert "Remove incorrect options from migrate CLI commands (#456)"

sematic/ui/src/pipelines/NotesPanel.tsx
A bug has been discovered following the es lint refactoring in https://github.com/sematic-ai/sematic/pull/451.
Previously, we wrongly relied on missing dependencies in the `useEffect` dependency list as a feature. Adding the missing dependency causes a component to render in a loop. Now we remove `authorsByEmail` as a state that would trigger the re-rendering of the component and use reference(`useRef`) instead (which doesn't trigger re-rendering, but can still track the data).
=> Prevents getting infinite loops with useEffect()

sematic/ui/src/hooks/pipelineHooks.ts, sematic/ui/src/pipelines/PipelinePanels.tsx, sematic/ui/src/pipelines/RunTree.tsx, sematic/ui/src/utils.tsx
Supports deep links with the center panel tab selected.
The deep link now has a form of 
```
pipelines/sematic.examples.testing_pipeline.pipeline.testing_pipeline/5d6592fb50c84fbf83e59350325ff903#tab=input&run=7c32dcb60c2f4ac0b1c07cf18c69dddb
```
=> Deeplink for run tabs

sematic/cli/BUILD, sematic/cli/cli.py, sematic/cli/main.py, sematic/cli/migrate.py, sematic/db/migrations/20221214142609_plugin_settings_file.py, sematic/resolver.py
Release 0.21.1 corrupted settings files, adding serialized dataclasses tags to the yaml file.
This PR does the following things:
- Updates a settings file migration to catch corrupted files and fix them
- Adds a `migrate` command to the CLI. Is there a way to call this as a post-pip-install script?
- Moves automated migrations from the CLI to before anything else is imported. Some modules (e.g. `server`) import plugins which loads settings. This means settings must be migrated before anything else is imported.
=> [bugfix] Fix corrupted settings files from 0.21.1

sematic/api/endpoints/artifacts.py, sematic/api/endpoints/edges.py, sematic/api/endpoints/notes.py, sematic/api/endpoints/request_parameters.py, sematic/api/endpoints/runs.py, sematic/api/endpoints/tests/test_runs.py, sematic/api_client.py
Adds the ability to sort the results when fetching Sqlalchemy model instances from the server endpoint.
This is required by #414.
Extends the shared URL parameter extraction logic to also extract a parameter which specifies the ordering direction, and updates existing code to use that instead of hardcoded local ordering.
Also adds a client function which queries the `runs` server endpoint and uses the new functionality, which is also required by #414.
Added new unit tests which validate the ordering, and also added missing unit tests to cover the functionality of touched code.
=> Ability to order model results on backend endpoints

sematic/db/migrations/20221214142609_plugin_settings_file.py
The old fix for migrating from old settings files missed a case for in-yaml tags; this PR covers it.
=> More robust fix for old settings files

sematic/resolvers/BUILD, sematic/resolvers/worker.py
It can sometimes be helpful to determine what version of Sematic a particular pipeline was running with when looking in the logs. This PR adds that info. Also, to diagnose whether there were new pods created, or help with k8s debugging, it can be helpful to view the pod name. This PR also adds that to the logs.
Testing
-------
Executed testing pipeline. View logs [here](https://dev1.dev-usw2-sematic0.sematic.cloud/pipelines/sematic.examples.testing_pipeline.pipeline.testing_pipeline/982287fea62d49f09670e7673c4524e3#run=027010013add4641a0accecf80ecd3c9&tab=logs)
=> Add more log messages to worker.py

sematic/types/types/dataclass.py, sematic/types/types/tests/test_dataclass.py
Sometimes dataclasses change over time, and it would be helpful if values deserialized using an old version of a class could be deserialized using a new version of the class. One would think that if you add a new field to a dataclass, it should be able to deserialize something written when the class did *not* have that field--provided that the new class has a default value for the field. This is how protobuf compatibility works, for example. However, our code did not support this use case until this PR.
One place where these kind of incongruences can show up is between clients on an old version of Sematic and servers on a new version of Sematic. Clients and servers share some dataclasses, like resource requirements. This makes it safe to add new fields to dataclasses, provided that you …
=> Enable dataclass compatibility

sematic/config/settings.py, sematic/config/tests/BUILD, sematic/config/tests/fixtures.py, sematic/config/tests/test_server_settings.py, sematic/config/tests/test_settings.py, sematic/config/tests/test_user_settings.py
Currently, if the settings file is empty or missing, the Server and User plugins' settings are not loaded at all. The consequence is that env overrides for those plugins won't take effect.
This fixes the default profile settings to always include the Server and User plugins, and extends the unit tests.
Before:
```bash
~/work/sematic$ bazel run sematic/cli:main -- settings show
[...]
Active profile settings:
scopes: {}
settings:
sematic.config.server_settings.ServerSettings: {}
sematic.config.user_settings.UserSettings:
AWS_S3_BUCKET: my_bucket
SEMATIC_API_ADDRESS: my_server
SEMATIC_API_KEY: my_api_key
~/work/sematic$ AWS_S3_BUCKET=test_bucket_override bazel run sematic/cli:main -- settings show
Active profile settings:
scopes: {}
settings:
sematic.config.server_settings.ServerSettings: {} …
```
=> Provide default plugin settings

bazel/WORKSPACE
Bazel 6.0.0 gives the following error when running any Sematic target:
```bash
~/work/sematic$ bazel test sematic/api/...
ERROR: Failed to load .bzl file '//bazel:pipeline.bzl': possible dependency cycle detected.
ERROR: Error computing the main repository mapping: cycles detected during computation of main repo mapping
```
This seems to be caused by the inclusion in the `WORKSPACE` file of a Bazel file this resides inside a nested `WORKSPACE`. The error message itself seems to be incorrect, as a cycle is not actually present. Changing the name of the nested `WORKSPACE` or commenting out the entirety of the imported `pipeline.bzl` file incorrectly yields the same error, which would suggest that this is a regression in the Bazel release.
None of the [Bazel 6.0.0 release …
=> Add support for Bazel 6.0.0

sematic/ui/src/pipelines/OutputPanel.tsx
Show a link pointing to logs tab in case the run failed, and no output is yielded.
Implementation-wise, it is implemented as a native HTML link instead of JS navigation functions. So we take advantage of copying/pasting, travel state, "open in new tabs" etc.
=> Add a link in output panel pointing to logs panel in case of error

sematic/ui/src/Home.tsx, sematic/ui/src/components/CopyButton.tsx, sematic/ui/src/components/Notes.tsx, sematic/ui/src/components/RunId.tsx, sematic/ui/src/components/RunStateChip.tsx, sematic/ui/src/pipelines/PipelineBar.tsx, sematic/ui/src/pipelines/PipelineIndex.tsx, sematic/ui/src/pipelines/RunDetailsPanel.tsx, sematic/ui/src/pipelines/RunTree.tsx, sematic/ui/src/pipelines/graph/RunNode.tsx, sematic/ui/src/runs/RunIndex.tsx
- On the run details page, render full run ID with copy button + original run ID shortened into six characters with deep-link. 
- Updated State chip and changes it to a hollow green circle for cloned runs. The label will be changed to `cloned` instead of `success`. The update should reflect on the DAG view and the run tree.
- Refactored the interface of `<RunStateChip />`.
Update: the visual style for the header part is updated to the following style:
(Screencast above is not re-recorded)
=> Show cloned run state

sematic/api_client.py
With the new way of writing data to S3, we aren't using the boto lib anymore for the actual write. This means that we are no longer doing the retries it did. This adds retries to our own write logic.
=> Add retry for data 'put'

sematic/examples/testing_pipeline/__main__.py, sematic/examples/testing_pipeline/pipeline.py, sematic/future_operators/getitem.py, sematic/ui/src/constants.ts
Fixes #494.
When re-running a pipeline that included `_getitem`, during the cloning process the func would be imported. As `_getitem` is declared inside another plain Python function, it is not available for import.
This does not reproduce for `_make_list` or for `_make_tuple` because their enclosing functions have the same respective names. `_getitem` is declared inside a function called `__getitem__`, which is then set as the homonymous utility function on the `Future` class.
This PR introduces a `_getitem` function which wraps `__getitem__`, which can be imported in its stead.
The testing pipeline is also updated to provide the ability to explicitly include the `_make_list`, `_make_tuple`, and `_getitem` virtual funcs.
Also, `_getitem` is added to the list of "hidden" funcs in the …
=> Make _getitem importable on graph cloning

sematic/ui/src/pipelines/ScrollingLogView.tsx
This PR dismisses the full page loading indicator when the component is unloaded. So we leave no lingering loading indicator after switching tabs.
=> Dismiss loading indicator

sematic/api/endpoints/runs.py, sematic/api/endpoints/tests/test_runs.py, sematic/db/queries.py, sematic/db/tests/test_queries.py
Support an API like the one below, which enumerates the external resources associated with a run
http://127.0.0.1:5001/api/v1/runs/df97c16293e6453485895811319ee643/external_resources
=> Endpoint for external resources used by a run

sematic/ui/src/hooks/logHooks.ts
This PR changes logs polling interval to 5 seconds. So we relive the server from constantly getting polled.
=> Change logs polling interval

.circleci/config.yml
Code coverage is failing on main due to a connection error pushing the coverage info to codecov. We don't really leverage this info anyway, so this PR disables coverage from CI.
=> disable publishing coverage

docs/changelog.md, sematic/ui/src/hooks/graphHooks.ts, sematic/ui/src/utils.tsx
This is a second attempt to fix the issue mentioned in https://github.com/sematic-ai/sematic/pull/440
The WebSocket packets to update the graph are emitted at random moments. If the client receives a packet when there is an ongoing request to get the updated graph payload, a successive such request will be discarded due to the logic in  [useAsyncRetry](https://github.com/streamich/react-use/blob/325f5bd69904346788ea981ec18bfc7397c611df/src/useAsyncRetry.ts#L13
), when we see the log message `You are calling useAsyncRetry hook retry() method while loading in progress, this is a no-op.' `, it is an indication of such mechanism underplay. 
In the previous PR, I attempted to wait for the async loading using a promise. That part succeeded. However, following the promise resolution, the loading …
=> Fixes a race condition issue

WORKSPACE
The current version 1.10.23 suddenly has a mismatched checksum. This issue fails CI run constantly.
We can decide whether to take this change in the reviews.
=> Upgrade aspect_bazel_lib to 1.23.3

sematic/ui/src/Models.tsx, sematic/ui/src/hooks/externalResourceHooks.ts, sematic/ui/src/hooks/httpHooks.ts, sematic/ui/src/hooks/runDetailsHooks.ts, sematic/ui/src/pipelines/DocumentationPanel.tsx, sematic/ui/src/pipelines/RunTabs.tsx, sematic/ui/src/pipelines/ScrollingLogView.tsx, sematic/ui/src/pipelines/external_resource/ExternalResource.tsx, sematic/ui/src/pipelines/external_resource/ExternalResourceState.tsx
This PR works to display the external resources tab. 
Currently, after the tab is switched to, the code will constantly poll the server with an interval of 1 second until it sees the external resource with `DEACTIVATED` state. Navigating away from the external resources tab will cancel polling.
Despite the server returning a list of resources, we assume the server will return a list of 1. 
Update:
After suggestions from code review, it now looks like this:
=> Implements UI for external resource

.circleci/config.yml
Parallelizing CI runs by dividing the workflow into several jobs.
This is to pave the way for the works of integration test later.
In the implementation, I adopted workspace storage (persist_to_workspace + attach_workspace) to preserve the work of `pip install` and code checkout. So the successive jobs can directly use the result when run in parallel.
Example: https://app.circleci.com/pipelines/github/sematic-ai/sematic/2078/workflows/0b83172b-0aa5-46d1-aea5-24534bdc8e4d
=> Parallelizing CI run

helm/sematic-server/values.yaml
If the tag is commented out, the image tag specified in `Chart.yaml` is used instead, which is the correct result.
=> Don't specify an image tag by default in Helm chart

sematic/types/types/dataclass.py, sematic/types/types/dict.py, sematic/types/types/tests/test_dataclass.py
Prior to this PR, instead of getting a casting error, there was an exception raised when the tuple unpacking failed. This made it hard to identify where in a dataclass a bad dict annotation was coming from. This makes it more clear.
=> Make untyped dict error message is clearer, ensure propagation in dataclasses

sematic/resolvers/log_streamer.py, sematic/resolvers/tests/test_log_streamer.py, sematic/utils/BUILD, sematic/utils/stdout.py
Addresses #459 
Prior to this PR, we ingested logs to Sematic for display in the UI--but at the cost of the logs not being available on the pod's original stdout/stderr. This has the downside that if people are using other logging systems, and want job logs available there, they can't access them. This PR changes this so that we push logs *both* to Sematic *and* to the original stdout. This effectively emulates the behavior of ["tee"](https://linuxize.com/post/linux-tee-command/). Why not use *actual* `tee`?
1. We want to support people bringing their own base images, and not all will have `tee` (ex: slim base images like alpine)
2. Currently the worker image is created by using bazel [`py3_image`](https://github.com/bazelbuild/rules_docker/blob/4c1eaabcb6f52500373cf550e11982463d37a7a4/REA …
=> "Tee" logs to pod stdout as well as Sematic ingestion

sematic/abstract_future.py, sematic/api/endpoints/BUILD, sematic/api/endpoints/resolutions.py, sematic/api/endpoints/runs.py, sematic/api/endpoints/tests/test_resolutions.py, sematic/db/models/resolution.py, sematic/resolvers/cloud_resolver.py, sematic/resolvers/local_resolver.py, sematic/resolvers/tests/test_cloud_resolver.py, sematic/resolvers/tests/test_local_resolver.py, sematic/scheduling/kubernetes.py
Addresses #518, #417
Make some improvements to the way run/resolution cleanup is performed. In particular:
- Make it so that when one run fails and others are running/pending, it is clear which have failed and which were just canceled
- Make it so when the resolver restarts, all runs are stopped (instead of left running). We also add an appropriate error visible in the UI when this occurs.
The first of these is achieved simply by changing the existing logic that marks remaining runs as "failed" to mark them as "canceled" instead. The latter is achieved by adjusting the logic such that when a resolution reaches a terminal state, we always cancel any remaining associated runs on the server side. This works because when a resolver pod restarted, we were already failing the resolution. The …
=> Improve run/resolution cleanup (clearer root cause, resolver restarts)

sematic/resolvers/tests/BUILD, sematic/resolvers/tests/test_local_resolver.py, sematic/tests/fixtures.py, sematic/types/types/dict.py
This is the fourth in a series of PRs that implement #338. The previous one is #414.
This introduces unit tests that validate the integration between the Resolver and the output caching module. Unit tests for the caching module had already existed.
```bash
$ bazel test --test_output=all sematic/resolvers/tests:test_local_resolver
```
=> Function output caching unit tests

sematic/__init__.py
Fixes #539.
This updates the Server initialization code to set an env variable only when running on MacOS to deactivate `urllib` from making an OS framework call that will kill the `gunicorn` WSGI worker. For mode details, please see the code comment, and [this Python issue](https://bugs.python.org/issue33725).
The consequence is that in local MacOS laptop deployments `urllib` calls (currently used for the Cancelation and Slack notification features) will not use system-level proxies.
- Setting the env variable mentioned in #539 can only be done outside the Sematic code / scripts, and deactivates a system behavior, which is not desired, and which might go away with any future OS release.
- The `gunicorn` version used is already the latest.
- Switching the `multiprocessing` forking …
=> Avoid urllib usage killing WSGI workers on MacOS

sematic/api/endpoints/resolutions.py, sematic/api/endpoints/tests/test_resolutions.py
Fixes a behavior when the Resolver is left hanging and the Resolution incorrectly marked as failed if a cancelation event is emitted more than once.
This can happen either if the user (or a runtime environment) sends a cancelation signal, but I've also seen this happen sporadically where both the Resolver and the Dashboard both emit the cancelation event (possibly due to an apparent race condition in the socket.io broadcasting).
The below tests were executed by running the testing pipeline, and sending 2 / multiple interrupts from the console while the sleep func was executing. The fact that the sleep func itself was not canceled is a separate, missing feature.
**Resolver logs:**
```
~/work/sematic$ bazel run sematic/examples/testing_pipeline -- --sleep 10
[...] …
```
=> Fix client hanging after multiple cancelation events

sematic/db/migrate.py, sematic/db/migrations/20221214142609_plugin_settings_file.py
Currently when a Python migration fails, the exception is swallowed and a revert is immediately executed, creating a bad experience.
This updates the migration logic to also inform the user what the original exception was.
Also, an existing migration script is edited to permit accepting the new version of the settings file and completing successfully, instead of only accepting the previous version that had to be migrated away from.
=> Warn on Python migration error

developer-docs/README.md, docs/changelog.md, helm/sematic-server/Chart.yaml, helm/sematic-server/values.yaml, sematic/versions.py, sematic/wheel_constants.bzl
Release Sematic v0.24.0
Testing
--------
- Tested that installing the wheel without any "extras" does not install any ee features or Ray. Tested that installing with `[all]` did.
- Deployed the `ee` server and tested the current testing pipeline code against it: (a) changed values file to allow ray usage, then: `bazel run //sematic/examples/testing_pipeline:__main__ -- --cloud --detach --ray-resource` (b) `bazel run //sematic/examples/testing_pipeline:__main__ -- --cloud --detach --sleep 300` and watched pod logs in the UI and from Grafana to guarantee they were there (c) `bazel run //sematic/examples/testing_pipeline:__main__ -- --cloud --detach --sleep 300 --oom` confirmed that the OOM run was marked as failed, and others were failed up to the root. But sibling and later runs were …
=> Release Sematic v0.24.0

.circleci/config.yml
This removes an unnecessary setting from the Circleci configuration file. The Slack notification still works:
=> Simplify the Circleci Slack notification configuration

sematic/tests/integration/test_pip_install.sh, tools/sematic_wheel_rule.bzl
A regression in our wheel building macro patch made it so we were stuffing a bunch of irrelevant third party dep files into the wheel. This resolves the regression, and improves our basic sanity testing of the wheel to include wheel size.
=> Make wheel slimmer

helm/sematic-server/templates/configmap.yaml
On configuration of the Slack publishing plugin, it is not actually activated in the `PUBLISH` scope.
=> Fix Slack publishing Helm activation

.gitignore, sematic/api/endpoints/runs.py, sematic/api/endpoints/tests/test_runs.py, sematic/ui/src/components/RunList.tsx, sematic/ui/src/components/SideBar.tsx, sematic/ui/src/hooks/domHooks.ts, sematic/ui/src/index.tsx, sematic/ui/src/pipelines/PipelineIndex.tsx, sematic/ui/src/runs/RunIndex.tsx, sematic/ui/src/utils.tsx
This is a work based on PR of https://github.com/sematic-ai/sematic/pull/482
Since that branch is not rebased, the remaining work continues on this branch.
Support full-text search for the `name, calculator_path, description, source_code, id, tags` fields. There is a new page(UI) for searching runs. 
Closes #546
=> Full-text run search

sematic/ui/src/pipelines/PipelineIndex.tsx
Unify the layout experience of the runs page and pipeline list page. So the header and footer of the table are sticky, and only the data rows portion is scrollable.
Before:
After:
=> Refactor pipeline page layout

sematic/config/settings.py, sematic/config/tests/BUILD, sematic/config/tests/test_settings.py
Fixes a bug where in a collocated local deployment of both Server and pipeline submission, the submission of the pipeline itself fails with an import error if the local settings file configures a plugin that is Server-only.
This is because the pipeline submission binary is built without the Server plugins.
The plugin import error is gracefully handled already in [this section of the code](https://github.com/sematic-ai/sematic/blob/8cde601767ae3be60685da728b3acd8a4dc6583e/sematic/config/settings.py#L363-L372), which removes the unknown settings and logs a warning.
However, afterwards, [the settings are re-added](https://github.com/sematic-ai/sematic/blob/8cde601767ae3be60685da728b3acd8a4dc6583e/sematic/config/settings.py#L131) based on the corresponding declaration of the plugin in the …
=> Fix Resolver import error on Server plugin

docs/ray.md
This was a footnote, but the footnote got removed at some point. I thought it would be good to call it out more explicitly
=> Add notice that Ray is an EE feature

sematic/examples/mnist/pytorch/README.md, sematic/examples/mnist/pytorch/pipeline.py
Our cluster requires a toleration to be able to use GPU-enabled nodes. This PR adds that toleration for Mnist training. Sample [run](https://dev1.dev-usw2-sematic0.sematic.cloud/pipelines/sematic.examples.mnist.pytorch.pipeline.pipeline/175fd51d6d8346aab736037c92a1131a#tab=input)
=> Add k8s toleration to allow Mnist train on our K8s setup

helm/sematic-server/Chart.yaml
A release for the Helm charts only, in order to ship bug fixes to the charts.
=> Release Helm charts v1.1.2 with Sematic v0.24.1

.circleci/config.yml, sematic/api/endpoints/runs.py
Currently the lint step that CI performs lacks some operations that are present in the `make pre-commit` target developers use to lint the code before pushing changes.
This updates the CI linter to perform the exact same steps as Developers do.
=> Update CI lint step to match dev linting

docs/ray.md, sematic/ee/plugins/external_resource/ray/cluster.py, sematic/ee/plugins/external_resource/ray/tests/test_cluster.py, sematic/plugins/abstract_external_resource.py, sematic/resolvers/state_machine_resolver.py, sematic/resolvers/tests/fixtures.py, sematic/resolvers/tests/test_silent_resolver.py
Addresses #565
Allow the the timeouts for resource activation/deactivation to be configurable on a per-resource basis. Some resource activations may take longer than others. Ex: a big ray cluster takes longer to configure than a small one. Also, large base images take longer to start workers for than small base images. Resources should be able to configure appropriate timeouts for themselves rather than using a universal fixed default.
=> Use configurable timeouts

sematic/ui/package-lock.json, sematic/ui/package.json, sematic/ui/src/components/RunId.tsx, sematic/ui/src/hooks/pipelineHooks.ts, sematic/ui/src/index.tsx, sematic/ui/src/pipelines/OutputPanel.tsx, sematic/ui/src/pipelines/PipelineBar.tsx, sematic/ui/src/pipelines/PipelineRunView.tsx, sematic/ui/src/pipelines/PipelineRunViewContext.ts, sematic/ui/src/pipelines/PipelineView.tsx, sematic/ui/src/runs/RunIndex.tsx
Now we support a URL of the following form in the URL
```
http://localhost:3000/runs/953c084342014b0e89fe389d8fa2e75d
```
The current URL pattern `http://host/pipelines/:pipeline_path/:rootId` redirects to `http://host/runs/:rootId`
=> Supports runs link

sematic/types/types/pytorch/__init__.py
Closes #572
We can try to import `torch` near the top of resolver jobs when we try to import type deserialization logic. The existing code is resilient against "normal" `ImportError`, but not against more complicated import failures like the following:
```python
File "/pip_deps_torch/site-packages/torch/__init__.py", line 172, in _load_global_deps
ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
File "/python_x86_64-unknown-linux-gnu/lib/python3.9/ctypes/__init__.py", line 374, in __init__
self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.11: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
File "/rules_sematic/worker.py", line 8, in …
```
=> Resilient against non-standard torch import fails

bazel/pipeline.bzl, sematic/examples/testing_pipeline/BUILD
The default behavior for [`py3_image`](https://github.com/bazelbuild/rules_docker#py3_image), which Sematic uses to build docker images from bazel, is to gzip all the bazel dependencies into one zip. It then puts this zip as a new layer in the image. This is problematic because any change to any code invalidates the bazel and docker caches for the whole zip and layer. `py3_image` provides a `layers` parameter which allows you to break up the monolithic zip and layers into individual ones. This can make it much faster to iterate on code that needs to be built & pushed. This PR exposes this parameter in the `sematic_pipeline` macro.
Testing
-------
```
sematic-dev $ bazel run //sematic/examples/testing_pipeline:__main__ -- --cloud --ray-resource --detach
sematic-dev $ bazel run …
```
=> Add ability to use image layers for Sematic pipelines

sematic/db/migrate.py, sematic/db/tests/test_migrate.py
On PostgreSQL, SQL migration scripts that contain commented-out statements fail:
```
INFO:root:Applying 20221004183943_remove_exception_from_runs.sql
ERROR:root:20221004183943_remove_exception_from_runs.sql failed with error:
(psycopg2.ProgrammingError) can't execute an empty query
[SQL: -- TODO #302: implement sustainable way to upgrade sqlite3 DBs
-- ALTER TABLE runs DROP COLUMN exception;]
(Background on this error at: https://sqlalche.me/e/14/f405)
Last successful migration is: 20220930014400_migrate_exception_data.py
```
This update eliminates comments from the parsed SQL migration statements, and introduces a unit test to validate the logic. The unit test was falsified by failing the un-patched version.
=> Fix noop SQL migrations

docs/changelog.md, docs/ray.md, docs/upgrades.md, sematic/ee/LICENSE, sematic/ee/README.md, sematic/ui/src/Home.tsx
We have a lot of places where we tell people to reach out, but point them either to Discord or Emmanuel's email. Now that we're using support@sematic.dev , it's better to point them there.
=> Reference new support email

sematic/ui/src/Home.tsx, sematic/ui/src/components/MuiRouterLink.tsx, sematic/ui/src/components/RunId.tsx, sematic/ui/src/components/SideBar.tsx, sematic/ui/src/pipelines/PipelineBar.tsx, sematic/ui/src/pipelines/PipelineIndex.tsx, sematic/ui/src/runs/RunIndex.tsx
Instead of using the default `<Link>` component from MUI for in-app links, change them to use Links from `react-router`, so when these links are clicked, there will be no full page reload. 
The component is implemented as a composition of the `<Link>` component from `MUI` and the one from  `react-router`. So the MUI styles will still apply. 
If interested, here is how React-router's `<Link>` changes the browser URL without reloading the page
https://github.com/remix-run/react-router/blob/2b843a6739c6807e683de9097e20909e78f0a1bd/packages/react-router-dom/index.tsx#L446-L473
=> Refactor in-app links to use react router

.circleci/config.yml, sematic/ui/package-lock.json, sematic/ui/package.json, sematic/ui/src/Home.tsx, sematic/ui/src/Payloads.tsx, sematic/ui/src/components/TrackingNotice.tsx, sematic/ui/src/index.tsx, sematic/ui/src/postHogManager.ts, sematic/ui/src/runs/RunIndex.tsx, sematic/ui/src/utils.tsx
1. Tracks open load events by leveraging the PostHog platform.
2. Provide a UI for the user to opt out of event capturing.
3. The implementation also respects the settings of `globalPrivacyControl` if a user has not explicitly set the output config yet. 
Testing: manually set `globalPrivacyControl` and saw the localStorage value overrides that. Also saw `globalPrivacyControl` takes effect if localStorage is empty.
Closes #591
=> Integrate PostHog event capturing

.flake8, helm/sematic-server/templates/NOTES.txt, helm/sematic-server/templates/_helpers.tpl, helm/sematic-server/templates/migration-job.yaml, helm/sematic-server/values.yaml, sematic/cli/BUILD, sematic/cli/cli.py, sematic/cli/main.py
Resolve #588.
* Runs the migration as a separate container before starting api/socket servers.
* Does not start the servers if migration failed.
* Keeps the migration pod around in a Completed state until the next deploy so logs are accessible.
* Configured a logger explicitly since the CLI call doesn't.
* Cleaned up the Helm install notes a bit.
=> Atomic database migrations with Helm hooks

helm/sematic-server/templates/migration-job.yaml, sematic/db/migrate.py
- failed migrations now reraise their exceptions all the way out
- migration job container now has access to the db url secret
- migration job now runs from the interpreter rather than cli, mirroring how the api server runs in docker
=> Actually fail migrations and don't force local

docs/api.md, sematic/resolvers/cloud_resolver.py, sematic/resolvers/local_resolver.py
The rerun documentation was mentioning in a few places that the rerun-from-here run was not rerun itself, [which is incorrect](https://github.com/sematic-ai/sematic/blob/3a5bfeee684e7ccbc62f50ed3f247ceb69a4f6c0/sematic/graph.py#L366).
Updated the documentation and code comments in question.
=> Correct rerun documentation

sematic/ui/package-lock.json, sematic/ui/package.json, sematic/ui/src/components/tests/test_RunStateChip.cy.tsx, sematic/ui/src/hooks/graphHooks.ts, sematic/ui/src/hooks/tests/test_graphHooks.cy.tsx, sematic/ui/tests/fixtures/run.ts, sematic/ui/tests/package.json, sematic/ui/tests/support/utils.ts, sematic/ui/tsconfig.json
Sort the nested runs under the same parent run by their `created_at` field.
Added unit test for the sorting logic.
This is a fix to a regression issue.
before 
after:
which matches the DAG more closely.
=> Sort run tree nodes

sematic/ui/src/index.tsx
Remove the hash portion from URL in telemetry reporting
=> Remove hash from URL in telemetry

sematic/ui/src/pipelines/PipelineBar.tsx, sematic/ui/src/tests/test_utils.cy.ts, sematic/ui/src/utils.tsx, sematic/ui/tests/fixtures/user.ts
The run details page now shows the information of the user who launched the pipeline.
Closes #617
=> Add run owner info on the run details page

sematic/api/endpoints/resolutions.py
Some users would like to be able to use their monitoring infra to create dashboards around various pipelines. A simple way for us to enable this for them is to add a log message that contains the relevant info about a pipeline's terminal state. Any users who rely on this should do so at their own risk: this is not a public API and is subject to change at any time. However, it can be useful if people are willing to accept that it may change/disappear.
Testing
--------
Deployed and ran a couple pipelines; one of which was known to fail:
Sample messages:
```
2023-03-02 18:53:53,050 [INFO] sematic.api.endpoints.resolutions: Remote resolution df55c4cccf5c4573b8812ca882deef00 for pipeline sematic.examples.testing_pipeline.pipeline.testing_pipeline terminated with root run in state …
```
=> Log message to be used for pipeline stats

sematic/ui/src/hooks/pipelineHooks.ts, sematic/ui/src/pipelines/NotesPanel.tsx, sematic/ui/src/pipelines/PipelinePanels.tsx, sematic/ui/src/pipelines/RunPanel.tsx
Besides adding support for deep linking selected panels, I also fixed a bug that prevented the browser back-forward buttons from working correctly.
The experience is deployed to https://chance.dev-usw2-sematic0.sematic.cloud/ to try out.
=> Support deep linking to selected panels on the run details page

sematic/ui/src/pipelines/PipelinePanels.tsx
Explain: `selectedPanelItemHash` is initially empty and caused the logic to believe it is not on the `run` panel. Hence removes the `run` and `tab` hashes from the URL. 
Using `selectedPanelItem` is safer because if `selectedPanelItemHash` is null, `selectedPanelItem`, as a proxy, will default to `run`.
=> Fixes a bug that removes the selected tab when the page is first loaded

bazel/pipeline.bzl
The "manual" tag was not being added to all image-related targets in `sematic_pipeline`. This adds that tag.
Testing
-------
```
bazel build //sematic/examples/add/... --subcommands -s --explain=tmp.txt --verbose_explanations
```
Did this before and after the change. Cleared the bazel cache between executions.
Before:
```
Build options: --subcommands=1 --subcommands=1 --explain=before.txt --verbose_explanations
Executing action 'BazelWorkspaceStatusAction stable-status.txt': unconditional execution is requested.
Executing action 'Creating source manifest for //sematic/examples/add:__main__': no entry in the cache (action is new).
Executing action 'Creating source manifest for //sematic/examples/add:add': no entry in the cache (action is new).
Executing action 'Creating source manifest for …
```
=> Add manual tag to other image targets

Makefile, sematic/ui/src/pipelines/RunTree.tsx
Fixed a UI issue that runs status updates is not reflected on the run tree.
Improve the make file to auto-run `npm install` during the `make ui` rule. `npm install`  will be skipped if `node_modules` already exists or `package.json` is not updated.
=> UI Bug fix + makefile improvement

sematic/ui/src/hooks/appHooks.ts, sematic/ui/src/hooks/externalResourceHooks.ts, sematic/ui/src/hooks/graphHooks.ts, sematic/ui/src/hooks/httpHooks.ts, sematic/ui/src/hooks/logHooks.ts, sematic/ui/src/hooks/pipelineHooks.ts, sematic/ui/src/login.tsx
So now `useHttpClient` returns the raw HTTP responses instead of converting them to JSON. It should be up to the caller to decide in what format it wants to consume the response (there are cases when it does not have to be JSON).
=> Refactor the interface of useHttpClient

sematic/abstract_future.py, sematic/api/endpoints/runs.py, sematic/api/endpoints/tests/test_notes.py, sematic/api/endpoints/tests/test_resolutions.py, sematic/api/endpoints/tests/test_runs.py, sematic/cli/tests/BUILD, sematic/cli/tests/test_cancel.py, sematic/cli/tests/test_logs.py, sematic/db/BUILD, sematic/db/models/tests/test_json_encodable_mixin.py, sematic/db/queries.py, sematic/db/tests/BUILD, sematic/db/tests/fixtures.py, sematic/db/tests/test_queries.py, sematic/plugins/publishing/tests/test_slack.py, sematic/resolvers/tests/test_cloud_resolver.py, sematic/scheduling/job_scheduler.py, sematic/tests/BUILD, sematic/tests/fixtures.py, sematic/tests/test_log_reader.py, sematic/types/type.py
As a part of pod lifecycle work, I discovered some issues with our state management of runs and resolutions. This PR addresses them, and adds some safeguards:
- There is a race condition where if a resolver has hit the `/api/v1/runs/future_states` endpoint at the same time as the run is hitting `POST /api/v1/graph` from `worker.py`, invalid status updates can occur. In particular, external jobs can be deleted by the latter when the former still expects those jobs to be present. Fixed this by having the logic in `/api/v1/graph` which deletes external jobs save the run status before doing so. This enables an existing race condition detection mechanism to work as expected in `/api/v1/runs/future_states` so the run doesn't get marked as failed when it doesn't find jobs.
- Also enforced that …
=> Force runs to pass through only allowed states

sematic/ui/src/Home.tsx
On the home page (landing page) only show the root pipelines of the currently logged-in user.
Tested with a deployment of pipelines owned by the current user vs not.
=> Filter pipelines of current user on the home page

docs/upgrades.md, helm/sematic-server/templates/configmap.yaml, helm/sematic-server/values.yaml, sematic/api/endpoints/storage.py, sematic/plugins/storage/s3_storage.py
The `Image` type PR #623 added caching to the storage `/data` endpoint and the S3 pre-signed URL.
The caching was always a little risky and made the assumption that both URLs (`/data` and S3) would be cached and expire at the same time, which is fickle. This PR removes S3 caching at this time.
Additionally, not specifying the bucket region and signature version to the boto3 client seems to lead to unstable URL signatures. This PR sets both region and signature version. The region needs to be set in the Helm value file.
=> Fix S3 signatures by specifying region and signature version

Makefile
make does not care about your `$SHELL` setting because that would cause portability issues for people that share makefiles because `make` shell behavior would change across machines, and it defaults to `/bin/sh` which can be changed by passing args to the make command or by explicitly setting it in the Makefile.
`make pre-commit` fails on linux because `pushd` is not available.  it turns out it _is_ available on macos, but not on linux.  so this pr forces bash instead because we don't need to live in the stone age.
```
$ make pre-commit
python3 -m flake8
python3 -m mypy sematic
Success: no issues found in 256 source files
python3 -m black sematic --check
All done! ✨ 🍰 ✨
304 files would be left unchanged.
python3 -m isort sematic --diff
Skipped 3 files
pushd sematic/ui && npm run lint && …
```
=> Force /bin/bash in Makefile

.gitignore, docker/Dockerfile.server
Since the `pip install` of the Sematic wheel is one step in the image build, Docker is not able to cache the install of Sematic's requirements. Requirements installs go in the same layer as whatever local changes have been made. This makes the build & push slower than they need to be, and also makes it so k8s nodes aren't able to effectively cache a layer for the image with deps installed. During iterative development and deployment, the wasted time can add up. This makes a couple changes to the Dockerfile that will make it possible during dev to cache the requirements install in a different image layer. This is meant to be used in conjunction with a change in the "serve-dev" development deployment script, which will be able to leverage the caching.
=> Allow caching dev requirements for server build

sematic/resolvers/cloud_resolver.py
Decreases the `CloudResolver` max polling interval from 10 min to 1 min. This will mean that the expected reaction time for progressing on DAG execution decreases from 5 min to 30 s.
The advantage is that after having waited for long-running runs to complete, the Resolver will continue scheduling new, unblocked runs, after waiting a less amount of extra time.
The disadvantage is more logs being outputted by the Resolver, but these are not viewable yet by the users anyway in the Cloud execution workflow that is improved by this PR.
=> Decrease CloudResolver max poll interval to 1 min

Makefile
Enforces local `pre-commit` failure on incorrectly-sorted imports, just as it is in Circleci.
=> Enforce import sorting

docs/local-execution.md
Fixes an incorrect instruction in the user-facing documentation.
=> Fix incorrect set command in user docs

sematic/examples/testing_pipeline/__main__.py, sematic/examples/testing_pipeline/pipeline.py, sematic/resolvers/BUILD, sematic/resolvers/log_streamer.py, sematic/resolvers/state_machine_resolver.py, sematic/resolvers/tests/BUILD, sematic/resolvers/tests/test_local_resolver.py, sematic/resolvers/tests/test_log_streamer.py, sematic/resolvers/worker.py, sematic/utils/BUILD, sematic/utils/signals.py
Fixes #502.
When user business logic inside Sematic `func`s fork subprocesses and then send them signals to kill them, the signal handler that is invoked is a memory copy of the handler installed in the worker process, which is intended to terminate the log streamer process.
As a result, when running in the cloud, the worker pod is terminated early, and when running locally, users have reported weird behaviors where the Resolver hangs.
This not an uncommon occurrence, as many ML or DP frameworks spawn subprocesses.
This PR ensures subprocesses do not execute the worker signal handler, and also installs other safeguards around abnormal subprocesses termination or incorrect or cleanup, to ensure the execution completes naturally, without illegal code accesses.
Added `LocalResolver` unit …
=> Handle signals in subprocesses of business logic

sematic/ee/plugins/external_resource/ray/tests/test_cluster.py
Fixes failing unit tests on `main`.
Externally, passing ci test rules were added to the `main` branch in the GitHub settings.
=> Fix unit tests on main

helm/sematic-server/templates/configmap.yaml, helm/sematic-server/templates/secret.yaml, helm/sematic-server/templates/server-role-binding.yaml, helm/sematic-server/templates/server-role.yaml, helm/sematic-server/templates/serviceaccount.yaml
our helm installs break on new clusters where sematic is not currently installed, because the db migration pod gets created before its secret/configmap is created.  this pr remedies this by creating the base resources at pre-install via a helm hook as well, and by giving them a negative weight value, which means they get created even before the db migration job does.
=> Add minimally required resources to pre-install Helm hook

sematic/ui/packages/main/src/pipelines/Artifacts.tsx
Fixes a bug that the `<ErrorBoundary />` component had no way to recover from an error state. Now use `resetKeys` to fix that, docs [here](https://www.npmjs.com/package/react-error-boundary)
Before:
After:
=> Fixes that ErrorBoundary error never dismisses.

sematic/types/types/tests/BUILD, sematic/types/types/tests/test_tuple.py, sematic/types/types/tuple.py
The elements were used in the `Tuple` summary instead of the elements' summary.
=> Fix tuple summary

sematic/resolvers/local_resolver.py, sematic/resolvers/tests/test_cloud_resolver.py
Currently, for certain failure modes of the resolver, the root run will get marked as `CANCELED`. This has been observed "in the wild" in particular for a failure to schedule a run.
Testing
--------
Changed `schedule_run` API call to this:
```python
def schedule_run(run_id: str) -> Run:
"""Ask the server to execute the calculator for the run."""
import random
if random.random() < 0.10:
raise ValueError("Emulate random failure!")
response = _post(f"/runs/{run_id}/schedule", json_payload={})
return Run.from_json_encodable(response["content"])
```
And launched a [high fan-out run](https://dev1.dev-usw2-sematic0.sematic.cloud/runs/0fba7d8104ea4cafb6759f6867c39f81). Confirmed that the root run got marked as FAILED rather than CANCELED.
=> Mark root run as failed for resolver fails

sematic/api_client.py, sematic/tests/test_api_client.py
Whenever a resolver makes updates to graph/pipeline state, it tries to send out a notification that it has done so. This helps the UI refresh promptly on changes. However, sometimes the socketio server is unable to fulfill the request to broadcast, in which case the resolver would crash. Since this notification is for UI purposes only, it should not be fatal to a resolution. This PR makes it so that is the case.
=> Make notifying about updates not fatal on failure

sematic/ui/packages/main/src/components/RunTime.tsx
For cloned runs, we fill neither the `failed_at` or `resolved_at` fields. In order to display duration correctly, when we see the run has "original_run_id" field, we hardcode the running duration to "<1s"
This will not fix the issue if `failed_at` or `resolved_at` fields are null for failed or canceled runs. That will be investigated separately.
=> Fixes bug when displaying duration for cloned run

sematic/ui/packages/main/src/components/CalculatorPath.tsx, sematic/ui/packages/main/src/components/RunList.tsx
=> Fixes a UI bug that the content of a table cell would explode the table width and disrupt column alignment

sematic/api/endpoints/BUILD, sematic/api/endpoints/artifacts.py, sematic/api/endpoints/storage.py, sematic/api_client.py, sematic/plugins/abstract_storage.py, sematic/plugins/storage/local_storage.py, sematic/plugins/storage/memory_storage.py, sematic/plugins/storage/s3_storage.py, sematic/plugins/storage/tests/test_local_storage.py, sematic/plugins/storage/tests/test_memory_storage.py, sematic/plugins/storage/tests/test_s3_storage.py, sematic/ui/packages/main/src/hooks/blobHooks.ts
Depending on where the client is making a request (in-cluster, browser, local dev box), the host and scheme of a redirect URL are different.
If we controlled a single deployment we could make sure the correct headers are forwarded so as to reconstruct the origin host, but because we don't control every deployment environments, we must use some other mechanism.
In this PR, an `origin` URL parameter is added to queries to store and retrieve stored data.
=> Use URL parameter to construct redirects

sematic/BUILD, sematic/__init__.py
The local Server does not work when installed and started from the wheel for Python 3.10 only. Running from Bazel is unaffected.
The webserver was not accepting connections at all. The fix was to apply the `gevent` monkey patch as the first thing on importing the `sematic` module.
Tested locally in a virtualenv by starting the Server and submitting a pipeline.
=> Make local Server run with Python 3.10

sematic/types/types/matplotlib/figure.py
Using the `matplotlib.figure.Figure` type with non-silent resolvers cause a fatal error:
```
$ bazel run sematic/examples/liver_cirrhosis:liver_cirrhosis
```
After the fix:
The issue was caused by unpropagated changes to the `matplotlib` figure serialization code. I quickly checked the entire codebase, and there don't seem to be other impacted types.
=> Fix matplotlib figures serialization

sematic/config/config.py, sematic/tests/test_versions.py, sematic/versions.py
Fixes #554, which was caused by not comparing the patch version of the `sqlite` version string.
=> Fix corner case sqlite version comparison

requirements/requirements.in, sematic/types/types/image.py, sematic/types/types/matplotlib/BUILD, sematic/types/types/matplotlib/__init__.py, sematic/types/types/matplotlib/figure.py, sematic/types/types/matplotlib/tests/BUILD, sematic/types/types/matplotlib/tests/test_figure.py, sematic/ui/packages/main/src/types/image.tsx, sematic/ui/packages/main/src/types/matplot.tsx, sematic/versions.py
This PR gets rid of the mpld3 dependency to support `matplotlib.figure.Figure` and instead relies on the `Image` type.
=> Use `Image` to support `matplotlib.figure.Figure`

sematic/ui/packages/main/src/hooks/logHooks.ts, sematic/ui/packages/main/src/pipelines/ScrollingLogView.tsx, sematic/ui/packages/main/src/tests/test_utils.cy.ts, sematic/ui/packages/main/src/utils.tsx
1. Fixes bug #690 
2. Adds more loggings to understand different reasons (different types of user interactions) for requesting the server for logs. Captures the moments when the requests are issued and also unpacks the details of cursor/continuation_token. 
3. Sequentialize the requests to request logs but queuing them up, so there should be no overlapping, intertwined log requests. 
4. Add a unit test for the `AsyncInvocationQueue` tool.
=> Add more loggings for logs business

sematic/api/endpoints/resolutions.py
This is a follow-up to #682. That PR made displaying cases when a Run did not have a set ending time more user-friendly. This PR fixes a case when this might happen.
When pipelines are canceled, the Server marks all Runs as failed, but does not set any of the two timestamps we interpret as ending times: `failed_at` or `resolved_at`. This PR sets `failed_at` for canceled Runs, as `resolved_at` would suggest an Artifact exists, which is false.
No unit tests existed for validating the state of Runs after specific operations, so did not introduce any here.
Manually tested that the timestamp is set, reaches the Dashboard, and is rendered correctly.
**Before:**
Server response payload snippet:
```
"created_at": "2023-03-30T17:20:07.708873+00:00",
"description": "Adds all the numbers in the …
```
=> Ensure canceled Runs have and end time

sematic/ui/packages/common/src/component/GitInfo.tsx, sematic/ui/packages/common/src/component/RunStateChips.tsx, sematic/ui/packages/common/src/component/RunTree.tsx, sematic/ui/packages/common/src/component/RunsDropdown.tsx, sematic/ui/packages/common/src/component/TagsList.tsx, sematic/ui/packages/common/src/context/SnackBarProvider.tsx, sematic/ui/packages/common/src/pages/RunDetails/GitSection.tsx, sematic/ui/packages/storybook/src/stories/Dropdown.stories.tsx, sematic/ui/packages/storybook/src/stories/GitInfo.stories.tsx, sematic/ui/packages/storybook/src/stories/RunStateChip.stories.tsx, sematic/ui/packages/storybook/src/stories/Tags.stories.tsx, sematic/ui/packages/storybook/src/stories/TooltipManager.stories.tsx, sematic/ui/packages/storybook/src/stories/Tree.stories.tsx
1. Ensure that the following new components of `GitInfoBoxProps`, `RunTree`, `RunsDropdown` and `TagsList` can handle different input properties and support basic interactivity.
2. Add the complete types for the `RunStateChip` set. 
3. Create new storybook stories for the components mentioned above. 
The change is deployed to 
https://story.dev-usw2-sematic0.sematic.cloud/?path=/story/sematic-gitinfo--git-info&args=has+uncommited+changes:!false
for preview.
=> Show cases some of the new components

sematic/resolvers/cloud_resolver.py, sematic/resolvers/local_resolver.py
This is a follow-up to #703 that ensures all Run terminal state transitions are accompanied by setting the `failed_at` field, after a user had reported that there are other situations other than that covered by #703 that result in an incorrect duration being displayed in the Dashboard.
=> Ensure terminated Runs have an end time

sematic/log_reader.py, sematic/tests/test_log_reader.py
Closes #334
We no longer need to maintain support for reading logs written in the V1 format. This PR removes the source code that supported such reads.
Testing
-------
```
bazel run //sematic/examples/testing_pipeline:__main__ -- --cloud --detach --spam-logs 50000
```
In UI, jumped to end for the spam logs run
```
bazel run //sematic/examples/testing_pipeline:__main__ -- --cloud --detach --sleep 600
```
followed the logs for the sleep run as the run progressed
=> Remove v1 logs support

sematic/resolvers/cloud_resolver.py
Some users have reported errors where the resolver tries to schedule a run twice, which fails the resolution. After extensive attempts, we have been unable to reproduce this ourselves. This PR makes it so this occurrence is less likely to be fatal, and adds extra diagnosis information in any case.
Testing
--------
Executed the testing pipeline with:
```
bazel run //sematic/examples/testing_pipeline:__main__ -- --cloud --detach --fan-out 10
```
3 times.
=> Guard against double-scheduling from resolver

.circleci/config.yml, Makefile, developer-docs/README.md, docker/Dockerfile.ci, docs/contribute-example.md, sematic/db/migrate.py, sematic/db/schema.sql.sqlite
Recently some migration files were omitted from the `sqlite` schema file dump. The effect is that fresh local installations can be created in inconsistent states, that might result in un-applicable subsequent migrations.
To avoid this situation, this PR makes it so the schema is dumped in the pre-commit Make target, which we realistically always run.
Also, this PR includes a dump from a fresh and empty copy of the schema. During development, we might apply migrations which do not end up in main (most often due to changes in their timestamp name component). The result is that developers' local `sqlite` DBs are polluted with dev migrations, which do not actually exist in the codebase.
=> Ensure DB schema dump

sematic/ui/packages/common/src/reactHooks.ts, sematic/ui/packages/storybook/src/stories/Tree.stories.tsx
Back in [PR 702](https://github.com/sematic-ai/sematic/pull/702) I introduced stories for the RunTree component. There I used a class component for the story because I had trouble using functional components and hooks. 
Later investigation indicates that we saw the issue with hooks because, in Storybook's setup, we had two copies of React (despite the same version). The official React manual [here](https://legacy.reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) explains that.
My solution is to reimport the same react hooks used in the `common` package and consume them in the storybook package. This approach is easier to manipulate than symbolic linking the react dependency from the storybook, which will also have the bundler (webpack) treat the two references to the …
=> Use react hooks in story components

docs/changelog.md, docs/developers/manual.md, sematic/ui/packages/main/src/utils.tsx
Usage:
Append `debug=true` as a query parameter to any dashboard page, then this setting will be memorized even without explicitly setting it to the URL. (meant to maintain the debug state across refreshes).
To turn it off, append `debug=false` to the URL or manually clear it from localStorage using browser developer tools.
=> Allow setting debug flag in localstorage

docs/changelog.md, sematic/api/endpoints/resolutions.py, sematic/api/endpoints/tests/BUILD, sematic/api/endpoints/tests/test_resolutions.py, sematic/api/tests/fixtures.py, sematic/api_client.py, sematic/db/models/factories.py, sematic/db/models/mixins/has_user_mixin.py, sematic/db/models/tests/test_resolution.py, sematic/db/tests/fixtures.py, sematic/examples/testing_pipeline/__main__.py, sematic/resolvers/local_resolver.py, sematic/resolvers/state_machine_resolver.py, sematic/ui/packages/main/src/pipelines/PipelineBar.tsx
This fixes a regression where pipeline Resolutions could not be rerun by different users compared to the original submitters:
```
2023-03-30T23:44:29.471676245Z stdout F 2023-03-30 23:44:28,929 - ERROR - sematic.api_client: Server returned 400 for PUT http://sematic-server/api/v1/resolutions/46ae1ecf9a0243c580483140c68ba362: {"error": "Cannot update user_id of resolution 46ae1ecf9a0243c580483140c68ba362 after it has been created. Original value: '146161c5594c49c286dd6fb505761d3c', new value: '650ac18ea09f4c36ad69f752e2ff4620' (will not be used)"}
```
This regression actually disabled a previously-existing escalation of privileges vulnerability, where a reran Resolution would execute using the original submitter's API key, instead of the API key of the user who triggered the rerun.
When a …
=> Ensure different users can rerun Resolutions

sematic/ui/packages/main/src/components/RunTime.tsx
Before:
After:
Testing
-------
```
$ make ui
$ serve-dev
$ bazel run sematic/examples/testing_pipeline:__main__ -- --cloud --detach --sleep 10000
```
Look at run while running, look at completed/canceled/cloned runs
=> Fix display for run runtime when run is running

sematic/ui/packages/common/src/utils/hooks.ts, sematic/ui/packages/main/src/hooks/logHooks.ts, sematic/ui/packages/main/src/tests/test_utils.cy.ts, sematic/ui/packages/main/src/utils.tsx
A bug occurs when logs are already loading, and an accidental simultaneous scroll event triggers another log pull. The second pull will append the same logs twice. 
According to the previous work, we can already sequentialize the pulls using a queue. So the fix is to avoid the second pull being issued if we discovered from the first pull that there would be no more logs. 
This PR does such, and some extras:
1. Add more loggings to understand the async queuing and execution details
2. A helper function `useRefFn` to avoid the initial value of `useRef` being re-created multiple times across rendering. (see also [here](https://github.com/facebook/react/issues/14490))
3. Convert `AsyncInvocationQueue` from a function to a class to carry more responsibilities
4. Updated unit test accordingly.
=> Fixes log duplication issue

sematic/types/types/float.py
When a composite type is checked if it can cast to `float`:
```
ERROR:sematic.resolvers.silent_resolver:Error executing future
File "/home/tudor/.cache/bazel/_bazel_tudor/33dcc00034a66e07dc9fd2f996f93d80/execroot/sematic/bazel-out/k8-fastbuild/bin/sematic/examples/testing_pipeline/__main___binary.runfiles/sematic/sematic/calculator.py", line 185, in calculate
output = self.func(**kwargs)
File "/home/tudor/.cache/bazel/_bazel_tudor/33dcc00034a66e07dc9fd2f996f93d80/execroot/sematic/bazel-out/k8-fastbuild/bin/sematic/examples/testing_pipeline/__main___binary.runfiles/sematic/sematic/examples/testing_pipeline/pipeline.py", line 557, in testing_pipeline
result = add_all(futures) if len(futures) > 1 else futures[0]
File …
```
=> Fix composite type castability check for float

sematic/examples/testing_pipeline/__main__.py, sematic/examples/testing_pipeline/pipeline.py, sematic/types/__init__.py, sematic/types/types/aws/s3.py, sematic/types/types/aws/tests/test_s3.py, sematic/ui/packages/main/src/types/aws.tsx
The links generated in the Dashboard for `S3Location`s that pointed to "directories" rendered an error page.
This is due to S3 only emulating a file system through key-value pairs, without having an actual hierarchical directory structure. S3 has 2 separate endpoints for "directories" and files: "buckets" and "object", respectively
The existing Dashboard hyperlink generation mechanism generates these links using only the "object" endpoint, which results in an error being rendered for "directories".
This PR updates the generation of hyperlinks to S3 in the Dashboard to use the "buckets" endpoint for all locations. In this case, S3 successfully redirects to the "object" endpoint for existent files. Rendering of file links is unaffected.
This PR also introduces a convention in which …
=> Fix S3Location Dashboard link generation for directories

BUILD, sematic.pth, sematic/BUILD, sematic/__init__.py, sematic/api/BUILD, sematic/api/server.py, sematic/cli/main.py
When using gevent, it requires a monkey patch to some standard libraries. This monkey patch has to be applied *very early*, before certain other stdlib imports occur (even in transitive deps). The import is basically only required if you are using the server, but if the patch is applied at the wrong time when doing other things it can cause strange behaviors in other libs. This PR makes it so that we install a [`.pth` file](https://docs.python.org/3/library/site.html) with our wheel which will apply the patch before the user's main module is loaded. The `.pth` file will only work when installed with the wheel though, so some changes are also added in this PR to do an early patch for running the server and the CLI as main for when we're working directly in bazel.
Testing
-------
- built …
=> Make gevent monkey patch occur early

sematic/BUILD, sematic/api/endpoints/tests/test_runs.py, sematic/cli/tests/test_logs.py, sematic/log_reader.py, sematic/tests/test_log_reader.py, sematic/ui/packages/main/src/Payloads.tsx
The front-end wants a more robust way to ensure that duplicate lines are not shown in the log UI (due to duplicated requests, for example). This PR adds unique line ids for each returned log line that is derived from the log line's source file and index in such a way as to ensure that the ids are unique within a given run, and that higher ids are for later log lines.
Testing
-------
In addition to unit tests, also deployed and confirmed that the line ids are being returned by the HTTP request for log lines.
=> Add line ids for log lines

sematic/ui/package-lock.json, sematic/ui/packages/main/package.json, sematic/ui/packages/main/src/utils.tsx
The `useLogger` is used in many React components; each time a component consumes it, it has to re-fetch the setting in the URL and local storage, which is not performant.
1. The debug flag is set per page load and persists unless the page is reloaded again. The setting does not need to be re-read when the page session is live.
2. The logging function instance can be memorized instead of re-created for each component. 
This PR addresses the above issues by leveraging [lodash's memoize](https://www.geeksforgeeks.org/lodash-_-memoize-method/)
=> Refactors devLogger creation

README.md
The API token was completely missing from the CircleCI project settings. Created a dedicated one.
Before:
After:
=> Fix CircleCI GitHub badge

bazel/pipeline.bzl
Removes an unused parameter from `sematic_pipeline`, in order to avoid confusion.
=> Remove unused image_tags param from sematic_pipeline

helm/sematic-server/templates/ingress.yaml, helm/sematic-server/values.yaml
accidental usage of `http://` urls that are insecure, and cause google oauth to throw errors because it does not allow mixed use of secure/insecure domains.  rather than failing silently, we set all http requests to redirect to https by default so that users have a secure default.  also added `ingress.force_ssl` as an option so that this can be disabled for local/unsecured clusters.
fixes #597
=> Force HTTP requests to redirect to HTTPS by default

developer-docs/README.md
`helm repo add sematic-ai https://sematic-ai.github.io/helm-charts` might need to be run at least once. It might be a once-in-a-lifetime setup, but it is still worth mentioning.
=> Improve release doc about setting up helm repo ahead of time

sematic/ui/packages/common/src/Models.ts, sematic/ui/packages/main/src/Payloads.tsx, sematic/ui/packages/main/src/hooks/podHistoryHooks.ts, sematic/ui/packages/main/src/pipelines/RunTabs.tsx, sematic/ui/packages/main/src/pipelines/external_resource/ExternalResource.tsx, sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodEventHistory.tsx, sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodLifecycle.tsx, sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodLifecycleEvent.tsx, sematic/ui/packages/main/src/sockets.ts
Implements the Pod lifecycle history UI. 
The information displayed will be updated when the job is running.
The change is deployed to the `chance` namespace.
=> Pod lifecycle history UI

sematic/api/endpoints/resolutions.py, sematic/api/endpoints/runs.py, sematic/api/endpoints/tests/test_resolutions.py, sematic/api/endpoints/tests/test_runs.py, sematic/api_client.py, sematic/db/models/resolution.py, sematic/db/queries.py, sematic/db/tests/test_queries.py, sematic/scheduling/BUILD, sematic/scheduling/job_details.py, sematic/scheduling/job_scheduler.py, sematic/scheduling/kubernetes.py
Add APIs to clean up jobs that are still around/whose metadata claims they are after their run/resolution has terminated.
Testing
-------
In addition to unit tests, also used this API via the API client on the Sematic deployment in the `josh` namespace.
=> Add APIs to clean up orphaned jobs

sematic/db/models/git_info.py, sematic/ui/packages/main/src/components/GitInfo.tsx, sematic/utils/git.py
When submitting a pipeline from an uninitialized Git repo, information about the repo may be successfully collected, even though the first commit does not exist. This will produce a rendering error:
By requiring a commit to exist for the purposes of rendering the Git information, the issue is fixed:
=> Support uninitialized Git repo rendering

sematic/ui/packages/main/src/hooks/textSelectionHooks.ts, sematic/ui/packages/main/src/pipelines/pod_lifecycle/PodLifecycle.tsx, sematic/ui/packages/main/src/types/aws.tsx
Introduces a tool that prevents text selection from triggering click events. 
This was something used for S3Button. Now, it is extracted as a common utility that also applies to Pod life cycle accordions. 
Before:
After:
=> Extracts the text selection tool as a common utility

docs/SUMMARY.md, docs/api.md, docs/cloud-resolver.md, docs/errors.md, docs/glossary.md, docs/multiple-base-images.md, sematic/abstract_future.py, sematic/calculator.py, sematic/ee/plugins/external_resource/ray/cluster.py, sematic/ee/plugins/external_resource/ray/tests/load_testing/pipeline.py, sematic/examples/bazel/pipeline.py, sematic/examples/cifar_classifier/pipeline.py, sematic/examples/lightning_resnet/pipeline.py, sematic/examples/mnist/pytorch/pipeline.py, sematic/examples/retry/pipeline.py, sematic/examples/testing_pipeline/__main__.py, sematic/examples/testing_pipeline/pipeline.py, sematic/future.py, sematic/log_reader.py, sematic/resolvers/cloud_resolver.py, sematic/resolvers/state_machine_resolver.py, sematic/resolvers/tests/test_cloud_resolver.py, sematic/tests/test_calculator.py, sematic/tests/test_future.py
We still need to keep the Inline term in some places to refer to non-Standalone functions.
=> Migrating `inline=False` to `standalone=True`

docs/local-execution.md, sematic/plugins/storage/local_storage.py, sematic/plugins/storage/tests/BUILD, sematic/plugins/storage/tests/test_local_storage.py
This PR introduces a new settings for the `LocalStorage` plug-in. Before this PR, the local storage location was `~/.sematic/data`. Users can now customize it with the `LOCAL_STORAGE_PATH` settings and env var.
=> Make local storage location configurable

developer-docs/README.md, helm/sematic-grafana-dashboards/.helmignore, helm/sematic-grafana-dashboards/Chart.yaml, helm/sematic-grafana-dashboards/templates/sematic_jobs_dashboard_configmap.yaml, helm/sematic-grafana-dashboards/templates/sematic_server_dashboard_configmap.yaml, helm/sematic-grafana-dashboards/values.yaml
creates a separate helm package called `sematic-grafana-dashboards`, that will be served up by the same helm release mechanism we currently have in the `sematic-ai/helm-charts` repo, i.e. it will share the same `index.yaml` file in that repo, but will be it's own standalone helm package that must be installed separately by the user.
=> Add Sematic Grafana dashboards as helm package

helm/sematic-server/templates/configmap.yaml, helm/sematic-server/values.yaml
When local storage is selected, users can customize the storage location. This PR exposes this to the config map.
=> Add `LOCAL_STORAGE_PATH` to config map

sematic/api/endpoints/resolutions.py, sematic/api_client.py
Fixes an issue where the API Client logs a malformed error message:
```
sematic.api_client.ServerError: The Sematic server could not handle the POST request to http://127.0.0.1:5001/api/v1/resolutions/44fe6d5a6a9743fc86206ce13091fb62/schedule. NonePlease check the Sematic server logs for more information.
```
The problem is here: `[...]/schedule. NonePlease check the [...]`
After fixing the error message format:
```
sematic.api_client.ServerError: The Sematic server could not handle the POST request to http://127.0.0.1:5001/api/v1/resolutions/2c8d8da0322644689064cda9390bef5c/schedule. Please check the Sematic Server logs for more information.
```
And after fixing this particular endpoint's error handling:
```
sematic.api_client.BadRequestError: The POST request to …
```
=> Fix malformed API client error message

sematic/examples/mnist/pytorch/requirements.txt
The MNIST code uses plotly APIs that are only available after 5.5.0.
=> Constrain plotly version for MNIST example

sematic/ui/packages/common/src/component/Section.tsx, sematic/ui/packages/common/src/component/TagsList.tsx, sematic/ui/packages/common/src/layout/ThreeColumns.tsx, sematic/ui/packages/common/src/layout/TwoColumns.tsx, sematic/ui/packages/common/src/muitypes.d.ts, sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/CollapseableFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/OrderSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/OtherFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/OwnersFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/SearchTextSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/StatusFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/TagsFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/common.ts, sematic/ui/packages/common/src/pages/RunSearch/index.tsx, sematic/ui/packages/common/src/theme/new/componnets.ts, sematic/ui/packages/common/src/theme/new/palette.ts, sematic/ui/packages/storybook/src/stories/Color.stories.tsx, sematic/ui/packages/storybook/src/stories/Page.stories.tsx, sematic/ui/packages/storybook/src/stories/RunFilter.stories.tsx
The PR covers the new Run Search page -- the filters section.
It can be previewed at:
https://story.dev-usw2-sematic0.sematic.cloud/iframe.html?args=&id=sematic-page--run-search&viewMode=story
Two small side stories are added to demonstrate interactivity:
[Status Filter](https://story.dev-usw2-sematic0.sematic.cloud/?path=/story/sematic-runfilters--status-filter)
[Owner Filter](https://story.dev-usw2-sematic0.sematic.cloud/?path=/story/sematic-runfilters--owner-filter)
=> Storybook for the new Run Search page

sematic/api/endpoints/BUILD, sematic/api/endpoints/artifacts.py, sematic/api/endpoints/edges.py, sematic/api/endpoints/notes.py, sematic/api/endpoints/request_parameters.py, sematic/api/endpoints/resolutions.py, sematic/api/endpoints/runs.py, sematic/api/endpoints/tests/test_resolutions.py, sematic/api/endpoints/tests/test_runs.py, sematic/api_client.py, sematic/cli/clean.py, sematic/db/queries.py, sematic/db/tests/test_queries.py
Refactor the orphaned run/resolution query endpoints to look like run/resolution searches.
Queries look something like:
```
/api/v1/runs?filters='{"orphaned_jobs": {"eq": true}}'
```
Testing
-------
In addition to unit tests, intentionally orphaned some jobs and then deployed these changes (including the cleaner) and confirmed the runs/resolutions had their jobs cleaned. Intentionally [orphaned run](https://josh.dev-usw2-sematic0.sematic.cloud/runs/62dfd02dec0b478cb1b4406965dcde7c#panel=run&run=0809100fcd3b4d3b890f44cea3aac94f&tab=pod_lifecycle)
=> Refactoring "garbage" endpoints into existing search

sematic/ui/packages/common/src/component/TagsInput.tsx, sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/CollapseableFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/OwnersFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/StatusFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/TagsFilterSection.tsx, sematic/ui/packages/common/src/theme/new/componnets.ts, sematic/ui/packages/storybook/src/stories/Tags.stories.tsx
1. A new component `<TagInput />` is implemented to allow users to dynamically input tags.
2. Added to the Run Search page.
3. Created a dedicated story for such  a `<TagInput />` component.
Demo: https://story.dev-usw2-sematic0.sematic.cloud/iframe.html?args=&id=sematic-page--run-search&viewMode=story
=> A component to allow creating tag filters dynamically

sematic/plugins/abstract_builder.py, sematic/plugins/building/docker_builder.py
This is the second PR in a chain that introduces a Build System plugin with an implementation that uses native Python+Docker capabilities to build a container image and launch a pipeline, without requiring Bazel. The previous PR in the chain is #777.
This PR implements functionality that installs requirements, data files, source files, and an entry point on top of the base image. The base image can either be supplied directly in the build config file, or the result of executing the build script. This takes away responsibility from the user supplying a complete image.
Updated https://github.com/sematic-ai/example_docker/pull/1 with the changes from this PR. Of note, removed the entry point requirements from the advanced case, and added the `project` field.
Unit tests will be introduced in …
=> [2/N] Native Build System starting from base images

sematic/api/endpoints/payloads.py, sematic/api/endpoints/tests/test_runs.py
Due to a missing `function_path` -> `calculator_path` adaptor in the Server Run `list` endpoint, older clients are not supported.
This PR introduces the adaptor, as on the `get` endpoint.
=> Fix calculator_path client backwards compatibility

sematic/plugins/building/docker_builder.py, sematic/plugins/building/tests/fixtures/good_launch_script.yaml, sematic/plugins/building/tests/test_docker_builder.py
This is the third PR in a chain that introduces a Build System plugin with an implementation that uses native Python+Docker capabilities to build a container image and launch a pipeline, without requiring Bazel. The previous PR in the chain is #807.
This PR makes the Docker Client connection configurable, and fills in docstrings.
Validated that the intermediate and advanced cases from the [`example_docker` repo](https://github.com/sematic-ai/example_docker) still work, and added unit tests and checks for the new funcitonality:
```bash
$ bazel test --test_output=all sematic/plugins/building/tests:test_docker_builder
```
=> [4/N] Build System configurable Docker connection

sematic/ui/package-lock.json, sematic/ui/package.json, sematic/ui/packages/common/package.json, sematic/ui/packages/common/src/component/DateTime.tsx, sematic/ui/packages/common/src/component/RunReferenceLink.tsx, sematic/ui/packages/common/src/component/RunStateChips.tsx, sematic/ui/packages/common/src/component/RunStateText.ts, sematic/ui/packages/common/src/component/Table.tsx, sematic/ui/packages/common/src/component/TagsList.tsx, sematic/ui/packages/common/src/layout/TwoColumns.tsx, sematic/ui/packages/common/src/muitypes.d.ts, sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx, sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/RunList.tsx, sematic/ui/packages/common/src/pages/RunSearch/RunStatusColumn.tsx, sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx, sematic/ui/packages/common/src/pages/RunSearch/index.tsx, sematic/ui/packages/common/src/theme/new/components.ts, sematic/ui/packages/common/src/theme/new/index.ts, sematic/ui/packages/storybook/src/stories/RunStateChip.stories.tsx
1. This PR implements the static elements for the Run search table in the new style.
1. Introduced: [@tanstack/react-table](https://tanstack.com/table/v8) library
1. added border-radius: 2px to the filter buttons.
Preview: https://story.dev-usw2-sematic0.sematic.cloud/iframe.html?args=&id=sematic-page--run-search&viewMode=story
=> Search table static page

sematic/logging.py
Fixes application logs being duplicated.
Also refactors the touched code in order to improve readability.
Before:
```
$ sematic run examples/add
Running example script: '['examples/add']'
Running example examples/add
2023-05-09 16:50:45,842 [INFO] sematic.resolvers.state_machine_resolver: Starting resolution c2e4fbc29bc14e91afa8af6e8940d7e2
2023-05-09 16:50:45,842 [INFO] sematic.resolvers.state_machine_resolver: Starting resolution c2e4fbc29bc14e91afa8af6e8940d7e2
2023-05-09 16:50:48,152 [INFO] sematic.resolvers.state_machine_resolver: Running inline c2e4fbc29bc14e91afa8af6e8940d7e2 sematic.examples.add.pipeline.pipeline
2023-05-09 16:50:48,152 [INFO] sematic.resolvers.state_machine_resolver: Running inline c2e4fbc29bc14e91afa8af6e8940d7e2 sematic.examples.add.pipeline.pipeline
2023-05-09 …
```
=> Fix log duplication

helm/sematic-server/templates/hpa.yaml, helm/sematic-server/templates/pdb.yaml, helm/sematic-server/values.yaml
fixes #743.
all changes listed below apply only to the api server.  socket io server is unaffected, disruptions on it are considered "acceptable" since it is not mission critical for correctness.
- increases default replica count to 2.  this is required for fault tolerance and so that the pod disruption budget of 1 does not prevent nodes from draining.
- adds horizontal pod autoscaling (hpa) support, can be optionally enabled
- adds pod disruption budget of min 1 pod available, enabled by default
- hpa is now supported via the latest kube api version `autoscaling/v2`
- server cpu/memory resource request/limits are both halved to prior values, to account for 2 replicas being deployed by default compared to 1 before.
helm doc changes to follow in a separate pr.
=> Add horizontal pod autoscaling and pod disruption budget for API server

sematic/api_client.py, sematic/cli/BUILD, sematic/cli/run.py, sematic/logging.py, sematic/plugins/building/docker_builder.py, sematic/plugins/building/tests/fixtures/bad_version.yaml, sematic/plugins/building/tests/fixtures/good_launch_script.yaml, sematic/plugins/building/tests/fixtures/good_minimal.yaml, sematic/plugins/building/tests/fixtures/malformed_push1.yaml, sematic/plugins/building/tests/fixtures/malformed_push2.yaml, sematic/plugins/building/tests/fixtures/malformed_uri.yaml, sematic/plugins/building/tests/fixtures/no_image.yaml, sematic/plugins/building/tests/fixtures/two_images.yaml, sematic/tests/test_api_client.py
This is the fifth PR in a chain that introduces a Build System plugin with an implementation that uses native Python+Docker capabilities to build a container image and launch a pipeline, without requiring Bazel. The previous PR in the chain is #813.
This PR updates the `sematic run` CLI command to be able to run proprietary builds and launch cloud pipelines in addition to example pipelines. This effectively exposes the Docker Build System to users.
```
$ bazel test --test_output=all sematic/plugins/building/tests:test_docker_builder
```
```
$ sematic run --help
Usage: sematic run [OPTIONS] SCRIPT_PATH [SCRIPT_ARGUMENTS]...
Options:
-b, --build           Build a container image that will be used to execute
the pipeline, using the configured build plugin.
Defaults to `False`. If not set, …
```
=> [5/N] Run pipeline build through CLI

sematic/api/endpoints/tests/BUILD, sematic/api/endpoints/tests/test_auth.py, sematic/api/endpoints/tests/test_resolutions.py, sematic/config/BUILD, sematic/config/server_settings.py, sematic/config/settings.py, sematic/config/tests/BUILD, sematic/config/tests/test_config_dir.py, sematic/config/tests/test_settings.py, sematic/config/user_settings.py, sematic/ee/plugins/external_resource/ray/tests/BUILD, sematic/ee/plugins/external_resource/ray/tests/test_cluster.py, sematic/plugins/building/BUILD, sematic/plugins/building/docker_builder.py, sematic/plugins/kuberay_wrapper/tests/BUILD, sematic/plugins/kuberay_wrapper/tests/test_standard.py, sematic/plugins/publishing/tests/BUILD, sematic/plugins/publishing/tests/test_slack.py, sematic/resolvers/tests/BUILD, sematic/resolvers/tests/test_cloud_resolver.py, sematic/resolvers/tests/test_worker.py, sematic/scheduling/tests/BUILD, sematic/scheduling/tests/test_kubernetes.py, sematic/tests/fixtures.py, sematic/utils/BUILD, sematic/utils/env.py, sematic/utils/types.py
This is the sixth PR in a chain that introduces a Build System plugin with an implementation that uses native Python+Docker capabilities to build a container image and launch a pipeline, without requiring Bazel. The previous PR in the chain is #815.
This PR eliminates tech debt by extracting two local functions from other code modules to utility functions, and reusing them in the new Docker Build System, in addition to the original usages.
=> [6/N] Extract and reuse utility functions in DockerBuiler

sematic/db/db.py
Closes #792
This PR adds automatic connection expiration for connections in the pool. It also adds a mechanism to validate connections before trying to use them. Both changes should make Sematic more robust against DB availability issues.
Testing
-------
Set the timeout to 30s, and ran several example pipelines against the local server. Deployed to my namespace and executed the testing pipeline.
=> Add some mechanisms to make DB connection handling more robust

sematic/ui/packages/common/src/ApiContracts.ts, sematic/ui/packages/common/src/component/TagsInput.tsx, sematic/ui/packages/common/src/component/common.ts, sematic/ui/packages/common/src/hooks/userHooks.ts, sematic/ui/packages/common/src/pages/RunSearch/RunList.tsx, sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/OtherFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/OwnersFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/SearchTextSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/StatusFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/TagsFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/common.ts, sematic/ui/packages/common/src/pages/RunSearch/index.tsx, sematic/ui/packages/storybook/src/stories/RunFilter.stories.tsx
Support applying search filters to filter run list table by adding filter conditions to backend call. 
1. Blank result page style is not yet implemented.
2. `tags` is not working (not included in the search conditions), but resetting filters will reset tags.
3. If there are multiple values for the same search type, eg, searching both `completed` and `failed` runs, the conditions will be concatenated with `OR`
4. Different search filter types will be linked with `AND`. eg. search `completed` and `user_id=1` will become ['AND', `completed`,`user_id=1`] (in reverse polish notation)
5. Fuzzy test search can be combined with other search filter types using `AND` relationship.
The effect can be previewed in `my` namespace.
=> [New dashboard UI] Apply or reset search filters

sematic/resolvers/cloud_resolver.py, sematic/resolvers/local_resolver.py, sematic/resolvers/tests/test_local_resolver.py
If we failed somewhere between root run creation and resolution creation, we could swallow the original source of the failure and replace it with a "resolution not found" error when we tried to update the status of the resolution to failed. This PR makes it so that we instead just log a warning about the fact that we won't be able to update the resolution status, and allows the original error to continue to propagate.
Testing
-------
In addition to unit tests, raised an intentional error from `_make_resolution` and confirmed that the console showed both the original error and the warning message about inability to update status:
```
INFO:__main__:Command line arguments: Namespace(cache_namespace=None, cloud=True, detach=True, exit_code=None, expand_shared_memory=False, …
```
=> Make early resolution failure more robust

docker/Dockerfile.ci, docker/Dockerfile.worker, sematic/plugins/building/docker_builder.py, sematic/plugins/building/tests/fixtures/docker/Dockerfile.basic, sematic/plugins/building/tests/fixtures/docker/Dockerfile.data, sematic/plugins/building/tests/fixtures/docker/Dockerfile.full, sematic/plugins/building/tests/fixtures/docker/Dockerfile.requirements, sematic/plugins/building/tests/fixtures/docker/Dockerfile.src, sematic/plugins/building/tests/fixtures/docker/Dockerfile.target
Using `apt` results in "interactive" warning messages:
This PR switches to `apt-get`, which is supposed to be the "script-safe" version.
=> Switch to apt-get

sematic/ui/packages/common/src/component/NameTag.tsx, sematic/ui/packages/common/src/component/Note.tsx, sematic/ui/packages/common/src/component/ShellCommand.tsx, sematic/ui/packages/common/src/hooks/runHooks.ts, sematic/ui/packages/common/src/pages/RunSearch/RunList.tsx, sematic/ui/packages/common/src/pages/RunSearch/RunListEmptyState.tsx, sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/OwnersFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/index.tsx, sematic/ui/packages/main/src/Home.tsx, sematic/ui/packages/main/src/components/TrackingNotice.tsx
Display an empty state UI when the run search returns no result. Depending on whether a filter is used, there are two styles for the empty state page.
Demo:
Others:
1. Improved rendering of user's name, prevents displaying "undefined undefined".
2. Migrated `<ShellCommand />` to `common` package.
3. Relocated the logic for generating the filter conditions.
4. Updated obsolete discord link.
=> Display empty state in run search table

sematic/ui/packages/main/src/setupProxy.js
Missing this proxy rule disrupts using websocket in local dev scenarios.
=> Add the missing proxy rule.

sematic/plugins/building/BUILD, sematic/plugins/building/docker_builder.py, sematic/plugins/building/docker_client_utils.py, sematic/plugins/building/tests/BUILD, sematic/plugins/building/tests/test_docker_builder.py, sematic/plugins/building/tests/test_docker_client_utils.py
The Native Docker Build System prints update messages from the Docker Server in a rolling window, but sometimes this window does not correctly reset:
```
Building image and launching: yolo_v5_poc/main.py --tiny-model-test
[...]
[...]
[...]
[...]
[...]
[...]
[...]
[...]
[...]
[...]
[...]
stream=---> e210d40bab91
stream=Step 20/22 : COPY vflow_util/__init__.py vflow_util/__init__.py
stream=---> 4560ef9dbe78
stream=Step 21/22 : COPY vflow_util/argparse.py vflow_util/argparse.py
stream=---> b191bede1f1f
stream=Step 22/22 : COPY vflow_util/vflow_alluxio_fuse.py vflow_util/vflow_alluxio_fuse.py
stream=---> 2e9b7040ef2f
aux={'ID': 'sha256:2e9b7040ef2f9438458410d7fd573cebfdeda83518c49da16e2a0769e418e890'}
stream=Successfully built 2e9b7040ef2f
stream=Successfully tagged …
```
=> Wrap Docker update messages

sematic/ui/packages/common/src/ApiContracts.ts, sematic/ui/packages/common/src/component/GitInfo.tsx, sematic/ui/packages/common/src/component/Note.tsx, sematic/ui/packages/common/src/hooks/noteHooks.ts, sematic/ui/packages/common/src/layout/ThreeColumns.tsx, sematic/ui/packages/common/src/pages/RunDetails/NotesPane.tsx, sematic/ui/packages/main/src/Payloads.tsx, sematic/ui/packages/main/src/pipelines/NotesPanel.tsx
This PR also uses real data of notes on the run details page. 
Now the note pane can also be folded.
=> [New dashboard] Render and submit notes in the right pane of run details page

sematic/db/migrate.py
When developing migration scripts, the updated schema is dumped to a new `schema.sql` file in the project root. We then have to copy it over to `sematic/db/schema.sql.sqlite` in order to commit the changes.
This PR switches the default dump location to that file directly.
=> Dump the SQL schema to the current schema file by default

sematic/plugins/building/docker_builder.py, sematic/plugins/building/tests/fixtures/docker/Dockerfile.basic, sematic/plugins/building/tests/fixtures/docker/Dockerfile.data, sematic/plugins/building/tests/fixtures/docker/Dockerfile.full, sematic/plugins/building/tests/fixtures/docker/Dockerfile.requirements, sematic/plugins/building/tests/fixtures/docker/Dockerfile.src, sematic/plugins/building/tests/fixtures/docker/Dockerfile.target
Avoids [a bug in `pip`'s resolution algorithm](https://github.com/pypa/pip/issues/10851) by pinning the version.
Stack trace:
```
(venv_test) tudor@ip-10-42-76-65:~/sematic$ sematic run --build sematic/examples/lightning_resnet/main.py -- --cloud
Sematic will soon require the sqlite3 version to be at least 3.38.0, but your Python is using 3.37.2. Please upgrade. You may find this useful: https://stackoverflow.com/a/55729735/2540669
WARNING:sematic.config.config:Sematic will soon require the sqlite3 version to be at least 3.38.0, but your Python is using 3.37.2. Please upgrade. You may find this useful: https://stackoverflow.com/a/55729735/2540669
Building image and launching: sematic/examples/lightning_resnet/main.py --cloud
2023-05-26 10:07:30,060  [INFO] …
```
=> Avoid pip resolution bug

sematic/plugins/building/BUILD, sematic/plugins/building/docker_builder.py, sematic/plugins/building/docker_client_utils.py, sematic/utils/BUILD, sematic/utils/spinner.py
When passing the `--log-level=debug` parameter to the Native Docker Build System, this update deactivates the rolling window feature so that all update messages can be seen after during execution. This also simplifies any log files that are `tee`'d during execution, as they will not be interleaved with non-human readable deletion characters.
This also extracts printing the spinner character while waiting on a reply from the Docker server to a context manager for syntactic sugar, and also propagates it to waiting for pushing the image, not only while waiting for building it.
**No debug:**
```
(3.9.14/envs/3.9.14-testing) ~/work/example_docker$ sematic run --build intermediate/main.py -- /intermediate/data/message.txt
Building image and launching: intermediate/main.py …
```
=> Disable Docker updates rolling window on DEBUG level

sematic/plugins/building/docker_builder.py, sematic/plugins/building/tests/BUILD, sematic/plugins/building/tests/fixtures/absolute_data.yaml, sematic/plugins/building/tests/fixtures/absolute_image_script.yaml, sematic/plugins/building/tests/fixtures/absolute_requirements.yaml, sematic/plugins/building/tests/fixtures/absolute_src.yaml, sematic/plugins/building/tests/fixtures/bad_version.yaml, sematic/plugins/building/tests/fixtures/docker/Dockerfile.full, sematic/plugins/building/tests/fixtures/good_launch_script.yaml, sematic/plugins/building/tests/fixtures/jailbreak_data.yaml, sematic/plugins/building/tests/fixtures/jailbreak_image_script.yaml, sematic/plugins/building/tests/fixtures/jailbreak_requirements.yaml, sematic/plugins/building/tests/fixtures/jailbreak_src.yaml, sematic/plugins/building/tests/fixtures/malformed_push_empty_registry.yaml, sematic/plugins/building/tests/fixtures/malformed_push_missing_repository.yaml, sematic/plugins/building/tests/fixtures/malformed_uri.yaml, sematic/plugins/building/tests/fixtures/nested/ignored.yaml, sematic/plugins/building/tests/fixtures/nested/launch_script.yaml, sematic/plugins/building/tests/fixtures/nested/sematic_build.yaml, sematic/plugins/building/tests/fixtures/nested/third_level/third_level.txt, sematic/plugins/building/tests/fixtures/no_image.yaml, sematic/plugins/building/tests/fixtures/two_images.yaml, sematic/plugins/building/tests/test_docker_builder.py, sematic/plugins/building/tests/test_docker_builder_config.py
The source and data file globbing resolution was not done recursively, meaning that only one level of nesting resolution was supported.
This fixes the bug and adds a new test case to validate multi-level file globbing resolution.
=> Fix Native Docker Build System recursive globbing

sematic/cli/run.py, sematic/db/migrations/20230526141354_add_run_command_and_config_to_resolutions.sql, sematic/db/models/factories.py, sematic/db/models/resolution.py, sematic/db/models/tests/test_factories.py, sematic/db/schema.sql.sqlite, sematic/db/tests/fixtures.py, sematic/plugins/abstract_builder.py, sematic/plugins/building/docker_builder.py, sematic/plugins/building/docker_builder_config.py, sematic/plugins/building/tests/fixtures/good_launch_script.py, sematic/plugins/building/tests/test_docker_builder.py, sematic/resolvers/BUILD, sematic/resolvers/local_resolver.py, sematic/scheduling/tests/test_job_scheduler.py
This is the eight PR in a chain that introduces a Build System plugin with an implementation that uses native Python+Docker capabilities to build a container image and launch a pipeline, without requiring Bazel. The previous PR in the chain is #850.
This PR stores the CLI run command and the build configuration object text that were used to launch a pipeline in the database, in the `resolutions` table. At a later date, these will be exposed in the Dashboard.
Existing unit and integration tests are updated to cover the new functionality. Some previously-missing checks are also filled in.
**Submit a pipeline:**
```
(venv_test) tudor@ip-10-42-76-65:~/example_docker$ sematic run --build --log-level=debug intermediate/main.py -- /intermediate/data/message.txt
[...] …
```
=> [8/N] Store run command and build config

sematic/resolvers/local_resolver.py, sematic/resolvers/tests/test_cloud_resolver.py, sematic/resolvers/worker.py
Currently the `--rerun-mode` argument is always injected into the pod, even if the run is not a rerun:
```
[...]
"args": [
"--run_id",
"98b7a2cbb2fb454e822a9bfbae732733",
"--resolve",
"--rerun-mode",
"SPECIFIC_RUN"
],
[...]
```
This updated the default value of the argument to be `None` instead, so the argument is not passed:
```
[...]
"args": [
"--run_id",
"5938a5221b4f448db06f5ff1c67a94f1",
"--resolve"
],
[...]
```
Also adds a missing log.
=> Remove redundant pod argument

sematic/__init__.py
A user was attempting to import newly-added Kubernetes utility classes directly from the Sematic base init module, as with other existing classes.
This PR adds these to the base init for improved usability.
=> Expose all K8 classes in base init

requirements/ci-requirements.txt
`mypy` is manifesting a bug where it incorrectly reports a syntax error in a pyenv virtual env only on CircleCI. This is caused by [a bug in `mypy` itself](https://github.com/python/mypy/issues/13627).
This started manifesting suddenly and [is blocking merges to `main`](https://app.circleci.com/pipelines/github/sematic-ai/sematic/3874/workflows/8ae1a54b-0381-4a51-ad8a-93dc3f820a70/jobs/13753).
This PR updates the version of `mypy` to avoid the bug.
=> Update mypy version to avoid bug

sematic/examples/mnist/pytorch/__main__.yaml, sematic/examples/mnist/pytorch/mnist_learning_rates.yaml, sematic/examples/mnist/pytorch/mnist_train.yaml, sematic/examples/mnist/pytorch/requirements.txt, sematic/examples/template/requirements.txt, sematic/plugins/building/docker_builder.py, sematic/plugins/building/tests/fixtures/docker/Dockerfile.basic, sematic/plugins/building/tests/fixtures/docker/Dockerfile.data, sematic/plugins/building/tests/fixtures/docker/Dockerfile.full, sematic/plugins/building/tests/fixtures/docker/Dockerfile.requirements, sematic/plugins/building/tests/fixtures/docker/Dockerfile.src, sematic/plugins/building/tests/fixtures/docker/Dockerfile.target, sematic/plugins/building/tests/test_docker_builder.py, sematic/utils/spinner.py
This slightly optimizes the size and build time of the Docker images constructed by the Native Docker Build System.
Changes:
- Switches from installing `pip` via `apt` to installing it from source.
- Always ensures `Sematic` is installed, even if it is not specified in the pipeline's requirements.
- Moved data file copying before requirements installation, to permit users including required wheels in the build.
- Fixes bug in `pip` command which did not deactivate cache dir, as was the intention.
- Fixes corner case where sometimes the existing incomplete `distutils` distribution was not overwritten with a full one required by some requirements.
- Manages to avoid installing `apt-utils`.
- Reduces number of layers.
- Reduces log spam during requirements installation.
- Renames silly-named …
=> Optimize Native Docker builds temporally and spatially

tools/sematic_wheel_rule.bzl
#857 caused the `sematic["default"]` wheel to also install `ray` dependencies, resulting in a Server Docker image size increase.
This PR updates the logic that decides which dependencies are "ee" or not to also include example pipelines which showcase "ee" behavior.
Before Regression:
```
DIGEST        OS/ARCH      SCANNED  LAST PULL  COMPRESSED SIZE 
6b9d41963f35  linux/amd64  ---      a day ago  416.27 MB
```
Regression:
```
DIGEST        OS/ARCH      SCANNED  LAST PULL  COMPRESSED SIZE 
0c9f38e013d1  linux/amd64  ---      a day ago  5.1 GB
```
After Fix:
```
DIGEST        OS/ARCH      SCANNED  LAST PULL      COMPRESSED SIZE 
cf0a4855948a  linux/amd64  ---      2 minutes ago  416.36 MB
```
=> Fix Server image size bloat

sematic/ui/packages/common/src/ApiContracts.ts, sematic/ui/packages/common/src/hooks/runHooks.ts, sematic/ui/packages/common/src/pages/RunSearch/RunList.tsx, sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/TagsFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/common.ts
Link to backend api to actually filter runs by tags.
unfortunately using multiple filter types currently doesn't work and will be investigated separately.
=> Support filter runs by tags

sematic/ui/packages/common/src/ApiContracts.ts, sematic/ui/packages/common/src/hooks/runHooks.ts, sematic/ui/packages/common/src/pages/RunSearch/filters/common.ts
Use `in` operator instead of `or` operator to avoid the deficiency of supporting nested boolean operations.
For tags search, each tag value will be `and`ed. This avoids the need to support `{'OR': [{tag: {contains: v1}}, {tag: {contains: v2}}]}`
=> Use in operator for the run search filters

sematic/ui/packages/common/src/typeViz/vizMapping.ts, sematic/ui/packages/main/src/types/Types.tsx
Matplot lib viz regressed, since it got removed from the front-end type registry when we moved it to store the summary as an image. This restores it to functionality. Now works in both new and old UIs.
=> Fix matplotlib viz

sematic/ui/packages/common/src/component/ContextMenu.tsx, sematic/ui/packages/common/src/component/MoreVertButton.tsx, sematic/ui/packages/common/src/hooks/resolutionHooks.ts, sematic/ui/packages/common/src/hooks/runHooks.ts, sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx, sematic/ui/packages/common/src/pages/RunDetails/PipelineSection.tsx, sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx, sematic/ui/packages/common/src/pages/RunDetails/artifacts/artifact.tsx, sematic/ui/packages/common/src/pages/RunDetails/contextMenus/ArtifactMenu.tsx, sematic/ui/packages/common/src/pages/RunDetails/contextMenus/FunctionSectionMenu.tsx, sematic/ui/packages/common/src/pages/RunDetails/contextMenus/PipelineSectionMenu.tsx, sematic/ui/packages/common/src/pages/RunDetails/contextMenus/RunSectionMenu.tsx, sematic/ui/packages/common/src/theme/new/components.ts
Add context menus on the run details page. 
This PR implements the context menu for 4 places on the run details page.
This PR also implements a error state for metrics error:
The change can be previewed from _my_ workspace.
=> Context menus on the run details page

sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/ReactFlowDag.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/common.ts, sematic/ui/packages/common/src/pages/RunDetails/dag/dagLayout.ts
1. Render the selected run node in the Dag view with thicker border.
2. Upon clicking a run node in the Dag view, jump to the run details for the selected node (switching away from dagview).
3. Dag view is still draggable.
=> Dagview selection

sematic/ui/packages/common/src/component/menu.tsx, sematic/ui/packages/common/src/layout/ThreeColumns.tsx, sematic/ui/packages/common/src/muitypes.d.ts, sematic/ui/packages/common/src/pages/RunDetails/MetaDataPane.tsx, sematic/ui/packages/common/src/pages/RunDetails/RunTreeSection.tsx, sematic/ui/packages/common/src/theme/new/palette.ts
The PR covers:
1. Add a background color (1% Black) to the side panels.
2. Hide the "building information", and "resolution logs" sections from the left side panel. (excluded from the first version of the new dashboard)
3. Hide the "metrics" menu item from the header bar. (excluded from the first version of the new dashboard)
Before:
After:
=> Add background color to side panels

sematic/ui/packages/common/src/context/SnackBarContext.ts, sematic/ui/packages/common/src/context/SnackBarProvider.tsx, sematic/ui/packages/common/src/hooks/pipelineSocketMonitorHooks.tsx, sematic/ui/packages/common/src/hooks/runHooks.ts, sematic/ui/packages/common/src/pages/PipelineList/LatestRunsColumn.tsx, sematic/ui/packages/common/src/pages/PipelineList/PipelineList.tsx, sematic/ui/packages/common/src/pages/PipelineRuns/index.tsx, sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx, sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx, sematic/ui/packages/main/src/pipelines/PipelineBar.tsx, sematic/ui/packages/main/src/pipelines/PipelineIndex.tsx, sematic/ui/packages/main/src/sockets.ts
This PR does the below:
1. When there is a new run or a run is canceled. Show the snack bar message.
2. When there is a pipeline/update message, refresh the pipeline list.
=> [New Dashboard] Hook up the notifications with snack message

sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx, sematic/ui/packages/common/src/pages/RunDetails/sourcecode/SourceCode.tsx, sematic/ui/packages/common/src/pages/RunDetails/sourcecode/index.tsx, sematic/ui/packages/main/src/components/SourceCode.tsx
=> Adapt source code panel to the new dashboard

README.md, README.rst, docs/changelog.md, helm/sematic-server/Chart.yaml, sematic/db/migrations/20230627153433_add_edges_run_indexes.sql, sematic/db/models/edge.py, sematic/db/schema.sql.sqlite, sematic/versions.py, sematic/wheel_constants.bzl
Only contains the contents of 0.31.0 and a migration to add two indexes to the `edges` table.  Fully tested.
=> Release 0.31.1

sematic/db/queries.py
This PR fixes a bug that sometimes runs would have the `function_path` column as "none", so when aggregated against the `function_path` column, we end up with a "none" key in the aggregated dictionary. This dictionary does not work with "flask.jsonify()".
=> Fixes a bug when function path is none

sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/common.ts, sematic/ui/packages/common/src/pages/RunDetails/dag/dagLayout.ts
This PR:
1. remove the round border of the handles, so there is no space between the handle and the box border
2. Align the center of the handle vertically with the box border.
Before:
After:
=> Align DAG node handles and remove border of the handles

sematic/ui/packages/common/src/component/GitInfo.tsx, sematic/ui/packages/common/src/component/Note.tsx, sematic/ui/packages/common/src/component/RunStateChips.tsx, sematic/ui/packages/common/src/component/RunsDropdown.tsx, sematic/ui/packages/common/src/component/menu.tsx, sematic/ui/packages/common/src/layout/TwoColumns.tsx, sematic/ui/packages/common/src/pages/PipelineList/LatestRunsColumn.tsx, sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx, sematic/ui/packages/common/src/pages/RunDetails/externalResource/index.tsx, sematic/ui/packages/common/src/pages/RunDetails/logs/LogsPane.tsx, sematic/ui/packages/common/src/pages/RunDetails/metricsTab/MetricsPane.tsx, sematic/ui/packages/common/src/pages/RunDetails/metricsTab/index.tsx, sematic/ui/packages/common/src/pages/RunDetails/pipelineMetrics/index.tsx, sematic/ui/packages/common/src/pages/RunDetails/podLifecycle/index.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/CollapseableFilterSection.tsx, sematic/ui/packages/common/src/pages/RunSearch/filters/StatusFilterSection.tsx, sematic/ui/packages/common/src/pages/RunTableCommon/RunListEmptyState.tsx, sematic/ui/packages/common/src/pages/RunTableCommon/filters/OwnersFilterSection.tsx, sematic/ui/packages/common/src/theme/new/palette.ts, sematic/ui/packages/common/src/typeViz/ArtifactVizTemplate.tsx, sematic/ui/packages/storybook/src/stories/Header.stories.tsx, sematic/ui/packages/storybook/src/stories/RunFilter.stories.tsx
This PR fixes the following defects:
1. Fixes a typo for the uncommitted changes tooltip.
2. Fixes the shading of the notes
3. Fixes the background of the run search result ( => white)
4. Fixes the background of the run search filters ( => %1 Black)
5. Add a link to the Docs header menu
6. Renamed "Support" header menu to "Discord" and provided a link as such.
7. Fixed the artifact menu too lose to the edge.
8. Fixes an issue that switching tabs on the Run Detail page might sometimes leave a lingering loading indicator. 
9. When rendering artifacts, prevents incorrect artifact payload crashes the rendering process and explodes the whole page. 
10. Fixes compile errors and broken pages in Storybook.
11. Fixes an issue that not having a logged-in user would cause the run search page to …
=> Some bug fixes for the new UI

sematic/cli/cli.py, sematic/examples/add/__main__.yaml, sematic/plugins/building/docker_builder_config.py, sematic/plugins/building/tests/test_docker_builder_config.py
If a docker image URI is surrounded in quotes, it can throw off the image pushing. This change ensures that we strip quotes if they're present. This PR also introduces two changes which were introduced to allow testing the change on a Mac:
- make sure that when a Sematic developer does `bazel run //sematic/cli:main`, it runs from the directory you ran that command from (basically as if you had actually executed the `sematic` cli).
- add a build yaml for the add pipeline
Testing
--------
`bazel run //sematic/cli:main -- run --build ./sematic/examples/add/__main__.py -- --cloud --detach`
[run](https://josh.dev-usw2-sematic0.sematic.cloud/runs/97dd47094bb34609961ae9a58fb53e3f#tab=output)
=> Make Docker image URI parsing more robust

sematic/ui/packages/common/src/hooks/runHooks.ts, sematic/ui/packages/common/src/pages/RunSearch/SearchFilters.tsx, sematic/ui/packages/common/src/pages/RunSearch/index.tsx, sematic/ui/packages/common/src/pages/RunTableCommon/filters/SearchTextSection.tsx, sematic/ui/packages/main/src/runs/RunIndex.tsx
This PR implements deep-linking the search term in the run list search page (new dashboard). It could avoid double fetching runs when the page is initially loaded and a search term is used in the URL. 
This is a follow-up after [PR 845](https://github.com/sematic-ai/sematic/pull/845)
=> Deeplink search term in new UI

sematic/ui/packages/common/src/typeViz/ArtifactVizTemplate.tsx
**Before:**
When the page is not wide enough, the "type" and "value" part of the artifact line will cluster together.
**After:**
If the page is wide enough, then:
When the page width is narrow, we get:
Note: "and some othere bla bla text" is merely a temporary test code to enlarge the size of the value part., it will not be part of the PR.
=> Fixes the clustering in the artifact headline

sematic/ui/packages/common/src/pages/RunDetails/artifacts/InputPane.tsx, sematic/ui/packages/common/src/pages/RunDetails/artifacts/OutputPane.tsx, sematic/ui/packages/common/src/pages/RunDetails/artifacts/artifact.tsx, sematic/ui/packages/common/src/typeViz/ArtifactVizTemplate.tsx, sematic/ui/packages/common/src/typeViz/common.tsx, sematic/ui/packages/common/src/typeViz/views/HuggingFaceReference.tsx, sematic/ui/packages/common/src/typeViz/views/HuggingFaceStoredModel.tsx
1. Fixes an issue that when the graph is updating, the artifact list always refreshes, despite no change
2. Fixes an issue that the Link type artifact cannot be rendered correctly. 
Before:
After:
3. Refactor the code of high-lightening the expanded artifact section. Now all nested artifact values will have the indentation indicator.
=> Fixes frequent updates on the artifact list

.circleci/config.yml
CI has been kind of flaky lately due to issues downloading third party libs in bazel. This adds retries around the places where that needs to happen so that it's not fatal for the CI pipeline.
=> Make CI more robust

sematic/ui/packages/common/src/component/RunsDropdown.tsx, sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/ReactFlowDag.tsx
1. Ensure the DAG view will not be over-zoomed during viewport initialization to prevent it from being too big. 
2. Ensure that the DAG node handles have the same color as the border of the nodes.
3. Ensure that DAG nodes should have pointer on mouse hover
4. Fixes a bug that the runs dropdown list does not update the state chip when the DAG is updated. 
Preview
=> Fixes DAG zoom issue

sematic/ui/packages/common/src/hooks/resolutionHooks.ts
Fixes a bug that a hook does not pick up the latest value of the parameters when sending request to backend.
=> Fixes a bug about rerun request parameter

.circleci/config.yml, .circleci/retry
It turns out [these docs](https://support.circleci.com/hc/en-us/articles/360043188514-How-to-Retry-a-Failed-Step-with-when-Attribute-) from Circle only tell you how to ensure a step gets tried again, but will NOT stop the overall job from failing. So this PR switches us to use a bash script to do retries.
=> Improve CI retry

sematic/ui/packages/common/src/component/Note.tsx, sematic/ui/packages/common/src/component/UserAvatar.tsx, sematic/ui/packages/common/src/component/UserMenu.tsx, sematic/ui/packages/common/src/component/menu.tsx, sematic/ui/packages/common/src/pages/RunDetails/NotesPane.tsx, sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx, sematic/ui/packages/common/src/pages/RunTableCommon/columnDefinition.tsx, sematic/ui/packages/common/src/pages/RunTableCommon/ownerColumn.tsx, sematic/ui/packages/common/src/utils/color.ts, sematic/ui/packages/common/src/utils/string.ts
Preview:
1. Style for the case when users have pre-defined profile images.
2. Style for the case when users do not have profile images pre-defined.
=> Display avatar alongside user names

sematic/plugins/publishing/slack.py, sematic/plugins/publishing/tests/test_slack.py
We changed the formatting of URL links to runs, but never updated the slack plugin to account for that. This PR does that.
Testing
-------
Launched a run on dev1 that I intentionally failed, confirmed that the new link posted in slack took me to the relevant run.
=> Fix Slack generated URL

sematic/config/config.py, sematic/db/migrate.py
Closes #934
Removes the DB password from the DB URL logged to the migration logs.
Testing
-------
Deployed with helm and looked at the logs from the migration pod. Got:
```
INFO:root:Running migrations on postgresql://josh:<REDACTED>@dev-usw2-sematic0.cjwke8fboxes.us-west-2.rds.amazonaws.com:5432/josh
INFO:root:Already applied 20220424062956_create_runs_table.sql
INFO:root:Already applied 20220514015440_create_artifacts_table.sql
...
```
Note that the logs actually contain the string `<REDACTED>` in the location shown above, that's not a post-hoc modification.
=> Redact full DB URL from migration logs

sematic/ui/packages/common/src/pages/PipelineRuns/PipelineInfoPane.tsx, sematic/ui/packages/common/src/pages/RunDetails/contextMenus/PipelineSectionMenu.tsx, sematic/ui/packages/common/src/pages/RunDetails/pipelineMetrics/BasicMetricsPanel.tsx, sematic/ui/packages/common/src/pages/RunDetails/pipelineMetrics/index.tsx
1. Fixes a bug that the "Metrics" menu item does not trigger page navigation if it is triggered from the Run Resolutions page. (It only worked on the run details page)
2. Changes the scrolling behavior of the pipeline metrics panel from full-page scrolling to scrolling from only within the center pane.
Before:
After:
=> Fixes broken metrics link

sematic/ui/packages/common/src/utils/FeatureFlagManager.ts, sematic/ui/packages/main/src/Home.tsx, sematic/ui/packages/main/src/components/PromotionBanner.tsx, sematic/ui/packages/main/src/components/Shell.tsx, sematic/ui/packages/main/src/components/SideBar.tsx, sematic/ui/packages/main/src/pipelines/PipelineRunView.tsx
Display a promotional banner in the old UI to encourage usage of the new dashboard.
Clicking the X button will opt out of seeing the banner. 
Preview:
=> Add promotion banner to switch to new dashboard in old UI

sematic/ui/packages/common/src/component/RunStateChips.tsx, sematic/ui/packages/common/src/component/RunStateText.tsx, sematic/ui/packages/common/src/component/RunTree.tsx, sematic/ui/packages/common/src/component/RunsDropdown.tsx, sematic/ui/packages/common/src/pages/PipelineList/LatestRunsColumn.tsx, sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx, sematic/ui/packages/common/src/pages/RunSearch/RunStatusColumn.tsx, sematic/ui/packages/common/src/pages/RunTableCommon/columnDefinition.tsx
Snapshots for the new icon for cloned runs:
1. Run details page 
2. Run list:
3. Graph:
=> Display cloned state icon for cloned runs

sematic/db/BUILD, sematic/db/migration_utils.py, sematic/db/migrations/20230706150252_pre_alembic_parity.py, sematic/db/migrations/20230712121255_add_organizations_associations.py, sematic/db/models/BUILD, sematic/db/models/artifact.py, sematic/db/models/mixins/BUILD, sematic/db/models/mixins/has_organization_mixin.py, sematic/db/models/resolution.py, sematic/db/models/run.py, sematic/db/schema.sql.sqlite, sematic/plugins/metrics_storage/sql/models/BUILD, sematic/plugins/metrics_storage/sql/models/metric_label.py
This is the second of a series of PRs that will introduce the capability of defining and managing user organizations. The previous PR in the chain is #915.
This PR propagates the associations between existing data models and the `organizations` model, without code propagations. The new foreign key columns remain `NULL`. These will start to be populated once the Resolution submission API will supply an Organization ID.
=> [2/N] Add Organizations associations

sematic/db/migrations/20230712121255_add_organizations_associations.py
A DB migration script has incorrect syntax for PostgreSQL.
=> Fix DB migration script for PostgreSQL

sematic/ui/packages/common/src/component/SettingsMenu.tsx, sematic/ui/packages/common/src/component/UserMenu.tsx, sematic/ui/packages/common/src/component/menu.tsx, sematic/ui/packages/main/src/components/SideBar.tsx
1. For local deployment, which does not have authentication enabled, instead of showing the user profile menu, show a "Settings" menu instead.
2. The settings menu has a minimized command list that only supports "switch UI" + "Privacy settings" menu items. Because "user API key" and "Sign out" isn't applicable for user-less deployments.
3. Also added a placeholder entry point on the old UI to switch to the new UI, instead of relying on the user profile menu to switch to the new UI because the user profile menu does not display for the local deployment without authentication enabled.  
4. The experience for deployments with authentication doesn't change.
Preview:
Closes #985 
Closes #986
=> Fixes an issue that local deployment cannot switch UI

sematic/api/endpoints/runs.py, sematic/api/endpoints/tests/test_runs.py
The Server API endpoint that fetches lists of Runs has a parameter that can restrict the payload content to a subset of fields, instead of returning the entire Run objects. This feature is currently restricted to only Run ids.
The enforcement only functions correctly when garbage collection parameters are specified, and does not function on the general case.
This PR corrects the behavior and adds a unit test for validation.
=> Enforce Runs fields selection

sematic/ui/packages/common/src/component/RunStateChips.tsx, sematic/ui/packages/common/src/layout/Shell.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx, sematic/ui/packages/common/src/theme/new/svgfilters.tsx
Applies a breathing style for running state icon on the DAG view. It is DAG view only for now.
Preview:
=> Breathing style for running state icon on the DAG view

sematic/examples/testing_pipeline/pipeline.py
The Testing Pipeline function that raises and retries takes a raising probability parameter that can be specified in the CLI. This parameter isn't actually passed to the func, instead always using the default value of `0.5`.
=> Propagate Testing Pipeline raise retry probability to func

sematic/ui/packages/common/src/component/RunReference.tsx, sematic/ui/packages/common/src/pages/RunDetails/contextMenus/FunctionSectionMenu.tsx, sematic/ui/packages/common/src/pages/RunDetails/contextMenus/RunSectionMenu.tsx, sematic/ui/packages/common/src/pages/RunDetails/dag/ReactFlowDag.tsx, sematic/ui/packages/common/src/pages/RunDetails/logs/LogsPane.tsx, sematic/ui/packages/common/src/pages/RunDetails/podLifecycle/PodLifecycle.tsx
Fixes the following bugs:
Fixes #988 : Url hashes are now preserved
Fixes #990 : The allowed max zoom level is now increased. But the autofit zoom level is still clamped to ensure the text is visible.
The following picture showcases the maximum allowed zoom level. 
Fixes #993 : Logs will start streaming whenever the state shifted from "CREATED" or "SCHEDULED". But if the run does not provide logs initially during the first pull, it is still up to the user to manually pull the logs.
Fixes #994: The menu item labels are renamed to "start from scratch" and "start from here".
Fixes #996: Disclaimer will show up regardless of whether there is pod history.
=> Miscellaneous UI bug fixes

sematic/examples/summarization_finetune/requirements.txt, sematic/examples/summarization_finetune/train_eval.py
It turns out that some library versions that have been released since this was created have broken some functionality. This pins the libs to working versions. There was also a bug introduced in the gradio refactor that made the prompt get truncated to only the first character. This fixes that.
=> Fix a bug and pin libs for fine-tuning

sematic/plugins/building/docker_builder.py
Fixes #995.
If the local name chosen when producing an image collides with a public Dockerhub repo, then building the image will result in an error:
```bash
$ sematic run --log-level debug --build advanced/main.py -- /advanced/data/message.txt
[...]
2023-07-14 04:54:10,978  [INFO] sematic.plugins.building.docker_builder: Building image 'advanced:default_example_docker_advanced' starting from base: example_docker:default_advanced
Step 1/8 : FROM example_docker:default_advanced
2023-07-14 04:54:21,929  [ERROR] sematic.plugins.building.docker_builder: Image build error details: '{'message': "pull access denied for example_docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}'
File …
```
=> Avoid Docker Build name collision with public repos

docs/container-images.md, sematic/cli/run.py, sematic/plugins/abstract_builder.py, sematic/plugins/building/docker_builder.py, sematic/plugins/building/tests/test_docker_builder.py
The Docker Build System uses layer caching, which can result in older versions of libraries being used instead of the new ones. After a new version of Sematic is released, this can result in incompatibilities between the client bundled in an older pipeline image layer, and the backend Server:
Client:
```bash
$ sematic version
Sematic server v0.32.0 is installed.
Client versions >= v0.30.0 are supported.
Python v3.8.14 is running this binary.
$ sematic run --build intermediate/main.py -- /intermediate/data/message.txt
[...]
2023-07-19 06:27:56,503  [INFO] sematic.plugins.building.docker_builder: Launching target: 'intermediate/main.py'
41c30e6ae8904535ba0a28c8944321d0
Built and launched 'intermediate/main.py' in 24.77s
```
Server:
```bash
$ kubectl exec -it …
```
=> Docker Build provide no-cache option

sematic/api/endpoints/request_parameters.py, sematic/api/endpoints/tests/test_runs.py, sematic/db/models/BUILD, sematic/db/models/run.py
First an ORM model has to define a [`relationship()`](https://docs.sqlalchemy.org/en/20/orm/relationship_api.html) field,
then we can construct queries using {"field.relationship_field": {"eq": "value"}} filters
=> Support filter runs using a relationship model field

sematic/ee/tests/test_metrics.py, sematic/future_context.py, sematic/plugins/abstract_external_resource.py, sematic/plugins/external_resource/timed_message.py, sematic/resolvers/tests/test_worker.py, sematic/resolvers/worker.py, sematic/runners/cloud_runner.py, sematic/runners/silent_runner.py, sematic/runners/tests/test_silent_runner.py
Currently, if a user tries to create a Ray cluster from a non-standalone (aka inline) function, the message they get in the UI is something like "can't create manifest for Ray cluster." the server logs have more detail, showing a failure of the assert: `assert image_uri is not None  # please mypy`, which still leaves them very little information about what's going on. This PR changes it such that the message they get in the UI will be:
`sematic.utils.exceptions.ExternalResourceError: Could not activate resource with id 2b03efcfd1214d1480539151e3355818: RayCluster must be activated from a standalone function`. Furthermore, this kind of error message will be shown for other external resources that have a similar restriction that their cloud variants must use a standalone func (which is …
=> Better error message for Ray cluster from non-standalone function

.circleci/retry
CI sometimes still fails with too many consecutive retries for the ephemeral issues of downloading dependencies during pre-build. This PR increases the delay between tries so we give more time for the issue to resolve itself before trying again.
=> Extend retry delay

sematic/api/endpoints/resolutions.py, sematic/api/endpoints/tests/test_resolutions.py, sematic/db/models/factories.py, sematic/db/models/tests/test_factories.py, sematic/db/tests/BUILD, sematic/db/tests/fixtures.py, sematic/examples/testing_pipeline/__main__.py, sematic/examples/testing_pipeline/pipeline.py
This PR add the ability to trigger a Pipeline rerun in the Server API with Artifact ID overrides for the root Run Function's input parameters. This results in the new Pipeline Run effectively executing on new input data.
The rationale is to support a scenario in which rapid bootstrapping of cloud Pipeline runs are necessary on different inputs. The same Worker container can be reused, without re-building it for each execution. The submitter would have to ensure the desired Artifacts exist in Sematic's database in order to specify an override.
There exist 2 API endpoints that trigger reruns: one which requires the Pipeline Run to already exist (used by the Runner), and one which does not (used by the Dashboard). This PR enhances only the latter one with this capability, as the desired …
=> API capability of rerunning Pipelines with different Artifacts

sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
The moment when the "useRef" would be filled is unpredictable under certain scenarios. So this change aims to re-render until the reference become available before passing to the child component. 
A similar approach pre-existed in https://github.com/sematic-ai/sematic/blob/25e92ffba2f61a9bb679963a8ec6b4f087b3fb8c/sematic/ui/packages/common/src/pages/RunDetails/artifacts/artifact.tsx#L52-L59
Fixes #1035
=> Fixe a bug that could cause context menu missing.

sematic/BUILD, sematic/db/models/BUILD, sematic/db/models/factories.py, sematic/db/models/tests/test_factories.py, sematic/db/tests/BUILD, sematic/examples/add/pipeline.py, sematic/graph.py, sematic/resolvers/BUILD, sematic/resolvers/worker.py, sematic/runners/cloud_runner.py, sematic/runners/local_runner.py, sematic/runners/tests/test_cloud_runner.py, sematic/tests/test_graph.py
The cloud runner is sometimes restarted unexpectedly by K8s. Prior to this PR, this was handled by starting an entirely new pipeline run, with a new id, starting where the old one left off. This PR changes the behavior such that the runner is instead able to re-create its internal state and continue from where it left off. This (unlike the previous behavior) should be transparent to end-users.
Testing
-------
Disabled the signal handlers in the StateMachineRunner, so it wouldn't interpret `kubectl delete pod ...` as cancellations, then performed the following tests, using `kubectl delete pod` on the runner pod to emulate evictions:
- With an entirely inline graph, interrupted mid-execution. [Run](https://josh.dev-usw2-sematic0.sematic.cloud/runs/390bf91a57524b38acff77df6265fce7#run=e6d3cc3 …
=> Make runner reentrant

sematic/ui/packages/common/src/pages/RunDetails/logs/LogsPane.tsx
In the new log view UI, it was waiting to present the logs for a run until the run reached a state where the logs would be available. However, while logs appear during the `SCHEDULED` state, while the run is executing, the UI considered this to be a state where logs were not available. The effect was that the logs for a run would not show up until after the run completed. This regression appeared in v0.34.0. This PR fixes the regression.
Testing
-------
Submitted the testing pipeline including a "sleep" step, and observed that the logs for the step were shown during the execution of the run.
=> Fix log view regression

sematic/types/types/list.py, sematic/types/types/set.py, sematic/types/types/tests/BUILD, sematic/types/types/tests/test_set.py
`List` and `Set` were doing a comparison in their `can_cast_type` functions that assumed the `List[T]` variant of the type was being used instead of the `list[T]` variant. This PR makes the check compatible with both of these variants. It also adds a unit test for the `Set` type, which had been missing.
=> Improve <3.9 type-checking for list/set

sematic/api_client.py, sematic/cli/BUILD, sematic/cli/version.py, sematic/tests/fixtures.py, sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx
The `sematic version` CLI was a bit misleading, as it checked the client's version and called it the server version. This PR changes it so that both the client and the server version are reported, along with the min version from the actual server.
Testing
-------
```
$ sematic version
Sematic client v0.34.0 is installed.
The server is at version v0.34.0
Client versions >= v0.30.0 are supported.
Python v3.8.15 is running this binary.
```
And with an unsupported server/client combo:
```
$ sematic version
Sematic client v0.34.0 is installed.
The Sematic API client is at version 0.34.0, which is newer than the Sematic server's version of 0.33.0. Please downgrade your client to 0.33.0, or ask your server admin to upgrade to at least 0.34.0.
```
=> Improve `sematic version` CLI

docs/deploy.md
The deploy docs didn't take you "all the way" to actually running something against your new deployment. This PR improves that.
=> Improve example refs in deploy docs

sematic/api_client.py, sematic/runners/local_runner.py
If `save_graph` is consistently resulting in error, it can take an unpleasant number of attempts to get the program to finally exit. This is because there is an attempt to save the graph during run failure handling, pipeline run (i.e. resolution) run handling, and cancellation run handling. This PR does two things to address this:
(1) Don't retry `save_graph` when performing cleanup operations, to encourage a quick and clean exit
(2) During cleanup operations, only save the runs, which reduces chances that problems with artifact/edge saves prevent the run state from getting updated.
WRT the latter, artifacts in particular have an extra risk of failure compared to runs; their "json summaries" can be too large, which can cause the graph save attempt to be rejected.
Testing
--------
Ran …
=> Reduce chances of excessive retry

sematic/examples/testing_pipeline/__main__.py, sematic/examples/testing_pipeline/pipeline.py
Adds a string parameter to the Testing Pipeline so that it can be used with a string parameter.
```bash
$ bazel run //sematic/examples/testing_pipeline:__main__ -- --cloud --detach --count-letters hello!
```
=> Add string parameter to Testing Pipeline

sematic/cli/cancel.py
The CLI for `cancel` was currently always using the local user env (since that is the default for CLI commands). But really we want it to communicate with whatever API the user's config is set up to talk to.
Testing
-------
Made sure my Sematic config was pointing to a remote server and used this command. Ensured it used the remote server to complete the request.
=> Have the cancel CLI use the API from the config

sematic/api_client.py, sematic/tests/BUILD, sematic/tests/test_api_client.py
If you called `api_client.get_runs()`, it would result in errors, despite claiming that all the fields were optional. In practice, we hadn't been calling the API this way, but this PR fixes it to make it more robust and adds a test.
=> Make run retrieval API more robust

sematic/api/endpoints/request_parameters.py, sematic/api/server.py, sematic/logs.py
There were a couple of situations where it would be helpful to have errors logged in the server logs, but that wasn't happening. Basically (1) anything that was going uncaught was relying on the `uvicorn.*` logger to get logged, whereas we want it to be handled by the `sematic.*` logger as well, (2) any time we were explicitly returning a json error response, we wouldn't log anything to the server logs unless the particular code calling `jsonify_error` had already logged the exception. This PR addresses both of these.
Testing
--------
Ran the local server and intentionally injected exceptions, both uncaught ones and ones that resulted in a `jsonify_error`. Made sure the exceptions made it to the local server logs. Then did the same thing with code deployed to my namespace.
=> Have the server log more errors & warnings

docs/cli.md, helm/sematic-server/templates/configmap.yaml, helm/sematic-server/values.yaml, sematic/config/server_settings.py, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_kubernetes.py
In some cases, runner and standalone pods may need to pull their images from a private registry that isn't automatically accessible on the basis of the service accounts already associated with the pod. This PR makes it possible to specify custom image pull secrets for these pods.
Testing
-------
Deployed to my namespace and tested with and without configuring `worker.image_pull_secrets`. Confirmed that the pods got created with the proper configuration for their imagePullSecrets.
=> Allow custom image pull secrets

sematic/types/serialization.py, sematic/types/tests/BUILD, sematic/types/tests/test_serialization.py
The code for checking whether a type in `serialization.py` would fail if given `_is_dataclass(Union)`, because `Union` has no `__dict__`. This change fixes it. Note that if you use a bare `Union` in a function type annotation, you still get the following:
```
TypeError: Invalid type annotation for argument 'x' of sematic.tests.test_function.f: typing.Union must be parametrized (typing.Union[...] instead of typing.Union).
```
=> Fix serialization dataclass check

sematic/api_client.py, sematic/cli/version.py
When the Server is unreachable:
```
$ sematic version
Sematic client v0.34.1 is installed.
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
$ sematic settings set SEMATIC_API_ADDRESS <address>
WARNING:sematic.utils.retry:Retrying request in 1 seconds with 6 tries left...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
$ sematic settings set SEMATIC_API_ADDRESS <address>
WARNING:sematic.utils.retry:Retrying request in 2.1 seconds with 5 tries left...
WARNING:sematic.utils.retry:Unable to connect to the Sematic API at http://127.0.0.1:5001.
Make sure the correct server address is set with
$ sematic settings set …
```
=> Fix error in version CLI command when Server unreachable

.circleci/config.yml, docs/upgrades.md, helm/sematic-server/templates/configmap.yaml, helm/sematic-server/templates/deployment.yaml, helm/sematic-server/templates/ingress.yaml, helm/sematic-server/templates/pdb.yaml, helm/sematic-server/templates/service.yaml, helm/sematic-server/templates/socketio_deployment.yaml, helm/sematic-server/templates/socketio_service.yaml, helm/sematic-server/values.yaml, requirements/requirements.in
You actually get errors connecting to socketio if you don't use a dedicated socketio. So the default setting is broken. This PR makes it so that this is no longer configurable, and you must have a dedicated socketio server. It also changes the default value for whether to create a service to `true`, which is the more appropriate value (that is another place where a vanilla install would fail to work as expected).
Tested by deleting the staging deployment, removing the configs for the standalone SocketIO server and the service creation from the staging deployment's chart, and installed the deployment to staging again.
=> Remove configurability for dedicated socket io

sematic/ui/packages/common/src/component/SettingsMenu.tsx, sematic/ui/packages/main/src/components/PromotionBanner.tsx, sematic/ui/packages/main/src/components/SideBar.tsx, sematic/ui/packages/main/src/index.tsx, sematic/ui/packages/tests/e2e/main.cy.ts
The new dashboard has been vetted well enough that we can change the default behavior to be using the new UI. We still likely want to keep the old one around for a few more releases in case this change surfaces new users that haven't tried the dashboard and run into problems. If that happens, we can fix their issues and let them manually switch back to the old one as a mitigation.
Testing
--------
Cleared my local storage, rebuilt & started the app, and refreshed my page. Confirmed it used the new UI. Used the toggles to switch between the new and old UIs and confirmed that they still toggle.
=> Change the default to be usage of the new UI

sematic/ui/packages/common/src/pages/Home/index.tsx
Recently, after user feedback, the "Pipelines" and "Runs" buttons were switched in the Dashboard header. But on the homepage, the 2 "Pipelines" and "Runs" panels were kept in the same order.
Now when viewing the homepage, this creates an unpleasant experience.
This PR switches the 2 panels as well.
Before:
After:
=> Switch runs and pipelines panels

README.md
Link to the developer guide from the main readme, so contributors can more easily find info on how to set up their dev environment.
=> Link dev guide from main readme

developer-docs/README.md, docs/api.md, docs/cli.md, docs/cloud-runner.md, helm/sematic-server/templates/configmap.yaml, helm/sematic-server/values.yaml, sematic/__init__.py, sematic/config/server_settings.py, sematic/examples/testing_pipeline/__main__.py, sematic/examples/testing_pipeline/pipeline.py, sematic/examples/testing_pipeline/requirements.txt, sematic/resolvers/resource_requirements.py, sematic/resolvers/tests/test_resource_requirements.py, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_kubernetes.py
Introduces the capability of mounting paths from the underlying node filesystem into the Worker pod.
This is added as a new `ResourceRequirements` parameter.
The documentation is updated to cover the new capability, and to cover other missing capabilities.
The unit tests are updated to cover the new functionality:
```
$ bazel test //sematic/scheduling/tests:test_kubernetes
$ bazel test //sematic/resolvers/tests:test_resource_requirements
```
The Testing Pipeline is enhanced with a new parameter to test mounting paths, and writing to and reading from them inside the Worker pods. The existing `ResourceRequirements` testing, which only covered shared memory mount expansion, is also refactored, and enhanced to check its effects.
```
$ bazel run //sematic/examples/testing_pipeline:__main__ -- …
```
=> Capability of mounting underlying node paths in the pod

sematic/examples/cifar_classifier/requirements.txt
The latest versions of the dependencies for this example don't work. Freezing them at versions that do.
Testing
--------
```
pip install -r sematic/examples/cifar_classifier/requirements.txt
sematic run sematic/examples/cifar_classifier/main.py
sematic run --build sematic/examples/cifar_classifier/main.py -- --cloud
```
=> Update requirements on CIFAR classifier

helm/sematic-server/templates/deployment.yaml
currently, pods in the sematic server deployment don't restart when the configmap associated with them changes.  on every helm upgrade, helm _does_ rerun the migration pod with the updated configmap values, but the deployment pods themselves stick around unchanged.  this is a known issue in k8s: https://github.com/kubernetes/kubernetes/issues/22368
to remove any confusion here, we take a checksum of all of the values in the helm chart and apply the checksum as an annotation on the pods.  with this, k8s will forcibly refresh the pods on _any_ change to the helm values.  while that is a bit of overkill (not all changes technically require the pods to restart), it is far less error-prone than the status quo.
also documented as a helm tip here: …
=> Force pod restarts on config map changes

sematic/runners/state_machine_runner.py, sematic/runners/tests/test_silent_runner.py
There was a bug that if two runs timed out at the same exact time (ex: parallel runs launched simultaneously), the comparison logic would fall back to comparing `Future` objects directly, which don't support the `<` operator. This switches so that in such cases we fall back to comparing the ids instead of the Future objects.
=> Fix edge-case in timeout comparisons

sematic/api_client.py
closes #1089 
When doing a `PUT` to write artifact data, we are currently not raising an error directly. Likely an error will still occur when something downstream tries to *use* the artifact data (unless it's the last artifact in a pipeline...), but we should fail more explicitly when the error first occurs.
=> Fail more loudly if artifact data writes are not successful

sematic/api/endpoints/auth.py, sematic/api/endpoints/tests/test_auth.py
Closes #1093
Google only sets the`hd` claim on an id token [under certain circumstances](https://developers.google.com/identity/openid-connect/openid-connect). If it's not set, we should consider the user's email domain to be whatever comes after the `@` in their email address.
=> If user token has no hd, use email address domain

docs/api.md, sematic/db/migrations/20231115163910_runner_resources.sql, sematic/db/models/factories.py, sematic/db/models/resolution.py, sematic/db/schema.sql.sqlite, sematic/examples/testing_pipeline/__main__.py, sematic/resolvers/resource_requirements.py, sematic/runners/cloud_runner.py, sematic/runners/local_runner.py, sematic/runners/tests/test_cloud_runner.py, sematic/scheduling/job_scheduler.py, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_job_scheduler.py
Closes #1095
Until now, runner pods could only use fixed resource requirements. We had to pick a value that was big enough to not OOM in the vast majority of cases while also not being wasteful in what was requested. This led to a few limitations:
1. Not all runner pods had equal compute needs (inline runs might require more or less memory, importing large libs might increase memory near the limit for some workloads, etc.)
2. Anything requiring a secret could not be executed inline. Note that inline (aka non-standalone) stuff should STILL be only used for lightweight tasks, these do sometimes require secrets (ex: a func which makes just one quick API call)
3. It wasn't possible to pursue cluster resource efficiency/reliability goals by putting runner pods on non-pre-emptible nodes or …
=> Alow custom resources for runner pods

helm/sematic-server/templates/cleaner-cron.yaml, sematic/api/endpoints/resolutions.py, sematic/api/endpoints/tests/test_resolutions.py, sematic/api_client.py, sematic/cli/clean.py, sematic/cli/tests/test_clean.py, sematic/db/models/resolution.py, sematic/db/queries.py, sematic/db/tests/test_queries.py, sematic/scheduling/job_scheduler.py, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_job_scheduler.py
Closes #1088 
We have observed that this can happen if, for example, the runner pod OOM'd. We don't want the Sematic dashboard to show such things as still active when they're really not.
Additionally, the runner jobs weren't really getting their statuses updated except when they were created and when they were killed. I added some intermediate updates by having the jobs get updated whenever the resolution object is saved.
Finally, there are cases where the runner job looked like it might just be pending on k8s, and that was getting confused as still being active. To catch cases like this, I added logic that if a job still hasn't been started (which for run jobs is as soon as k8s acknowledges them, and for resolution jobs as soon as the runner pod updates the resolution status at its …
=> Have the cleaner cover cases where the runner pod is dead but Sematic's DB doesn't see that

sematic/plugins/kuberay_wrapper/standard.py, sematic/plugins/kuberay_wrapper/tests/test_standard.py
Closes #1090 
The current version parsing logic wasn't robust to non `.`/numeric characters in the version string. This is.
=> Make version parsing more robust for Kuberay

sematic/future.py, sematic/tests/test_future.py
Addressed #87 
Fail while doing `__eq__`, `__gt__`, `__ge__`, `__lt__` and `__le__` operations on `Future`.
=> Fail while doing __eq__ (and other comparison) on Future

sematic/ui/packages/common/src/pages/RunDetails/FunctionSection.tsx
Fixes this incorrect rendering:
=> Fix completion date rendering

sematic/log_reader.py, sematic/tests/test_log_reader.py
We write log chunks to cloud storage every ~10 seconds, but we SKIP writing a log file if there were no log lines produced in that time period. When we request logs from the dashboard, we request them with a limit for the number of lines (2000). We will traverse the files in storage until we get to 2000 lines, so long as there are more files available for traversal. If your logging is dense, you will get to 2k lines quickly. If your logging is sparse in the sense that you only get messages every few minutes, but when those messages do show up there are at least several lines, then you get to 2k lines fairly quickly. The worst case scenario for how many remote log files you must traverse is if your logging produces a small number of lines every several seconds (absolute worst case would be …
=> More responsive log reading

sematic/ui/packages/common/src/typeViz/common.tsx
After the fix, we will be able to render WorkloadConfig
Example:
=> Fixes an issue related to artifact rendering

sematic/resolvers/BUILD, sematic/runners/cloud_runner.py, sematic/runners/state_machine_runner.py
Closes #1114 
K8s sometimes needs to move pods from one node to another. When this occurs, it first gives the pod a sigterm to allow it to stop gracefully. It will force kill if the pod doesn't stop within a grace period. The cloud runner calls the Sematic API to mark itself as canceled when this occurs, but the correct behavior should be that it just exits the process and picks up where it left off once it is rescheduled. This ability to pick up where it left off is already supported. The part that needs to be changed is that we should not call the "mark canceled" API.
You might ask: if we don't mark the runner as canceled when it gets a sigterm, aren't we susceptible to the Sematic metadata showing it as still running when the pod is terminated and NOT rescheduled? The answer is that …
=> Stop CloudRunner from calling "cancel" API when it receives sigterm

sematic/runners/local_runner.py, sematic/runners/state_machine_runner.py
Closes #1120
In certain cases, Sematic could get "stuck" waiting for something on one branch of a pipeline when more work could be done in other branches. This PR makes it so that Sematic will avoid entering a wait until changes are no longer being made to the pipeline state. Essentially the bug was that it can take a few iterations through the state-evolution loop before all the changes have taken effect that allow us to know it's OK to schedule a particular run. The fix was to look at whether the state-evolution loop resulted in anything in the pipeline changing state. And if it did, don't enter the wait.
Testing
-------
Set up a pipeline that I knew would hit a condition that would wait prematurely before the fix. The sleep in the left branch of the image takes seconds, while the …
=> Improve parallelism for deeply nested parallel branches

docs/api.md, helm/sematic-server/templates/configmap.yaml, helm/sematic-server/values.yaml, sematic/config/server_settings.py, sematic/examples/testing_pipeline/__main__.py, sematic/examples/testing_pipeline/pipeline.py, sematic/resolvers/resource_requirements.py, sematic/scheduling/kubernetes.py, sematic/scheduling/tests/test_kubernetes.py
Allow annotations and labels to be specified in `KubernetesResourceRequirements` IF they have been allow-listed using a server config. The reason we need to have an allow-list is that allowing the user to arbitrarily specify annotations and labels can contain foot-guns (ex: a user specifying a label of `sematic.ai/component: api` might wind up having their pod be considered part of the Sematic k8s service object). In the worst case, they can contain security holes (ex: an annotation of  `kubernetes.io/psp: eks.privileged`).
Testing
-------
Deployed a server with this code to staging. Then:
- re-ran an old pipeline execution from the UI to confirm it still worked.
- Ran the testing pipeline with custom runner resources and confirmed that the specified annotations and labels appeared …
=> Allow custom annotations & labels

sematic/db/migrate.py, sematic/db/migrations/20220930014400_migrate_exception_data.py, sematic/db/tests/test_migrate.py
One of the changes in SQLAlchemy from 1.4.X -> 2.X is that they've removed automatic commits for DDL/DML statements fed into `Connection`s created from `Engine.connect()`. This leads to a few minor bugs in the DB migration code post `0.39.0` release (and the SQLAlchemy 2.X migration in #1127).
This PR fixes those bugs by using `Connection`s created by `Engine.begin()` instead
```bash
$ bazel run sematic/db/tests:test_migrate
```
+ manual testing in a repo that's using Sematic as a dependency
=> Use Engine.begin() instead of Engine.connect() to ensure DML/DDL statements are committed in migration code

helm/sematic-server/templates/configmap.yaml, helm/sematic-server/values.yaml, sematic/plugins/kuberay_wrapper/standard.py, sematic/plugins/kuberay_wrapper/tests/test_standard.py
Some k8s infrastructure may require custom annotations and/or labels to be applied to pods in the cluster (ex: custom autoscalers). Sematic already supports control over this for runner and standalone job pods, but doesn't for pods created via the Ray integration. This PR adds that support. The integration works by adding helm-configurable annotations and labels. The integration works by allowing you to specify annotations or labels to apply to ALL pods created by Sematic's ray integration. You can specify different configurations for pods with/without GPUs but otherwise the configurations must be universal. These configurations must be specified at the helm level, and NOT by pipeline authors.
Testing
-------
In addition to the unit test, manually applied a Ray cluster yaml created with …
=> Support custom annotations for Ray pods

sematic/types/types/tests/test_tuple.py, sematic/types/types/tuple.py
Apparently `tuple` was missing an implementation for `can_cast_type`. It likely went unnoticed because `can_cast` has a quick check to return `True` if the source and destination types are the same python object (`a is b` check), which would work for most cases. But for other cases you might want it to work, the implementation was missing & causing problems. This PR adds an implementation.
=> Add can_cast for tuple

.github/workflows/test.yaml
These are the CI steps for the following two items:
- nodejs lint
- nodejs unit tests using Cypress component testing
The Cypress e2e test is not yet included in this PR.
1. The Cypress e2e test will have to mobilize headless browser engines, which requires several graphics libraries to be installed to the system. So we have two options for preparing the environment: 
A: use the default ubuntu distribution and install those graphic libraries or
B: use the Cypress officially prepared docker image and install other toolchains (eg. make) as needed. 
For the sake of increasing the likelihood of running Cypress test suite successfully, I chose the latter. 
2. In order to reuse the installed Cypress executables (installed through `npm install`) I decided to cache the Cypress installation cache. …
=> CI work for nodejs part

.github/workflows/test.yaml
Now the GH action CI should be complete with the Cypress e2e.
=> Add Cypress e2e Integration test in the GH action CI
