Dockerfile
Makefile
sematic/BUILD
sematic/api/endpoints/BUILD
sematic/api/endpoints/notes.py
sematic/api/endpoints/request_parameters.py
sematic/api/endpoints/runs.py
sematic/api/server.py
sematic/api_client.py
sematic/cli/cli.py
sematic/config.py
sematic/config_dir.py
sematic/db/migrate.py
sematic/db/models/factories.py
sematic/db/models/json_encodable_mixin.py
sematic/db/models/run.py
sematic/db/models/tests/test_run.py
sematic/db/queries.py
sematic/db/tests/test_queries.py
sematic/resolvers/BUILD
sematic/resolvers/local_resolver.py
sematic/resolvers/tests/test_local_resolver.py
sematic/tests/test_user_settings.py
sematic/user_settings.py

This is necessary to write to a cloud-hosted API server

Save graph via the API instead of directly to the DB

---

.bazelrc
README.md
sematic/db/migrations/20220726001230_add_exception_to_runs_table.sql
sematic/db/models/run.py
sematic/db/schema.sql.sqlite
sematic/examples/bazel/pipeline.py
sematic/resolvers/cloud_resolver.py
sematic/resolvers/local_resolver.py
sematic/resolvers/state_machine_resolver.py
sematic/resolvers/tests/BUILD
sematic/resolvers/tests/test_local_resolver.py
sematic/resolvers/tests/test_worker.py
sematic/resolvers/worker.py
sematic/ui/src/Models.tsx
sematic/ui/src/components/DagTab.tsx

This PR makes sure that when runs fail, the stack trace is captured and persisted in the DB. It is then displayed in the Logs tab in the UI.

Persist stack traces and display in UI

---

docs/README.md
docs/sematic-vs.md

Correct a couple things on our comparison page, and add more comparisons that will likely come up.

Sematic vs updates

---

docs/SUMMARY.md
docs/sematic-vs.md

some of the "Sematic vs ..." entries didn't have the leading "..."

Add missing ellipsis

---

sematic/ui/src/components/Notes.tsx
sematic/ui/src/components/NotesPanel.tsx
sematic/ui/src/components/PipelineBar.tsx
sematic/ui/src/index.tsx
sematic/ui/src/pipelines/PipelineView.tsx

Addresses https://github.com/sematic-ai/sematic/issues/74
The URL now contains the ID of the root run.

Root run deep linking

---

sematic/api/server.py

The access.log and error.log only contained log messages which were generated by Gunicorn. Even when there was an exception, there was nothing in the logs but a record of the 500. This makes it so that we still get Gunicorn logs, but we also get logs from our `logger.info("blah")` statements and the like.

Make it so we actually get log messages from loggers

---

docs/changelog.md
docs/deploy.md
sematic/versions.py
sematic/wheel_version.bzl

Release v0.12.0

---

docs/changelog.md
sematic/__init__.py
sematic/calculator.py
sematic/resolvers/cloud_resolver.py
sematic/resolvers/resource_requirements.py
sematic/resolvers/tests/BUILD
sematic/resolvers/tests/test_cloud_resolver.py
sematic/tests/test_calculator.py

We don't have great ways to inject secrets into containers right now, this is something basic to get things started.

Support k8s secrets mount

---

docs/get-started.md

People have asked about Windows, let's make it explicit that it's not supported.

List supported platforms

---

docs/container-images.md
docs/execution-modes.md

There are some common confusions around what's going on with `inline`, as well as what to do about lightweight steps and container images. This PR beefs up the docs to address these.

Better docs on inline stuff

---

.gitignore

Add a `.gitignore` entry for The Intellij IDEA IDE local config files.

Add Intellij IDEA files to .gitignore

---

Makefile
developer-docs/README.md
docs/contribute-example.md
docs/developers/guidelines.md

Updates the contribute and dev docs with dev env setup instructions, in order to provide devs with a little smoother experience.

Update contributing docs with dev env setup instructions.

---

sematic/ui/src/components/GitInfo.tsx
sematic/ui/src/components/PipelineBar.tsx

Regular font, better alignment and sizing.

Fine-tuning git info design

---

docs/changelog.md
helm/sematic/values.yaml
sematic/versions.py
sematic/wheel_version.bzl

Bump versions for 0.17.0

---

sematic/ui/src/components/PipelineBar.tsx

Fix cancel button upon completion

---

docs/deploy.md

Document upgrade process

---

docs/changelog.md
helm/sematic/values.yaml
sematic/versions.py
sematic/wheel_version.bzl

Bump versions for 0.17.1

---

sematic/utils/git.py

This is an addendum to #226.
It correctly fixes that bug

Correct fix GitInfo for custom Bazel workspaces

---

docs/changelog.md
helm/sematic/values.yaml
sematic/versions.py
sematic/wheel_version.bzl

Bump versions for 0.17.2

---

README.md
README.rst
developer-docs/README.md
requirements/ci-requirements.txt

Update the release procedure developer docs with missing info and new additions.

Update the release procedure developer docs

---

docs/changelog.md
helm/sematic/values.yaml
sematic/versions.py
sematic/wheel_version.bzl

release 0.18.1

---

developer-docs/README.md

Updates the developer documentation to mention what kinds of tests should be made for changes that potentially impact pipeline resolution.

Doc update with resolution testing instructions

---

docs/changelog.md
helm/sematic/values.yaml
sematic/versions.py
sematic/wheel_version.bzl

Bump versions to release v0.19.0

Bump versions for 0.19.0

---

docs/SUMMARY.md
docs/bigquery.md
docs/dataflow.md
docs/dbt.md
docs/integrations.md
docs/redshift.md
docs/slack.md

Fixes dead links in the public-facing documentation.

Fix dead links in the documentation

---

docs/contributor-guide.md

Improves the public-facing documentation with the list of GitHub "good first issues", so that users have more resources available to become contributors.

Update contributing guide with good first issues

---

docs/changelog.md
sematic/tests/test_versions.py

Adds links to the PyPi releases for each entry in the changelog.

Add PyPi links to the changelog

---

docs/changelog.md
helm/sematic/values.yaml
sematic/versions.py
sematic/wheel_version.bzl

Bumps versions for the 0.19.1 release.

Bump versions for 0.19.1

---

docs/changelog.md
helm/sematic/values.yaml
sematic/versions.py
sematic/wheel_version.bzl

Bumps versions for the 0.19.2 release.

Bump versions for 0.19.2

---

sematic/db/migrations/20220610234559_create_notes_table.sql
sematic/db/migrations/20220930014400_migrate_exception_data.py

Fixes various bugs in the migration scripts.

Fix various migration script issues

---

sematic/graph.py
sematic/tests/test_graph.py

The source code on the `main` branch does not correspond to the linter's standards.

Lint the source code on main

---

docs/changelog.md
helm/sematic/values.yaml
sematic/versions.py
sematic/wheel_version.bzl

Bumps versions for the 0.20.0 release.

Bump versions for 0.20.0

---

sematic/ui/package-lock.json

Updates the package lock file to reflect the most recent changes to the dependencies.

Update UI package versions

---

sematic/ui/src/components/MenuPanel.tsx
sematic/ui/src/components/PipelinePanels.tsx
sematic/ui/src/components/ReactFlowDag.tsx
sematic/ui/src/components/RunPanel.tsx
sematic/ui/src/components/RunTree.tsx
sematic/ui/src/components/graph/graphContext.ts
sematic/ui/src/hooks/graphHooks.ts
sematic/ui/src/interfaces/graph.ts
sematic/ui/src/pipelines/RunDetailsPanel.tsx

Elevates and centralizes the graph handling processes, by having `GraphContext`.
1. `GraphContext` handles graph loading and updates from the socket automatically.
2. `runsById` and `artifactById` are created by default with the graph loading. 
3. `runsTree` is created on demand using `useRunsTree()` hook
4. Separated GraphPanel(FlowWithProvider) and RunDetailsPanel from RunPanel.

[2/2] Refactors the state management of graph-related scenarios

---

sematic/ui/src/hooks/scrollingHooks.ts
sematic/ui/src/pipelines/LogPanel.tsx
sematic/ui/src/pipelines/ScrollingLogView.tsx

Fixes a UI defect in case the run had an exception.
From
:
To:

Fixes UI error in case of exception

---

sematic/ui/src/hooks/graphHooks.ts

When the frontend responds to websocket event (`graph, ["update"])` , it will attempt to call `retry` emitted by 
https://github.com/streamich/react-use/blob/325f5bd69904346788ea981ec18bfc7397c611df/src/useAsyncRetry.ts#L13
However, by the design of [useAsyncRetry](https://github.com/streamich/react-use/blob/325f5bd69904346788ea981ec18bfc7397c611df/src/useAsyncRetry.ts#L13
), if a previous call to the same resource is ongoing, it will stop re-fetch and emits `You are calling useAsyncRetry hook retry() method while loading in progress, this is a no-op.' `
Since the graph call usually takes some time, we could occasionally run into this collision-in-the-air issue, which causes the latter calls to be discarded. 
So this PR changes to waiting on the previous call to finish before attempting …

Fixes a bug on websocket graph reactive callbacks.

---

README.md
docs/README.md
docs/SUMMARY.md
docs/api.md
docs/capabilities.md
docs/cloud-resolver.md
docs/concepts.md
docs/first-pipeline.md
docs/functions.md
docs/get-started.md
docs/glossary.md
docs/local-execution.md
docs/real-example.md
docs/type-support.md
docs/types.md
sematic/future_context.py
sematic/resolver.py
sematic/resolvers/resource_requirements.py
sematic/resolvers/tests/test_type_utils.py
sematic/resolvers/type_utils.py

Refreshing our outdated documentation.
This is a first pass (MVP). It can be merged as is and is already an improvement on the current docs.
See rendering at https://app.gitbook.com/o/imZLVRfMJ5iefBKUWLRh/s/Jn9AQm5pUMgA50IMvjh3/~/revisions/WA5PO5PaOGOCJJe3yz8F/onboarding/readme

Documentation refresh

---

Makefile
README.md
README.rst
developer-docs/README.md
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_version.bzl

Release 0.22.0

---

docs/README.md

Fixes a broken link on the public documentation.

Fix team link on user documentation

---

developer-docs/README.md

Going through the release procedure recently, there are a couple things that could be made a bit easier/more robust. Thanks to @tscurtu for some of these suggestions!

Update release procedure

---

developer-docs/README.md
helm/sematic-server/Chart.yaml
helm/sematic-server/templates/service.yaml

- Fixes the helm repo index url that is used to populate the helm index
- Fixes service creation template that was wrongly negated

Helm release fixes

---

docs/deploy.md

Updated docs on Helm installation instructions.  One item that is still a TODO here (at the very end of the diff) is to create a table in a `README.md` in the `helm-charts` repository that contains a list of all of the possible settings, defaults, and explanations possible in `values.yaml`.

Update Helm deployment instructions

---

requirements/ci-requirements.txt
sematic/container_images.py

Fixes lint and mypy errors on `main`.

Fix lint and mypy errors on main

---

docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_version.bzl

Bump release version to 0.23.0

Bump release version to 0.23.0

---

Makefile
docs/developers/guidelines.md

Add ts linting to `pre-commit` make command. Also added instructions in the developer docs.

Add ts linting to `pre-commit` make command

---

sematic/resolvers/tests/test_local_resolver.py

Fixes lint on `main`, which started failing after a merge commit was pushed.

Fix lint on main

---

helm/sematic-server/values.yaml

Fixes an incorrect setting name.

Fix an incorrect name in the Helm chart

---

docs/SUMMARY.md
docs/changelog.md
docs/deploy.md
docs/upgrades.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release v0.24.1. Please see/review the new "upgrade" docs

Release v0.24.1

---

docs/SUMMARY.md
docs/deploy.md
docs/ray.md
docs/upgrades.md

Add more detailed docs around Ray usage, and refactor how Ray configuration/installation is presented

Add more detailed Ray docs

---

.circleci/config.yml
sematic/ui/package.json
sematic/ui/src/hooks/helperHooks.ts
sematic/ui/src/hooks/tests/helperHook.cy.tsx
sematic/ui/tests/cypress.config.ts
sematic/ui/tests/global.d.ts
sematic/ui/tests/package.json
sematic/ui/tests/support/component-index.html
sematic/ui/tests/support/component.ts
sematic/ui/tsconfig.json

1. Introduced a new React hook `useQueuedAsyncRetry` that will queue a load request if an ongoing loading process is already present.
2. Have a unit test to validate the behavior of the `useQueuedAsyncRetry` in the form of Cypress component test
3. Integrate the Cypress component test into CI.

First cypress component test example

---

sematic/ui/src/index.tsx

Remove the path info from reporting by PostHog

Remove path info

---

docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release 0.26.0

---

sematic/ui/src/Home.tsx
sematic/ui/src/appContext.ts
sematic/ui/src/components/EnvironmentProvider.tsx
sematic/ui/src/components/Shell.tsx
sematic/ui/src/components/SideBar.tsx
sematic/ui/src/hooks/appHooks.ts
sematic/ui/src/hooks/httpHooks.ts
sematic/ui/src/hooks/tests/test_appHooks.cy.tsx
sematic/ui/src/index.tsx
sematic/ui/src/login.tsx
sematic/ui/src/loginGoogle.tsx
sematic/ui/src/pipelines/NotesPanel.tsx
sematic/ui/src/pipelines/PipelineBar.tsx
sematic/ui/src/pipelines/RunDetailsPanel.tsx

Refactors the login workflow with the following features:
1. A new `/login` page handles login logic. 
2. After a successful login, the app will redirect to the previous page that the user has requested. 
3. user info is stored in the local storage using jotai atoms.

Refactors the login workflow

---

sematic/api/endpoints/notes.py
sematic/api/endpoints/tests/test_notes.py
sematic/ui/src/Models.tsx
sematic/ui/src/pipelines/NotesPanel.tsx

Sync the FE to also uses the latest updates from the Note model.

Fixes user field name in a Note model

---

sematic/examples/testing_pipeline/__main__.py
sematic/examples/testing_pipeline/pipeline.py

Adds a function to the Testing Pipeline that produces log messages, which can be used to load test the logging collection mechanism.
Also fixes minor issues and updates docs in the Testing Pipeline.

Add a log spamming func to the Testing Pipeline

---

sematic/ee/plugins/external_resource/ray/cluster.py

Standardizes the Ray external resource messages so that they all have the same structure.
Also updates some exception logs to deduplicate exception printing.

Standardize Ray external resource messages

---

docs/sematic-ui.md

Documents the Graph Panel zooming behavior, following a user request.

Document zooming in the Graph Panel

---

docs/changelog.md
docs/get-started.md
docs/upgrades.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Bump versions for release v0.27.0.

Release 0.27.0

---

docs/deploy.md

Updates the public documentation with clarifications which were prompted by recent user interactions.

Trivial doc update with user instructions

---

sematic/ui/package-lock.json
sematic/ui/packages/common/src/component/menu.tsx
sematic/ui/packages/common/src/layout/Shell.tsx
sematic/ui/packages/common/src/muitypes.d.ts
sematic/ui/packages/common/src/static/fox.tsx
sematic/ui/packages/common/src/theme/new/componnets.ts
sematic/ui/packages/common/src/theme/new/index.ts
sematic/ui/packages/common/src/theme/new/palette.ts
sematic/ui/packages/common/src/theme/new/typography.ts
sematic/ui/packages/storybook/.storybook/main.js
sematic/ui/packages/storybook/package.json
sematic/ui/packages/storybook/src/stories/Button.stories.tsx
sematic/ui/packages/storybook/src/stories/Color.stories.tsx
sematic/ui/packages/storybook/src/stories/Header.stories.tsx
sematic/ui/packages/storybook/src/stories/Link.stories.tsx
sematic/ui/packages/storybook/src/stories/Page.stories.tsx
sematic/ui/packages/storybook/tsconfig.json

Implement the components and styles for the new header bar
Set default component styles for MUI Theme and created button variants for the Logo and MenuItem styles.
Used the SVG component for the branch logo image. 
To preview the current storybook: https://story.dev-usw2-sematic0.sematic.cloud

Implement the components and styles for the new header bar

---

sematic/resolvers/log_streamer.py
sematic/resolvers/tests/test_log_streamer.py

Before this PR, log files would be uploaded every 10 seconds. After this PR, they will be uploaded based on whichever comes earlier:
- 10 seconds passes
- 1000 lines are written to the log file
Why? This should reduce the worst-case "seek time" for picking up the cursor to get the next log lines, since you will have to linear seek through at most 999 lines to get to the line you care about. But more importantly, this will enable a safer way to generate reverse traversal through log files. This ensures that one log file can be kept safely in-memory and reversed. Since the log files from s3 can't be linear-sought backwards, reversing whole files in-memory will be the next-best-thing from a simplicity-of-implementation perspective.
Testing
-------
In addition to the new unit test, launched a …

Limit log file size

---

README.md
README.rst
docs/changelog.md
docs/upgrades.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release 0.28.0

---

sematic/ui/packages/main/src/types/aws.tsx

Enable text selection on S3 buttons

---

docs/deploy.md

Fixes an incorrect statement that specifies setting a Server Setting in the user-facing documentation.

Fix an incorrect settings usage statement in the documentation

---

README.md
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release 0.28.1

---

README.rst
developer-docs/README.md

Updates the Release Procedure to cover including updates to the repo that are being produced during release validation.

Update the Release Procedure to include updates in the release PR

---

sematic/ui/packages/common/src/pages/RunDetails/PipelineSection.tsx
sematic/ui/packages/common/src/pages/RunDetails/RunSection.tsx

Renaming:
- "RUN" to "PIPELINE RUN"
- "average time" to "avg. runtime"
- "success rate" to "success"
My IDE automatically corrected the indentation on these files (4 spaces to 2 spaces).

Minor rewording of certain Dashboard labels

---

helm/sematic-grafana-dashboards/Chart.yaml
helm/sematic-grafana-dashboards/templates/sematic_jobs_dashboard_configmap.yaml
helm/sematic-grafana-dashboards/templates/sematic_server_dashboard_configmap.yaml

borked indentation causes k8s errors

Fix configmap indentation

---

docs/developers/manual.md

Updates the dev manual, after a user reported an out-of-date entry.

Update the dev manual

---

sematic/api/endpoints/runs.py
sematic/api/endpoints/tests/test_runs.py

Runs can't transition from CREATED to FAILED/NESTED_FAILED. The assumption is that the run would not have had a chance to fail if it was never even scheduled (and therefore also had no children). Thus to move it directly to a terminal state, we must move them to CANCELED. This PR updates the cleaning of CREATED orphaned runs to move them to CANCELED.
Testing
-------
In addition to unit tests, deployed in my namespace (where I was seeing some errors related to this and some old orphaned runs) and confirmed that some runs which had not previously been cleanable got cleaned up.

Fix cleaning of runs in the CREATED state

---

README.md
README.rst
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/api/endpoints/runs.py
sematic/ui/packages/main/src/types/image.tsx
sematic/versions.py
sematic/wheel_constants.bzl

Release 0.29.0

---

sematic/api/BUILD
sematic/api/endpoints/BUILD
sematic/api/endpoints/payloads.py
sematic/api/endpoints/tests/BUILD
sematic/api/endpoints/tests/test_users.py
sematic/api/endpoints/users.py
sematic/api/server.py
sematic/db/queries.py

An endpoint to list current users. Needed by the search filters in the new dashboard.

List users endpoint

---

bazel/ray
requirements/requirements.in
requirements/requirements3_10.txt
requirements/requirements3_8.txt
requirements/requirements3_9.txt
sematic/abstract_plugin.py
sematic/plugins/BUILD
sematic/plugins/abstract_builder.py
sematic/plugins/building/BUILD
sematic/plugins/building/docker.py
sematic/plugins/building/docker_builder.py

This is the first PR in a chain that introduces a Build System plugin with an implementation that uses native Python+Docker capabilities to build a container image and launch a pipeline, without requiring Bazel.
This PR introduces the abstract plugin and the Docker plugin implementation first iteration, which for now only works for local pipeline runs and for pipelines with completely custom images, built using a script file.
This functionality is not currently exposed to the users.
There are several places in the new code that specify TODOs. These will be implemented as part of the PR chain.
Unit tests will be introduced in a subsequent PR.
Manually tested using https://github.com/sematic-ai/example_docker/pull/1:
(3.9.14/envs/3.9.14-testing) ~/work/example_docker$ sematic run …

[1/N] Native Build System for custom images

---

sematic/ui/packages/main/src/pipelines/graph/RunNode.tsx

Fixes a DAG view display issue

---

sematic/BUILD
sematic/api_client.py
sematic/ee/BUILD
sematic/ee/metrics.py
sematic/ee/tests/BUILD
sematic/ee/tests/test_metrics.py
sematic/tests/BUILD
sematic/tests/test_api_client.py

This PR introduces the SDK for users to log metrics.
See full design in #732.

[6/N] User metrics SDK

---

README.md
README.rst
docs/changelog.md
docs/upgrades.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Rebased to include the unit test fix.

Release 0.30.0

---

docs/types.md

Fix broken link to Plotly docs

Fix broken Plotly link

---

sematic/plugins/metrics_storage/sql/sql_metrics_storage.py

Metrics were not being explicitly ordered by time, but this PR fixes that.
Testing
-------
Ran locally on an example with a small number of points. Deployed remotely and tried it on [this](https://josh.dev-usw2-sematic0.sematic.cloud/runs/c4371aef921b4cea9f2a6aab4c18a96f#run=72040175dc4a478590b88d72577f53ff&panel=run&tab=metrics)

order metrics by time

---

.gitignore

Adds the new IDEA `.ijwb` project config files to `.gitignore`.

Add new IDEA project config files to gitignore

---

README.md
README.rst
docs/changelog.md
docs/upgrades.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release v0.31.0

---

requirements/requirements.in
requirements/requirements3_10.txt
requirements/requirements3_8.txt
requirements/requirements3_9.txt

Add requirements that will allow adding Hugging Face types and using Hugging Face in examples. Note that this does not add these requirements to the wheel, it just makes them available to be depended on in bazel.

Add requirements for Hugging Face

---

sematic/ui/packages/common/src/layout/ThreeColumns.tsx
sematic/ui/packages/common/src/layout/TwoColumns.tsx
sematic/ui/packages/common/src/pages/PipelineList/PipelineList.tsx
sematic/ui/packages/common/src/pages/PipelineRuns/PipelineInfoPane.tsx
sematic/ui/packages/common/src/pages/PipelineRuns/PipelineRunsList.tsx
sematic/ui/packages/common/src/pages/PipelineRuns/index.tsx
sematic/ui/packages/common/src/pages/RunTableCommon/PresentationalComponent.tsx
sematic/ui/packages/common/src/pages/RunTableCommon/columnDefinition.tsx
sematic/ui/packages/common/src/typeViz/vizMapping.ts
sematic/ui/packages/main/src/index.tsx

A page showing all the resolutions of a pipeline.

Pipeline resolution list

---

sematic/ui/packages/common/src/component/ShellCommand.tsx
sematic/ui/packages/common/src/component/menu.tsx
sematic/ui/packages/common/src/pages/GettingStarted/index.tsx
sematic/ui/packages/common/src/theme/new/components.ts
sematic/ui/packages/main/src/index.tsx

This PR builds a new Getting Started page for the new dashboard.
The change can be previewed from _my_ workspace.

Getting started page (new dashboard version)

---

developer-docs/README.md
docs/upgrades.md

Though this is standard helm usage, people (like me 😆 ) may not know it and find it useful.

Mention helm update in release/upgrade docs

---

sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
sematic/ui/packages/common/src/pages/RunDetails/metrics/Metrics.tsx
sematic/ui/packages/common/src/pages/RunDetails/metrics/MetricsPane.tsx
sematic/ui/packages/common/src/pages/RunDetails/metrics/index.tsx
sematic/ui/packages/common/src/sockets.ts
sematic/ui/packages/common/src/utils/color.ts
sematic/ui/packages/main/src/pipelines/RunMetricsPanel.tsx
sematic/ui/packages/main/src/sockets.ts
sematic/ui/packages/main/src/utils.tsx

Adapt run metrics panel to the new dashboard

---

sematic/ui/packages/common/src/hooks/externalResourceHooks.ts
sematic/ui/packages/common/src/pages/RunDetails/RunTabs.tsx
sematic/ui/packages/common/src/pages/RunDetails/externalResource/ExternalResource.tsx
sematic/ui/packages/common/src/pages/RunDetails/externalResource/ExternalResourceState.tsx
sematic/ui/packages/common/src/pages/RunDetails/externalResource/index.tsx
sematic/ui/packages/main/src/pipelines/external_resource/ExternalResource.tsx

Adapt external resources panel to the new dashboard

---

sematic/ui/packages/common/src/component/Exception.tsx
sematic/ui/packages/common/src/pages/RunDetails/artifacts/OutputPane.tsx
sematic/ui/packages/main/src/pipelines/OutputPanel.tsx

[New dashboard] Show exception message when run failed in output pane

---

sematic/ui/packages/common/src/component/UserMenu.tsx
sematic/ui/packages/main/src/components/SideBar.tsx

Add ways to switch between two UI modes

---

sematic/ui/packages/common/src/utils/datetime.ts

Fixes a bug that we didn't consider day, month, and year components when constructing a duration string.

Fixes a datatime bug

---

sematic/ui/packages/common/src/context/artifactCoordinationContext.ts
sematic/ui/packages/common/src/pages/RunDetails/artifacts/artifact.tsx
sematic/ui/packages/common/src/pages/RunDetails/contextMenus/ArtifactMenu.tsx
sematic/ui/packages/common/src/typeViz/ArtifactVizTemplate.tsx

Support collapse all/expand all for artifact list

---

sematic/runners/state_machine_runner.py

This message can get overly verbose, and isn't really problematic. Will change to debug.

Downgrade a spammy log message

---

sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx

Fixes https://github.com/sematic-ai/sematic/issues/989

Fix a bug in dag view expand/collapse event

---

sematic/db/models/tests/test_job.py
sematic/scheduling/job_details.py

There was some code referencing a "force clean" method that was never implemented. This PR adds that method

Add force clean

---

sematic/examples/summarization_finetune/README.md
sematic/examples/summarization_finetune/__main__.py
sematic/examples/summarization_finetune/interactive.py
sematic/examples/summarization_finetune/pipeline.py
sematic/examples/summarization_finetune/train_eval.py
sematic/types/types/huggingface/model_reference.py
sematic/types/types/huggingface/reference.py
sematic/types/types/huggingface/stored_model.py

Tested 7b model on an AWS g5.12xlarge. [Result](https://josh.dev-usw2-sematic0.sematic.cloud/runs/4add0f674a0842488f2a4525d5f6cb0d)

Add Llama 2 to fine-tuning example

---

README.md
README.rst
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/examples/summarization_finetune/README.md
sematic/examples/summarization_finetune/requirements.txt
sematic/versions.py
sematic/wheel_constants.bzl

Release 0.33.0

---

sematic/ui/packages/common/src/component/RunStateChips.tsx
sematic/ui/packages/common/src/component/RunTree.tsx
sematic/ui/packages/common/src/component/menu.tsx
sematic/ui/packages/common/src/pages/RunDetails/dag/CompoundNode.tsx
sematic/ui/packages/common/src/pages/RunDetails/dag/LeafNode.tsx
sematic/ui/packages/common/src/theme/new/svgfilters.tsx
sematic/ui/packages/storybook/src/stories/RunStateChip.stories.tsx

Improves/fixes the following issues
1. Exchange the positions of "Pipelines" and "Runs" header menu items
2. Restyle the run icons and use the ones with solid circular backgrounds to make the icons more obvious.
3. Fixes visual defects when the run names are too long on both the DAG view and the run tree.
4. Fixes a bug that caused extra space above the header.
Preview:

Some UI improvements

---

docs/metrics.md

We never documented how to create your own pipeline-level metrics. This PR does that.

Document pipeline-level metrics

---

sematic/api/endpoints/tests/test_users.py
sematic/api/server.py
sematic/db/queries.py
sematic/graph.py
sematic/runners/local_runner.py

This PR contains miscellaneous trivial fixes and improvements.

Misc trivial fixes

---

README.md
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/ui/packages/common/src/pages/RunDetails/artifacts/OutputPane.tsx
sematic/versions.py
sematic/wheel_constants.bzl

Release v0.34.0
Add a small front-end improvement to prevent exception message from blinking during graph update.

Release 0.34.0

---

README.rst
developer-docs/README.md

Hint on how to get the correct credential when uploading py wheels to pypi.org.

Add a note related to uploading artifact to pypi.org 

---

README.md
README.rst
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release 0.34.1

---

docs/container-images.md

Fixes an incorrect parameter name in the user-facing documentation.

Trivial fix incorrect parameter documentation

---

README.md
README.rst
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Bump versions for v0.35.0

---

docs/upgrades.md

These updated instructions avoid this issue: https://github.com/sematic-ai/sematic/issues/1080.

Update upgrade docs for dedicated SocketIO deployment

---

README.md
README.rst
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release Sematic version 0.36.0 .

Release v0.36.0

---

README.md
README.rst
developer-docs/README.md
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Bump versions for 0.37.0 release

Bump versions for 0.37.0 release

---

sematic/scheduling/job_details.py
sematic/scheduling/kubernetes.py

Closes #1116 
Make a more robust attempt to collect final pod information and display that in the pods tab before deleting a k8s job.
Testing
--------
Ran a variety of things on the testing pipeline. Here is the final "pods" tab for different scenarios.
Exit with 42 status code
Pod OOM
Pod successful exit
Run canceled from UI
Manually deleted the job with kubectl (ex: outside Sematic)

Add more information about pod before deleting job

---

README.md
README.rst
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/examples/testing_pipeline/pipeline.py
sematic/runners/state_machine_runner.py
sematic/ui/packages/common/src/pages/Home/Blog.tsx
sematic/ui/packages/common/src/pages/Home/blogs.json
sematic/versions.py
sematic/wheel_constants.bzl

Release 0.38.0

---

README.md
README.rst
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release 0.38.1

---

README.md
README.rst
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release 0.39.1 with a small bugfix. Tested the bugfix using local server against both an existing mysql DB and a fresh one.

Release 0.39.1

---

README.md
README.rst
docs/changelog.md
helm/sematic-server/Chart.yaml
sematic/versions.py
sematic/wheel_constants.bzl

Release v0.40.0
